# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BATT5_SRS_GUI.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(969, 677)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.488773, y2:0, stop:0.698864 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.project_tab = QtGui.QWidget()
        self.project_tab.setObjectName(_fromUtf8("project_tab"))
        self.formLayout_4 = QtGui.QFormLayout(self.project_tab)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.projectView_layout = QtGui.QVBoxLayout()
        self.projectView_layout.setObjectName(_fromUtf8("projectView_layout"))
        self.projectView_label = QtGui.QLabel(self.project_tab)
        self.projectView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.projectView_label.setStyleSheet(_fromUtf8("background-color: rgb(182, 206, 227);"))
        self.projectView_label.setObjectName(_fromUtf8("projectView_label"))
        self.projectView_layout.addWidget(self.projectView_label)
        self.project_search = QtGui.QLineEdit(self.project_tab)
        self.project_search.setObjectName(_fromUtf8("project_search"))
        self.projectView_layout.addWidget(self.project_search)
        self.project_tree = QtGui.QTreeWidget(self.project_tab)
        self.project_tree.setObjectName(_fromUtf8("project_tree"))
        item_0 = QtGui.QTreeWidgetItem(self.project_tree)
        item_0 = QtGui.QTreeWidgetItem(self.project_tree)
        item_0 = QtGui.QTreeWidgetItem(self.project_tree)
        self.projectView_layout.addWidget(self.project_tree)
        self.newProject_button = QtGui.QPushButton(self.project_tab)
        self.newProject_button.setObjectName(_fromUtf8("newProject_button"))
        self.projectView_layout.addWidget(self.newProject_button)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.LabelRole, self.projectView_layout)
        self.detailedProjectView_layout = QtGui.QGridLayout()
        self.detailedProjectView_layout.setObjectName(_fromUtf8("detailedProjectView_layout"))
        self.detailedProjectView_label = QtGui.QLabel(self.project_tab)
        self.detailedProjectView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.detailedProjectView_label.setStyleSheet(_fromUtf8("background-color: rgb(182, 206, 227);"))
        self.detailedProjectView_label.setObjectName(_fromUtf8("detailedProjectView_label"))
        self.detailedProjectView_layout.addWidget(self.detailedProjectView_label, 0, 0, 1, 3)
        self.projectName_label = QtGui.QLabel(self.project_tab)
        self.projectName_label.setObjectName(_fromUtf8("projectName_label"))
        self.detailedProjectView_layout.addWidget(self.projectName_label, 1, 0, 1, 1)
        self.browse_button = QtGui.QPushButton(self.project_tab)
        self.browse_button.setObjectName(_fromUtf8("browse_button"))
        self.detailedProjectView_layout.addWidget(self.browse_button, 4, 2, 1, 1)
        self.projectName_text = QtGui.QLineEdit(self.project_tab)
        self.projectName_text.setObjectName(_fromUtf8("projectName_text"))
        self.detailedProjectView_layout.addWidget(self.projectName_text, 1, 1, 1, 1)
        self.binaryFilePath_label = QtGui.QLabel(self.project_tab)
        self.binaryFilePath_label.setObjectName(_fromUtf8("binaryFilePath_label"))
        self.detailedProjectView_layout.addWidget(self.binaryFilePath_label, 4, 0, 1, 1)
        self.projectDescription_label = QtGui.QLabel(self.project_tab)
        self.projectDescription_label.setObjectName(_fromUtf8("projectDescription_label"))
        self.detailedProjectView_layout.addWidget(self.projectDescription_label, 2, 0, 1, 1)
        self.binaryFilePath_text = QtGui.QLineEdit(self.project_tab)
        self.binaryFilePath_text.setObjectName(_fromUtf8("binaryFilePath_text"))
        self.detailedProjectView_layout.addWidget(self.binaryFilePath_text, 4, 1, 1, 1)
        self.binaryFileProperties_label = QtGui.QLabel(self.project_tab)
        self.binaryFileProperties_label.setObjectName(_fromUtf8("binaryFileProperties_label"))
        self.detailedProjectView_layout.addWidget(self.binaryFileProperties_label, 5, 0, 1, 1)
        self.binaryFileProperties_text = QtGui.QTreeWidget(self.project_tab)
        self.binaryFileProperties_text.setObjectName(_fromUtf8("binaryFileProperties_text"))
        item_0 = QtGui.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtGui.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtGui.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtGui.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtGui.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtGui.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtGui.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtGui.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtGui.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtGui.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtGui.QTreeWidgetItem(self.binaryFileProperties_text)
        self.detailedProjectView_layout.addWidget(self.binaryFileProperties_text, 5, 1, 1, 1)
        self.delete_button = QtGui.QPushButton(self.project_tab)
        self.delete_button.setObjectName(_fromUtf8("delete_button"))
        self.detailedProjectView_layout.addWidget(self.delete_button, 6, 0, 1, 1)
        self.save_button = QtGui.QPushButton(self.project_tab)
        self.save_button.setObjectName(_fromUtf8("save_button"))
        self.detailedProjectView_layout.addWidget(self.save_button, 6, 2, 1, 1)
        self.proJectDescription_text = QtGui.QTextEdit(self.project_tab)
        self.proJectDescription_text.setObjectName(_fromUtf8("proJectDescription_text"))
        self.detailedProjectView_layout.addWidget(self.proJectDescription_text, 2, 1, 1, 1)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.detailedProjectView_layout)
        self.tabWidget.addTab(self.project_tab, _fromUtf8(""))
        self.analysis_tab = QtGui.QWidget()
        self.analysis_tab.setObjectName(_fromUtf8("analysis_tab"))
        self.formLayout_3 = QtGui.QFormLayout(self.analysis_tab)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.pluginPOI_layout = QtGui.QVBoxLayout()
        self.pluginPOI_layout.setObjectName(_fromUtf8("pluginPOI_layout"))
        self.pluginPOISelection_layout = QtGui.QGridLayout()
        self.pluginPOISelection_layout.setObjectName(_fromUtf8("pluginPOISelection_layout"))
        self.plugin_label = QtGui.QLabel(self.analysis_tab)
        self.plugin_label.setMinimumSize(QtCore.QSize(0, 10))
        self.plugin_label.setObjectName(_fromUtf8("plugin_label"))
        self.pluginPOISelection_layout.addWidget(self.plugin_label, 0, 0, 1, 1)
        self.POIType_label = QtGui.QLabel(self.analysis_tab)
        self.POIType_label.setMinimumSize(QtCore.QSize(0, 10))
        self.POIType_label.setObjectName(_fromUtf8("POIType_label"))
        self.pluginPOISelection_layout.addWidget(self.POIType_label, 2, 0, 1, 1)
        self.plugin_selection = QtGui.QComboBox(self.analysis_tab)
        self.plugin_selection.setObjectName(_fromUtf8("plugin_selection"))
        self.plugin_selection.addItem(_fromUtf8(""))
        self.plugin_selection.addItem(_fromUtf8(""))
        self.plugin_selection.addItem(_fromUtf8(""))
        self.pluginPOISelection_layout.addWidget(self.plugin_selection, 0, 1, 1, 1)
        self.POIType_selection = QtGui.QComboBox(self.analysis_tab)
        self.POIType_selection.setObjectName(_fromUtf8("POIType_selection"))
        self.POIType_selection.addItem(_fromUtf8(""))
        self.POIType_selection.addItem(_fromUtf8(""))
        self.POIType_selection.addItem(_fromUtf8(""))
        self.pluginPOISelection_layout.addWidget(self.POIType_selection, 2, 1, 1, 1)
        self.pluginPOI_layout.addLayout(self.pluginPOISelection_layout)
        self.POIView_label = QtGui.QLabel(self.analysis_tab)
        self.POIView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.POIView_label.setStyleSheet(_fromUtf8("background-color: rgb(182, 206, 227);"))
        self.POIView_label.setObjectName(_fromUtf8("POIView_label"))
        self.pluginPOI_layout.addWidget(self.POIView_label)
        self.POI_search = QtGui.QLineEdit(self.analysis_tab)
        self.POI_search.setObjectName(_fromUtf8("POI_search"))
        self.pluginPOI_layout.addWidget(self.POI_search)
        self.POI_list = QtGui.QListWidget(self.analysis_tab)
        self.POI_list.setObjectName(_fromUtf8("POI_list"))
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.POI_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.POI_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.POI_list.addItem(item)
        self.pluginPOI_layout.addWidget(self.POI_list)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.LabelRole, self.pluginPOI_layout)
        self.detailedPOI_layout = QtGui.QGridLayout()
        self.detailedPOI_layout.setObjectName(_fromUtf8("detailedPOI_layout"))
        self.detailedPOIView_label = QtGui.QLabel(self.analysis_tab)
        self.detailedPOIView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.detailedPOIView_label.setStyleSheet(_fromUtf8("background-color: rgb(182, 206, 227);"))
        self.detailedPOIView_label.setObjectName(_fromUtf8("detailedPOIView_label"))
        self.detailedPOI_layout.addWidget(self.detailedPOIView_label, 9, 0, 1, 5)
        self.a_button = QtGui.QPushButton(self.analysis_tab)
        self.a_button.setObjectName(_fromUtf8("a_button"))
        self.detailedPOI_layout.addWidget(self.a_button, 9, 6, 1, 1, QtCore.Qt.AlignRight)
        self.o_button = QtGui.QPushButton(self.analysis_tab)
        self.o_button.setObjectName(_fromUtf8("o_button"))
        self.detailedPOI_layout.addWidget(self.o_button, 11, 6, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.POIContentArea_text = QtGui.QTextEdit(self.analysis_tab)
        self.POIContentArea_text.setObjectName(_fromUtf8("POIContentArea_text"))
        self.detailedPOI_layout.addWidget(self.POIContentArea_text, 11, 0, 1, 4)
        self.c_button = QtGui.QPushButton(self.analysis_tab)
        self.c_button.setMinimumSize(QtCore.QSize(0, 0))
        self.c_button.setObjectName(_fromUtf8("c_button"))
        self.detailedPOI_layout.addWidget(self.c_button, 11, 4, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.line = QtGui.QFrame(self.analysis_tab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.detailedPOI_layout.addWidget(self.line, 9, 5, 6, 1)
        self.stop_button = QtGui.QPushButton(self.analysis_tab)
        self.stop_button.setObjectName(_fromUtf8("stop_button"))
        self.detailedPOI_layout.addWidget(self.stop_button, 8, 6, 1, 1)
        self.dynamicAnalysisRun_button = QtGui.QPushButton(self.analysis_tab)
        self.dynamicAnalysisRun_button.setObjectName(_fromUtf8("dynamicAnalysisRun_button"))
        self.detailedPOI_layout.addWidget(self.dynamicAnalysisRun_button, 8, 4, 1, 1)
        self.dynamicAnalysis_label = QtGui.QLabel(self.analysis_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dynamicAnalysis_label.setFont(font)
        self.dynamicAnalysis_label.setObjectName(_fromUtf8("dynamicAnalysis_label"))
        self.detailedPOI_layout.addWidget(self.dynamicAnalysis_label, 8, 3, 1, 1)
        self.staticAnalysisRun_button = QtGui.QPushButton(self.analysis_tab)
        self.staticAnalysisRun_button.setObjectName(_fromUtf8("staticAnalysisRun_button"))
        self.detailedPOI_layout.addWidget(self.staticAnalysisRun_button, 8, 1, 1, 1)
        self.staticAnalysis_label = QtGui.QLabel(self.analysis_tab)
        self.staticAnalysis_label.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.staticAnalysis_label.setFont(font)
        self.staticAnalysis_label.setObjectName(_fromUtf8("staticAnalysis_label"))
        self.detailedPOI_layout.addWidget(self.staticAnalysis_label, 8, 0, 1, 1)
        self.terminal_text = QtGui.QTextEdit(self.analysis_tab)
        self.terminal_text.setObjectName(_fromUtf8("terminal_text"))
        self.detailedPOI_layout.addWidget(self.terminal_text, 12, 0, 3, 4)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.FieldRole, self.detailedPOI_layout)
        self.tabWidget.addTab(self.analysis_tab, _fromUtf8(""))
        self.pluginManagement_tab = QtGui.QWidget()
        self.pluginManagement_tab.setObjectName(_fromUtf8("pluginManagement_tab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.pluginManagement_tab)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pluginView_layout = QtGui.QVBoxLayout()
        self.pluginView_layout.setObjectName(_fromUtf8("pluginView_layout"))
        self.pluginView_label = QtGui.QLabel(self.pluginManagement_tab)
        self.pluginView_label.setEnabled(True)
        self.pluginView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.pluginView_label.setMaximumSize(QtCore.QSize(200, 100))
        self.pluginView_label.setStyleSheet(_fromUtf8("background-color: rgb(182, 206, 227);"))
        self.pluginView_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pluginView_label.setObjectName(_fromUtf8("pluginView_label"))
        self.pluginView_layout.addWidget(self.pluginView_label)
        self.pluginView_search = QtGui.QLineEdit(self.pluginManagement_tab)
        self.pluginView_search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pluginView_search.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.pluginView_search.setObjectName(_fromUtf8("pluginView_search"))
        self.pluginView_layout.addWidget(self.pluginView_search)
        self.pluginView_list = QtGui.QListWidget(self.pluginManagement_tab)
        self.pluginView_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pluginView_list.setObjectName(_fromUtf8("pluginView_list"))
        item = QtGui.QListWidgetItem()
        self.pluginView_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.pluginView_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.pluginView_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.pluginView_list.addItem(item)
        self.pluginView_layout.addWidget(self.pluginView_list)
        self.newPlugin_button = QtGui.QPushButton(self.pluginManagement_tab)
        self.newPlugin_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.newPlugin_button.setObjectName(_fromUtf8("newPlugin_button"))
        self.pluginView_layout.addWidget(self.newPlugin_button)
        self.horizontalLayout.addLayout(self.pluginView_layout)
        self.detailedPluginView_layout = QtGui.QVBoxLayout()
        self.detailedPluginView_layout.setObjectName(_fromUtf8("detailedPluginView_layout"))
        self.detailedPOI_label = QtGui.QLabel(self.pluginManagement_tab)
        self.detailedPOI_label.setMinimumSize(QtCore.QSize(0, 30))
        self.detailedPOI_label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.detailedPOI_label.setStyleSheet(_fromUtf8("background-color: rgb(182, 206, 227);"))
        self.detailedPOI_label.setAlignment(QtCore.Qt.AlignCenter)
        self.detailedPOI_label.setObjectName(_fromUtf8("detailedPOI_label"))
        self.detailedPluginView_layout.addWidget(self.detailedPOI_label)
        self.detailedPluginContent_layout = QtGui.QGridLayout()
        self.detailedPluginContent_layout.setObjectName(_fromUtf8("detailedPluginContent_layout"))
        self.savePOI_button = QtGui.QPushButton(self.pluginManagement_tab)
        self.savePOI_button.setObjectName(_fromUtf8("savePOI_button"))
        self.detailedPluginContent_layout.addWidget(self.savePOI_button, 7, 2, 1, 1)
        self.pluginPredefDataSet_label = QtGui.QLabel(self.pluginManagement_tab)
        self.pluginPredefDataSet_label.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.pluginPredefDataSet_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pluginPredefDataSet_label.setObjectName(_fromUtf8("pluginPredefDataSet_label"))
        self.detailedPluginContent_layout.addWidget(self.pluginPredefDataSet_label, 1, 0, 1, 1)
        self.poi_text = QtGui.QTextEdit(self.pluginManagement_tab)
        self.poi_text.setMinimumSize(QtCore.QSize(500, 0))
        self.poi_text.setMaximumSize(QtCore.QSize(500, 150))
        self.poi_text.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.poi_text.setObjectName(_fromUtf8("poi_text"))
        self.detailedPluginContent_layout.addWidget(self.poi_text, 5, 1, 1, 1)
        self.pluginStructure_label = QtGui.QLabel(self.pluginManagement_tab)
        self.pluginStructure_label.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.pluginStructure_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pluginStructure_label.setObjectName(_fromUtf8("pluginStructure_label"))
        self.detailedPluginContent_layout.addWidget(self.pluginStructure_label, 0, 0, 1, 1)
        self.pluginDescription_text = QtGui.QTextEdit(self.pluginManagement_tab)
        self.pluginDescription_text.setMinimumSize(QtCore.QSize(500, 0))
        self.pluginDescription_text.setMaximumSize(QtCore.QSize(500, 150))
        self.pluginDescription_text.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.pluginDescription_text.setObjectName(_fromUtf8("pluginDescription_text"))
        self.detailedPluginContent_layout.addWidget(self.pluginDescription_text, 3, 1, 1, 1)
        self.outputField_selection = QtGui.QComboBox(self.pluginManagement_tab)
        self.outputField_selection.setMaximumSize(QtCore.QSize(200, 16777215))
        self.outputField_selection.setObjectName(_fromUtf8("outputField_selection"))
        self.outputField_selection.addItem(_fromUtf8(""))
        self.outputField_selection.addItem(_fromUtf8(""))
        self.outputField_selection.addItem(_fromUtf8(""))
        self.detailedPluginContent_layout.addWidget(self.outputField_selection, 4, 1, 1, 1)
        self.poi_label = QtGui.QLabel(self.pluginManagement_tab)
        self.poi_label.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.poi_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.poi_label.setObjectName(_fromUtf8("poi_label"))
        self.detailedPluginContent_layout.addWidget(self.poi_label, 5, 0, 1, 1)
        self.delete_button_2 = QtGui.QPushButton(self.pluginManagement_tab)
        self.delete_button_2.setObjectName(_fromUtf8("delete_button_2"))
        self.detailedPluginContent_layout.addWidget(self.delete_button_2, 7, 0, 1, 1)
        self.pluginName_label = QtGui.QLabel(self.pluginManagement_tab)
        self.pluginName_label.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.pluginName_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pluginName_label.setObjectName(_fromUtf8("pluginName_label"))
        self.detailedPluginContent_layout.addWidget(self.pluginName_label, 2, 0, 1, 1)
        self.pluginPredefDataSet_text = QtGui.QLineEdit(self.pluginManagement_tab)
        self.pluginPredefDataSet_text.setMinimumSize(QtCore.QSize(500, 0))
        self.pluginPredefDataSet_text.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pluginPredefDataSet_text.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.pluginPredefDataSet_text.setObjectName(_fromUtf8("pluginPredefDataSet_text"))
        self.detailedPluginContent_layout.addWidget(self.pluginPredefDataSet_text, 1, 1, 1, 1)
        self.browsePluginStructures_buton = QtGui.QPushButton(self.pluginManagement_tab)
        self.browsePluginStructures_buton.setStyleSheet(_fromUtf8("background-color: rgb(228, 228, 228);"))
        self.browsePluginStructures_buton.setObjectName(_fromUtf8("browsePluginStructures_buton"))
        self.detailedPluginContent_layout.addWidget(self.browsePluginStructures_buton, 1, 2, 1, 1)
        self.pluginStructure_text = QtGui.QLineEdit(self.pluginManagement_tab)
        self.pluginStructure_text.setMinimumSize(QtCore.QSize(500, 0))
        self.pluginStructure_text.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pluginStructure_text.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.pluginStructure_text.setObjectName(_fromUtf8("pluginStructure_text"))
        self.detailedPluginContent_layout.addWidget(self.pluginStructure_text, 0, 1, 1, 1)
        self.browsePluginPredef_button = QtGui.QPushButton(self.pluginManagement_tab)
        self.browsePluginPredef_button.setStyleSheet(_fromUtf8("background-color: rgb(228, 228, 228);"))
        self.browsePluginPredef_button.setObjectName(_fromUtf8("browsePluginPredef_button"))
        self.detailedPluginContent_layout.addWidget(self.browsePluginPredef_button, 0, 2, 1, 1)
        self.pluginDescription_label = QtGui.QLabel(self.pluginManagement_tab)
        self.pluginDescription_label.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.pluginDescription_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pluginDescription_label.setObjectName(_fromUtf8("pluginDescription_label"))
        self.detailedPluginContent_layout.addWidget(self.pluginDescription_label, 3, 0, 1, 1)
        self.pluginName_text = QtGui.QLineEdit(self.pluginManagement_tab)
        self.pluginName_text.setMinimumSize(QtCore.QSize(500, 0))
        self.pluginName_text.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pluginName_text.setStyleSheet(_fromUtf8("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));"))
        self.pluginName_text.setObjectName(_fromUtf8("pluginName_text"))
        self.detailedPluginContent_layout.addWidget(self.pluginName_text, 2, 1, 1, 1)
        self.defaultOutField_label = QtGui.QLabel(self.pluginManagement_tab)
        self.defaultOutField_label.setStyleSheet(_fromUtf8("background-color: rgba(255, 255, 255, 0);"))
        self.defaultOutField_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.defaultOutField_label.setObjectName(_fromUtf8("defaultOutField_label"))
        self.detailedPluginContent_layout.addWidget(self.defaultOutField_label, 4, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.detailedPluginContent_layout.addItem(spacerItem, 6, 1, 1, 1)
        self.detailedPluginView_layout.addLayout(self.detailedPluginContent_layout)
        self.horizontalLayout.addLayout(self.detailedPluginView_layout)
        self.tabWidget.addTab(self.pluginManagement_tab, _fromUtf8(""))
        self.pointsOfInterest_tab = QtGui.QWidget()
        self.pointsOfInterest_tab.setObjectName(_fromUtf8("pointsOfInterest_tab"))
        self.formLayout = QtGui.QFormLayout(self.pointsOfInterest_tab)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.poiView_layout = QtGui.QVBoxLayout()
        self.poiView_layout.setObjectName(_fromUtf8("poiView_layout"))
        self.poiView_label = QtGui.QLabel(self.pointsOfInterest_tab)
        self.poiView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.poiView_label.setStyleSheet(_fromUtf8("background-color: rgb(182, 206, 227);"))
        self.poiView_label.setObjectName(_fromUtf8("poiView_label"))
        self.poiView_layout.addWidget(self.poiView_label)
        self.poiSearchBar_search = QtGui.QLineEdit(self.pointsOfInterest_tab)
        self.poiSearchBar_search.setObjectName(_fromUtf8("poiSearchBar_search"))
        self.poiView_layout.addWidget(self.poiSearchBar_search)
        self.poi_list = QtGui.QListWidget(self.pointsOfInterest_tab)
        self.poi_list.setObjectName(_fromUtf8("poi_list"))
        item = QtGui.QListWidgetItem()
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        self.poi_list.addItem(item)
        self.poiView_layout.addWidget(self.poi_list)
        self.newPOI_button = QtGui.QPushButton(self.pointsOfInterest_tab)
        self.newPOI_button.setObjectName(_fromUtf8("newPOI_button"))
        self.poiView_layout.addWidget(self.newPOI_button, 0, QtCore.Qt.AlignHCenter)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.poiView_layout)
        self.detailedPOIView_layout = QtGui.QGridLayout()
        self.detailedPOIView_layout.setObjectName(_fromUtf8("detailedPOIView_layout"))
        self.deleteSave_layout = QtGui.QHBoxLayout()
        self.deleteSave_layout.setObjectName(_fromUtf8("deleteSave_layout"))
        self.deletePOI_button = QtGui.QPushButton(self.pointsOfInterest_tab)
        self.deletePOI_button.setObjectName(_fromUtf8("deletePOI_button"))
        self.deleteSave_layout.addWidget(self.deletePOI_button, 0, QtCore.Qt.AlignLeft)
        self.savePOI_button_2 = QtGui.QPushButton(self.pointsOfInterest_tab)
        self.savePOI_button_2.setObjectName(_fromUtf8("savePOI_button_2"))
        self.deleteSave_layout.addWidget(self.savePOI_button_2, 0, QtCore.Qt.AlignRight)
        self.detailedPOIView_layout.addLayout(self.deleteSave_layout, 2, 0, 1, 1)
        self.detailedPOIView_text = QtGui.QListView(self.pointsOfInterest_tab)
        self.detailedPOIView_text.setObjectName(_fromUtf8("detailedPOIView_text"))
        self.detailedPOIView_layout.addWidget(self.detailedPOIView_text, 1, 0, 1, 1)
        self.detailedPOIViewSelection_layout = QtGui.QGridLayout()
        self.detailedPOIViewSelection_layout.setObjectName(_fromUtf8("detailedPOIViewSelection_layout"))
        self.pluginPOI_label = QtGui.QLabel(self.pointsOfInterest_tab)
        self.pluginPOI_label.setObjectName(_fromUtf8("pluginPOI_label"))
        self.detailedPOIViewSelection_layout.addWidget(self.pluginPOI_label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.poiType_label = QtGui.QLabel(self.pointsOfInterest_tab)
        self.poiType_label.setObjectName(_fromUtf8("poiType_label"))
        self.detailedPOIViewSelection_layout.addWidget(self.poiType_label, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.typePOI_selection = QtGui.QComboBox(self.pointsOfInterest_tab)
        self.typePOI_selection.setObjectName(_fromUtf8("typePOI_selection"))
        self.typePOI_selection.addItem(_fromUtf8(""))
        self.typePOI_selection.addItem(_fromUtf8(""))
        self.typePOI_selection.addItem(_fromUtf8(""))
        self.detailedPOIViewSelection_layout.addWidget(self.typePOI_selection, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.plugin_selection_2 = QtGui.QComboBox(self.pointsOfInterest_tab)
        self.plugin_selection_2.setObjectName(_fromUtf8("plugin_selection_2"))
        self.plugin_selection_2.addItem(_fromUtf8(""))
        self.plugin_selection_2.addItem(_fromUtf8(""))
        self.plugin_selection_2.addItem(_fromUtf8(""))
        self.detailedPOIViewSelection_layout.addWidget(self.plugin_selection_2, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.detailedPOIView_label_2 = QtGui.QLabel(self.pointsOfInterest_tab)
        self.detailedPOIView_label_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.detailedPOIView_label_2.setFont(font)
        self.detailedPOIView_label_2.setStyleSheet(_fromUtf8("background-color: rgb(182, 206, 227);"))
        self.detailedPOIView_label_2.setObjectName(_fromUtf8("detailedPOIView_label_2"))
        self.detailedPOIViewSelection_layout.addWidget(self.detailedPOIView_label_2, 0, 0, 1, 2)
        self.detailedPOIView_layout.addLayout(self.detailedPOIViewSelection_layout, 0, 0, 1, 1)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.detailedPOIView_layout)
        self.tabWidget.addTab(self.pointsOfInterest_tab, _fromUtf8(""))
        self.documentation_tab = QtGui.QWidget()
        self.documentation_tab.setObjectName(_fromUtf8("documentation_tab"))
        self.formLayout_2 = QtGui.QFormLayout(self.documentation_tab)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.documentView_layout = QtGui.QVBoxLayout()
        self.documentView_layout.setObjectName(_fromUtf8("documentView_layout"))
        self.documentView_label = QtGui.QLabel(self.documentation_tab)
        self.documentView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.documentView_label.setStyleSheet(_fromUtf8("background-color: rgb(182, 206, 227);"))
        self.documentView_label.setAlignment(QtCore.Qt.AlignCenter)
        self.documentView_label.setObjectName(_fromUtf8("documentView_label"))
        self.documentView_layout.addWidget(self.documentView_label)
        self.documentView_search = QtGui.QLineEdit(self.documentation_tab)
        self.documentView_search.setObjectName(_fromUtf8("documentView_search"))
        self.documentView_layout.addWidget(self.documentView_search)
        self.documentView_text = QtGui.QTextEdit(self.documentation_tab)
        self.documentView_text.setObjectName(_fromUtf8("documentView_text"))
        self.documentView_layout.addWidget(self.documentView_text)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.documentView_layout)
        self.detailedDocumentView_layout = QtGui.QVBoxLayout()
        self.detailedDocumentView_layout.setObjectName(_fromUtf8("detailedDocumentView_layout"))
        self.detailedDocumentView_label = QtGui.QLabel(self.documentation_tab)
        self.detailedDocumentView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.detailedDocumentView_label.setStyleSheet(_fromUtf8("background-color: rgb(182, 206, 227);"))
        self.detailedDocumentView_label.setAlignment(QtCore.Qt.AlignCenter)
        self.detailedDocumentView_label.setObjectName(_fromUtf8("detailedDocumentView_label"))
        self.detailedDocumentView_layout.addWidget(self.detailedDocumentView_label)
        self.documentContentArea_text = QtGui.QTextBrowser(self.documentation_tab)
        self.documentContentArea_text.setObjectName(_fromUtf8("documentContentArea_text"))
        self.detailedDocumentView_layout.addWidget(self.documentContentArea_text)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.FieldRole, self.detailedDocumentView_layout)
        self.tabWidget.addTab(self.documentation_tab, _fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.projectView_label.setText(_translate("MainWindow", "                                 Project View", None))
        self.project_search.setText(_translate("MainWindow", "Search", None))
        self.project_tree.headerItem().setText(0, _translate("MainWindow", "Projects", None))
        __sortingEnabled = self.project_tree.isSortingEnabled()
        self.project_tree.setSortingEnabled(False)
        self.project_tree.topLevelItem(0).setText(0, _translate("MainWindow", "Project A", None))
        self.project_tree.topLevelItem(1).setText(0, _translate("MainWindow", "Project B", None))
        self.project_tree.topLevelItem(2).setText(0, _translate("MainWindow", "Project C", None))
        self.project_tree.setSortingEnabled(__sortingEnabled)
        self.newProject_button.setText(_translate("MainWindow", "New", None))
        self.detailedProjectView_label.setText(_translate("MainWindow", "                                                                   Detailed Project View", None))
        self.projectName_label.setText(_translate("MainWindow", "Project Name", None))
        self.browse_button.setText(_translate("MainWindow", "Browse", None))
        self.binaryFilePath_label.setText(_translate("MainWindow", "Binary File Path", None))
        self.projectDescription_label.setText(_translate("MainWindow", "Project Description", None))
        self.binaryFileProperties_label.setText(_translate("MainWindow", "Binary File Properties", None))
        self.binaryFileProperties_text.headerItem().setText(0, _translate("MainWindow", "Name", None))
        self.binaryFileProperties_text.headerItem().setText(1, _translate("MainWindow", "Value", None))
        __sortingEnabled = self.binaryFileProperties_text.isSortingEnabled()
        self.binaryFileProperties_text.setSortingEnabled(False)
        self.binaryFileProperties_text.topLevelItem(0).setText(0, _translate("MainWindow", "OS", None))
        self.binaryFileProperties_text.topLevelItem(0).setText(1, _translate("MainWindow", "Parsed Value", None))
        self.binaryFileProperties_text.topLevelItem(1).setText(0, _translate("MainWindow", "Machine", None))
        self.binaryFileProperties_text.topLevelItem(1).setText(1, _translate("MainWindow", "Parsed Value", None))
        self.binaryFileProperties_text.topLevelItem(2).setText(0, _translate("MainWindow", "Class", None))
        self.binaryFileProperties_text.topLevelItem(2).setText(1, _translate("MainWindow", "Parsed Value", None))
        self.binaryFileProperties_text.topLevelItem(3).setText(0, _translate("MainWindow", "Bits", None))
        self.binaryFileProperties_text.topLevelItem(3).setText(1, _translate("MainWindow", "Parsed Value", None))
        self.binaryFileProperties_text.topLevelItem(4).setText(0, _translate("MainWindow", "Language", None))
        self.binaryFileProperties_text.topLevelItem(4).setText(1, _translate("MainWindow", "Parsed Value", None))
        self.binaryFileProperties_text.topLevelItem(5).setText(0, _translate("MainWindow", "Canary", None))
        self.binaryFileProperties_text.topLevelItem(5).setText(1, _translate("MainWindow", "Parsed Value", None))
        self.binaryFileProperties_text.topLevelItem(6).setText(0, _translate("MainWindow", "Nx", None))
        self.binaryFileProperties_text.topLevelItem(6).setText(1, _translate("MainWindow", "Parsed Value", None))
        self.binaryFileProperties_text.topLevelItem(7).setText(0, _translate("MainWindow", "Pic", None))
        self.binaryFileProperties_text.topLevelItem(7).setText(1, _translate("MainWindow", "Parsed Value", None))
        self.binaryFileProperties_text.topLevelItem(8).setText(0, _translate("MainWindow", "Relocs", None))
        self.binaryFileProperties_text.topLevelItem(8).setText(1, _translate("MainWindow", "Parsed Value", None))
        self.binaryFileProperties_text.topLevelItem(9).setText(0, _translate("MainWindow", "Relro", None))
        self.binaryFileProperties_text.topLevelItem(9).setText(1, _translate("MainWindow", "Parsed Value", None))
        self.binaryFileProperties_text.topLevelItem(10).setText(0, _translate("MainWindow", "Stripped", None))
        self.binaryFileProperties_text.topLevelItem(10).setText(1, _translate("MainWindow", "Parsed Value", None))
        self.binaryFileProperties_text.setSortingEnabled(__sortingEnabled)
        self.delete_button.setText(_translate("MainWindow", "Delete", None))
        self.save_button.setText(_translate("MainWindow", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.project_tab), _translate("MainWindow", "Projects", None))
        self.plugin_label.setText(_translate("MainWindow", "Plugin", None))
        self.POIType_label.setText(_translate("MainWindow", "Point Of Interest Type", None))
        self.plugin_selection.setItemText(0, _translate("MainWindow", "Plugin A", None))
        self.plugin_selection.setItemText(1, _translate("MainWindow", "Plugin B", None))
        self.plugin_selection.setItemText(2, _translate("MainWindow", "Plugin C", None))
        self.POIType_selection.setItemText(0, _translate("MainWindow", "Type A", None))
        self.POIType_selection.setItemText(1, _translate("MainWindow", "Type B", None))
        self.POIType_selection.setItemText(2, _translate("MainWindow", "Type C", None))
        self.POIView_label.setText(_translate("MainWindow", "                   Point Of Interest View", None))
        self.POI_search.setText(_translate("MainWindow", "Search", None))
        __sortingEnabled = self.POI_list.isSortingEnabled()
        self.POI_list.setSortingEnabled(False)
        item = self.POI_list.item(0)
        item.setText(_translate("MainWindow", "POI A", None))
        item = self.POI_list.item(1)
        item.setText(_translate("MainWindow", "POI B", None))
        item = self.POI_list.item(2)
        item.setText(_translate("MainWindow", "POI C", None))
        self.POI_list.setSortingEnabled(__sortingEnabled)
        self.detailedPOIView_label.setText(_translate("MainWindow", "                            Detailed Point Of Interest View", None))
        self.a_button.setText(_translate("MainWindow", "A", None))
        self.o_button.setText(_translate("MainWindow", "O", None))
        self.POIContentArea_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Point Of Interest Content Area</span></p></body></html>", None))
        self.c_button.setText(_translate("MainWindow", "C", None))
        self.stop_button.setText(_translate("MainWindow", "Stop", None))
        self.dynamicAnalysisRun_button.setText(_translate("MainWindow", "Run", None))
        self.dynamicAnalysis_label.setText(_translate("MainWindow", "Dynamic Analysis", None))
        self.staticAnalysisRun_button.setText(_translate("MainWindow", "Run", None))
        self.staticAnalysis_label.setText(_translate("MainWindow", "Static Analysis", None))
        self.terminal_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Terminal Window Content Area</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysis_tab), _translate("MainWindow", "Analysis", None))
        self.pluginView_label.setText(_translate("MainWindow", "Plugin View", None))
        self.pluginView_search.setText(_translate("MainWindow", "Search", None))
        __sortingEnabled = self.pluginView_list.isSortingEnabled()
        self.pluginView_list.setSortingEnabled(False)
        item = self.pluginView_list.item(0)
        item.setText(_translate("MainWindow", "Plugin A", None))
        item = self.pluginView_list.item(1)
        item.setText(_translate("MainWindow", "Plugin B", None))
        item = self.pluginView_list.item(2)
        item.setText(_translate("MainWindow", "Plugin C", None))
        item = self.pluginView_list.item(3)
        item.setText(_translate("MainWindow", "Plugin D", None))
        self.pluginView_list.setSortingEnabled(__sortingEnabled)
        self.newPlugin_button.setText(_translate("MainWindow", "New", None))
        self.detailedPOI_label.setText(_translate("MainWindow", "Detailed Plugin View", None))
        self.savePOI_button.setText(_translate("MainWindow", "Save", None))
        self.pluginPredefDataSet_label.setText(_translate("MainWindow", "Plugin Predefined Data Set", None))
        self.pluginStructure_label.setText(_translate("MainWindow", "Plugin Structure", None))
        self.outputField_selection.setItemText(0, _translate("MainWindow", "Output Field 1", None))
        self.outputField_selection.setItemText(1, _translate("MainWindow", "Output Field 2", None))
        self.outputField_selection.setItemText(2, _translate("MainWindow", "OutputField 3", None))
        self.poi_label.setText(_translate("MainWindow", "Points of Interest", None))
        self.delete_button_2.setText(_translate("MainWindow", "Delete", None))
        self.pluginName_label.setText(_translate("MainWindow", "Plugin Name", None))
        self.browsePluginStructures_buton.setText(_translate("MainWindow", "Browse", None))
        self.browsePluginPredef_button.setText(_translate("MainWindow", "Browse", None))
        self.pluginDescription_label.setText(_translate("MainWindow", "Plugin Description", None))
        self.defaultOutField_label.setText(_translate("MainWindow", "Default Output Field", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pluginManagement_tab), _translate("MainWindow", "Plugin Management", None))
        self.poiView_label.setText(_translate("MainWindow", "                   Point Of Interest View", None))
        self.poiSearchBar_search.setText(_translate("MainWindow", "Search", None))
        __sortingEnabled = self.poi_list.isSortingEnabled()
        self.poi_list.setSortingEnabled(False)
        item = self.poi_list.item(0)
        item.setText(_translate("MainWindow", "POI A", None))
        item = self.poi_list.item(1)
        item.setText(_translate("MainWindow", "POI B", None))
        item = self.poi_list.item(2)
        item.setText(_translate("MainWindow", "POI C", None))
        item = self.poi_list.item(3)
        item.setText(_translate("MainWindow", "POI D", None))
        self.poi_list.setSortingEnabled(__sortingEnabled)
        self.newPOI_button.setText(_translate("MainWindow", "New", None))
        self.deletePOI_button.setText(_translate("MainWindow", "Delete", None))
        self.savePOI_button_2.setText(_translate("MainWindow", "Save", None))
        self.pluginPOI_label.setText(_translate("MainWindow", "Plugin", None))
        self.poiType_label.setText(_translate("MainWindow", "Point of Interest Type", None))
        self.typePOI_selection.setItemText(0, _translate("MainWindow", "Type A", None))
        self.typePOI_selection.setItemText(1, _translate("MainWindow", "Type B", None))
        self.typePOI_selection.setItemText(2, _translate("MainWindow", "Type C", None))
        self.plugin_selection_2.setItemText(0, _translate("MainWindow", "Plugin A", None))
        self.plugin_selection_2.setItemText(1, _translate("MainWindow", "Plugin B", None))
        self.plugin_selection_2.setItemText(2, _translate("MainWindow", "Plugin C", None))
        self.detailedPOIView_label_2.setText(_translate("MainWindow", "                                                            Detailed Point Of Interest View", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pointsOfInterest_tab), _translate("MainWindow", "Points of Interest", None))
        self.documentView_label.setText(_translate("MainWindow", "Document View", None))
        self.documentView_search.setText(_translate("MainWindow", "Search", None))
        self.documentView_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">BEAT Documentation</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Plugin Structure</span></p></body></html>", None))
        self.detailedDocumentView_label.setText(_translate("MainWindow", "Detailed Document View", None))
        self.documentContentArea_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Document Content Area</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documentation_tab), _translate("MainWindow", "Documentation", None))

