# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BATT5_GUI.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BATT5(object):
    def setupUi(self, BATT5):
        BATT5.setObjectName(_fromUtf8("BATT5"))
        BATT5.resize(1142, 894)
        self.central_layout = QtGui.QWidget(BATT5)
        self.central_layout.setObjectName(_fromUtf8("central_layout"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.central_layout)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.central_tabs = QtGui.QTabWidget(self.central_layout)
        self.central_tabs.setObjectName(_fromUtf8("central_tabs"))
        self.analysis_tab = QtGui.QWidget()
        self.analysis_tab.setObjectName(_fromUtf8("analysis_tab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.analysis_tab)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.project_layout = QtGui.QHBoxLayout()
        self.project_layout.setObjectName(_fromUtf8("project_layout"))
        self.project_sublayout = QtGui.QVBoxLayout()
        self.project_sublayout.setObjectName(_fromUtf8("project_sublayout"))
        self.project_box = QtGui.QGroupBox(self.analysis_tab)
        self.project_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.project_box.setAcceptDrops(False)
        self.project_box.setAutoFillBackground(False)
        self.project_box.setStyleSheet(_fromUtf8(""))
        self.project_box.setFlat(False)
        self.project_box.setCheckable(False)
        self.project_box.setObjectName(_fromUtf8("project_box"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.project_box)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.projectSearch_lineEdit = QtGui.QLineEdit(self.project_box)
        self.projectSearch_lineEdit.setMaximumSize(QtCore.QSize(275, 16777215))
        self.projectSearch_lineEdit.setObjectName(_fromUtf8("projectSearch_lineEdit"))
        self.verticalLayout_7.addWidget(self.projectSearch_lineEdit)
        self.projectNavigator_tree = QtGui.QTreeWidget(self.project_box)
        self.projectNavigator_tree.setMinimumSize(QtCore.QSize(275, 0))
        self.projectNavigator_tree.setMaximumSize(QtCore.QSize(250, 16777215))
        self.projectNavigator_tree.setObjectName(_fromUtf8("projectNavigator_tree"))
        item_0 = QtGui.QTreeWidgetItem(self.projectNavigator_tree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.projectNavigator_tree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.projectNavigator_tree)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        self.verticalLayout_7.addWidget(self.projectNavigator_tree)
        self.projectProperties_text = QtGui.QTextBrowser(self.project_box)
        self.projectProperties_text.setMinimumSize(QtCore.QSize(275, 0))
        self.projectProperties_text.setMaximumSize(QtCore.QSize(250, 16777215))
        self.projectProperties_text.setObjectName(_fromUtf8("projectProperties_text"))
        self.verticalLayout_7.addWidget(self.projectProperties_text)
        self.project_sublayout.addWidget(self.project_box)
        self.pluginSelection_box = QtGui.QGroupBox(self.analysis_tab)
        self.pluginSelection_box.setMinimumSize(QtCore.QSize(250, 65))
        self.pluginSelection_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pluginSelection_box.setObjectName(_fromUtf8("pluginSelection_box"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.pluginSelection_box)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.pluginSelection_dropdown = QtGui.QComboBox(self.pluginSelection_box)
        self.pluginSelection_dropdown.setMinimumSize(QtCore.QSize(275, 0))
        self.pluginSelection_dropdown.setMaximumSize(QtCore.QSize(245, 16777215))
        self.pluginSelection_dropdown.setObjectName(_fromUtf8("pluginSelection_dropdown"))
        self.pluginSelection_dropdown.addItem(_fromUtf8(""))
        self.pluginSelection_dropdown.addItem(_fromUtf8(""))
        self.pluginSelection_dropdown.addItem(_fromUtf8(""))
        self.verticalLayout_8.addWidget(self.pluginSelection_dropdown)
        self.project_sublayout.addWidget(self.pluginSelection_box)
        self.analyisisControls_box = QtGui.QGroupBox(self.analysis_tab)
        self.analyisisControls_box.setMinimumSize(QtCore.QSize(300, 85))
        self.analyisisControls_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.analyisisControls_box.setObjectName(_fromUtf8("analyisisControls_box"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.analyisisControls_box)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.runStaticAnalysis_button = QtGui.QPushButton(self.analyisisControls_box)
        self.runStaticAnalysis_button.setObjectName(_fromUtf8("runStaticAnalysis_button"))
        self.verticalLayout_9.addWidget(self.runStaticAnalysis_button)
        self.runDynamicAnalysis_button = QtGui.QPushButton(self.analyisisControls_box)
        self.runDynamicAnalysis_button.setObjectName(_fromUtf8("runDynamicAnalysis_button"))
        self.verticalLayout_9.addWidget(self.runDynamicAnalysis_button)
        self.project_sublayout.addWidget(self.analyisisControls_box, 0, QtCore.Qt.AlignLeft)
        self.pluginControls_box = QtGui.QGroupBox(self.analysis_tab)
        self.pluginControls_box.setMinimumSize(QtCore.QSize(300, 50))
        self.pluginControls_box.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pluginControls_box.setObjectName(_fromUtf8("pluginControls_box"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.pluginControls_box)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.generateScript_button = QtGui.QPushButton(self.pluginControls_box)
        self.generateScript_button.setObjectName(_fromUtf8("generateScript_button"))
        self.verticalLayout_10.addWidget(self.generateScript_button)
        self.project_sublayout.addWidget(self.pluginControls_box)
        self.project_layout.addLayout(self.project_sublayout)
        self.horizontalLayout_2.addLayout(self.project_layout)
        self.detailedAnalysis_layout = QtGui.QHBoxLayout()
        self.detailedAnalysis_layout.setObjectName(_fromUtf8("detailedAnalysis_layout"))
        self.detailedAnalysis_sublayout = QtGui.QVBoxLayout()
        self.detailedAnalysis_sublayout.setObjectName(_fromUtf8("detailedAnalysis_sublayout"))
        self.analysis_box = QtGui.QGroupBox(self.analysis_tab)
        self.analysis_box.setObjectName(_fromUtf8("analysis_box"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.analysis_box)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.analysis_text = QtGui.QTextEdit(self.analysis_box)
        self.analysis_text.setMinimumSize(QtCore.QSize(0, 0))
        self.analysis_text.setObjectName(_fromUtf8("analysis_text"))
        self.verticalLayout_16.addWidget(self.analysis_text)
        self.detailedAnalysis_sublayout.addWidget(self.analysis_box)
        self.radareConsole_box = QtGui.QGroupBox(self.analysis_tab)
        self.radareConsole_box.setMinimumSize(QtCore.QSize(300, 0))
        self.radareConsole_box.setMaximumSize(QtCore.QSize(16777215, 218))
        self.radareConsole_box.setObjectName(_fromUtf8("radareConsole_box"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.radareConsole_box)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.radareConsole_text = QtGui.QTextEdit(self.radareConsole_box)
        self.radareConsole_text.setMinimumSize(QtCore.QSize(0, 0))
        self.radareConsole_text.setMaximumSize(QtCore.QSize(16777215, 200))
        self.radareConsole_text.setObjectName(_fromUtf8("radareConsole_text"))
        self.verticalLayout_17.addWidget(self.radareConsole_text)
        self.detailedAnalysis_sublayout.addWidget(self.radareConsole_box)
        self.detailedAnalysis_layout.addLayout(self.detailedAnalysis_sublayout)
        self.horizontalLayout_2.addLayout(self.detailedAnalysis_layout)
        self.commentAndPoi_layout = QtGui.QHBoxLayout()
        self.commentAndPoi_layout.setObjectName(_fromUtf8("commentAndPoi_layout"))
        self.commentAndPoi_sublayout = QtGui.QVBoxLayout()
        self.commentAndPoi_sublayout.setObjectName(_fromUtf8("commentAndPoi_sublayout"))
        self.comment_box = QtGui.QGroupBox(self.analysis_tab)
        self.comment_box.setMaximumSize(QtCore.QSize(300, 300))
        self.comment_box.setObjectName(_fromUtf8("comment_box"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.comment_box)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comment_text = QtGui.QTextEdit(self.comment_box)
        self.comment_text.setMinimumSize(QtCore.QSize(0, 0))
        self.comment_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comment_text.setObjectName(_fromUtf8("comment_text"))
        self.verticalLayout_2.addWidget(self.comment_text)
        self.commentButton_layout = QtGui.QGridLayout()
        self.commentButton_layout.setObjectName(_fromUtf8("commentButton_layout"))
        self.commentSave_button = QtGui.QPushButton(self.comment_box)
        self.commentSave_button.setObjectName(_fromUtf8("commentSave_button"))
        self.commentButton_layout.addWidget(self.commentSave_button, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.commentButton_layout.addItem(spacerItem, 0, 1, 1, 1)
        self.commentClear_button = QtGui.QPushButton(self.comment_box)
        self.commentClear_button.setObjectName(_fromUtf8("commentClear_button"))
        self.commentButton_layout.addWidget(self.commentClear_button, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.commentButton_layout)
        self.commentAndPoi_sublayout.addWidget(self.comment_box)
        self.poi_box = QtGui.QGroupBox(self.analysis_tab)
        self.poi_box.setMinimumSize(QtCore.QSize(0, 50))
        self.poi_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.poi_box.setObjectName(_fromUtf8("poi_box"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.poi_box)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.poi_layout = QtGui.QGridLayout()
        self.poi_layout.setObjectName(_fromUtf8("poi_layout"))
        self.poiType_label = QtGui.QLabel(self.poi_box)
        self.poiType_label.setObjectName(_fromUtf8("poiType_label"))
        self.poi_layout.addWidget(self.poiType_label, 0, 0, 1, 1)
        self.poiType_dropdown = QtGui.QComboBox(self.poi_box)
        self.poiType_dropdown.setObjectName(_fromUtf8("poiType_dropdown"))
        self.poi_layout.addWidget(self.poiType_dropdown, 0, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.poi_layout)
        self.poiSearch_lineEdit = QtGui.QLineEdit(self.poi_box)
        self.poiSearch_lineEdit.setObjectName(_fromUtf8("poiSearch_lineEdit"))
        self.verticalLayout_11.addWidget(self.poiSearch_lineEdit)
        self.poi_list = QtGui.QListWidget(self.poi_box)
        self.poi_list.setMinimumSize(QtCore.QSize(275, 0))
        self.poi_list.setObjectName(_fromUtf8("poi_list"))
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        item = QtGui.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.poi_list.addItem(item)
        self.verticalLayout_11.addWidget(self.poi_list)
        self.commentAndPoi_sublayout.addWidget(self.poi_box)
        self.commentAndPoi_layout.addLayout(self.commentAndPoi_sublayout)
        self.horizontalLayout_2.addLayout(self.commentAndPoi_layout)
        self.central_tabs.addTab(self.analysis_tab, _fromUtf8(""))
        self.management_tab = QtGui.QWidget()
        self.management_tab.setObjectName(_fromUtf8("management_tab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.management_tab)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.management_layout = QtGui.QVBoxLayout()
        self.management_layout.setObjectName(_fromUtf8("management_layout"))
        self.pluginManagement_box = QtGui.QGroupBox(self.management_tab)
        self.pluginManagement_box.setMinimumSize(QtCore.QSize(200, 0))
        self.pluginManagement_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pluginManagement_box.setStyleSheet(_fromUtf8(""))
        self.pluginManagement_box.setObjectName(_fromUtf8("pluginManagement_box"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.pluginManagement_box)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.pluginManagementSearch_lineEdit = QtGui.QLineEdit(self.pluginManagement_box)
        self.pluginManagementSearch_lineEdit.setObjectName(_fromUtf8("pluginManagementSearch_lineEdit"))
        self.verticalLayout_12.addWidget(self.pluginManagementSearch_lineEdit)
        self.pluginManagement_list = QtGui.QListWidget(self.pluginManagement_box)
        self.pluginManagement_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pluginManagement_list.setObjectName(_fromUtf8("pluginManagement_list"))
        self.verticalLayout_12.addWidget(self.pluginManagement_list)
        self.pluginManagementNew_button = QtGui.QPushButton(self.pluginManagement_box)
        self.pluginManagementNew_button.setObjectName(_fromUtf8("pluginManagementNew_button"))
        self.verticalLayout_12.addWidget(self.pluginManagementNew_button)
        self.management_layout.addWidget(self.pluginManagement_box, 0, QtCore.Qt.AlignLeft)
        self.poiManagement_box = QtGui.QGroupBox(self.management_tab)
        self.poiManagement_box.setMinimumSize(QtCore.QSize(200, 0))
        self.poiManagement_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.poiManagement_box.setObjectName(_fromUtf8("poiManagement_box"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.poiManagement_box)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.poiManagementSeach_lineEdit = QtGui.QLineEdit(self.poiManagement_box)
        self.poiManagementSeach_lineEdit.setObjectName(_fromUtf8("poiManagementSeach_lineEdit"))
        self.verticalLayout_14.addWidget(self.poiManagementSeach_lineEdit)
        self.poiManagement_list = QtGui.QListWidget(self.poiManagement_box)
        self.poiManagement_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.poiManagement_list.setObjectName(_fromUtf8("poiManagement_list"))
        self.verticalLayout_14.addWidget(self.poiManagement_list)
        self.poiManagementNew_button = QtGui.QPushButton(self.poiManagement_box)
        self.poiManagementNew_button.setObjectName(_fromUtf8("poiManagementNew_button"))
        self.verticalLayout_14.addWidget(self.poiManagementNew_button)
        self.management_layout.addWidget(self.poiManagement_box, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addLayout(self.management_layout)
        self.detailed_layout = QtGui.QVBoxLayout()
        self.detailed_layout.setObjectName(_fromUtf8("detailed_layout"))
        self.dpm_box = QtGui.QGroupBox(self.management_tab)
        self.dpm_box.setObjectName(_fromUtf8("dpm_box"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.dpm_box)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.dpm_layout = QtGui.QGridLayout()
        self.dpm_layout.setObjectName(_fromUtf8("dpm_layout"))
        self.dpm_comboBox = QtGui.QComboBox(self.dpm_box)
        self.dpm_comboBox.setMaximumSize(QtCore.QSize(200, 200))
        self.dpm_comboBox.setObjectName(_fromUtf8("dpm_comboBox"))
        self.dpm_layout.addWidget(self.dpm_comboBox, 5, 1, 1, 1)
        self.dpmPluginPredefined_lineEdit = QtGui.QLineEdit(self.dpm_box)
        self.dpmPluginPredefined_lineEdit.setObjectName(_fromUtf8("dpmPluginPredefined_lineEdit"))
        self.dpm_layout.addWidget(self.dpmPluginPredefined_lineEdit, 2, 1, 1, 1)
        self.dpmPluginStructure_lineEdit = QtGui.QLineEdit(self.dpm_box)
        self.dpmPluginStructure_lineEdit.setObjectName(_fromUtf8("dpmPluginStructure_lineEdit"))
        self.dpm_layout.addWidget(self.dpmPluginStructure_lineEdit, 1, 1, 1, 1)
        self.dpmDelete_button = QtGui.QPushButton(self.dpm_box)
        self.dpmDelete_button.setObjectName(_fromUtf8("dpmDelete_button"))
        self.dpm_layout.addWidget(self.dpmDelete_button, 8, 0, 1, 1)
        self.dpmPluginDescription_label = QtGui.QLabel(self.dpm_box)
        self.dpmPluginDescription_label.setObjectName(_fromUtf8("dpmPluginDescription_label"))
        self.dpm_layout.addWidget(self.dpmPluginDescription_label, 4, 0, 1, 1)
        self.dpmPluginName_lineEdit = QtGui.QLineEdit(self.dpm_box)
        self.dpmPluginName_lineEdit.setObjectName(_fromUtf8("dpmPluginName_lineEdit"))
        self.dpm_layout.addWidget(self.dpmPluginName_lineEdit, 3, 1, 1, 1)
        self.dpmDefaultOutputField_label = QtGui.QLabel(self.dpm_box)
        self.dpmDefaultOutputField_label.setObjectName(_fromUtf8("dpmDefaultOutputField_label"))
        self.dpm_layout.addWidget(self.dpmDefaultOutputField_label, 5, 0, 1, 1)
        self.dpmPluginPredefined_label = QtGui.QLabel(self.dpm_box)
        self.dpmPluginPredefined_label.setObjectName(_fromUtf8("dpmPluginPredefined_label"))
        self.dpm_layout.addWidget(self.dpmPluginPredefined_label, 2, 0, 1, 1)
        self.dpmPluginName_label = QtGui.QLabel(self.dpm_box)
        self.dpmPluginName_label.setObjectName(_fromUtf8("dpmPluginName_label"))
        self.dpm_layout.addWidget(self.dpmPluginName_label, 3, 0, 1, 1)
        self.dpmPoi_textEdit = QtGui.QTextEdit(self.dpm_box)
        self.dpmPoi_textEdit.setMaximumSize(QtCore.QSize(16777215, 75))
        self.dpmPoi_textEdit.setObjectName(_fromUtf8("dpmPoi_textEdit"))
        self.dpm_layout.addWidget(self.dpmPoi_textEdit, 6, 1, 1, 1)
        self.dpmPluginDescription_textEdit = QtGui.QTextEdit(self.dpm_box)
        self.dpmPluginDescription_textEdit.setMaximumSize(QtCore.QSize(16777215, 75))
        self.dpmPluginDescription_textEdit.setObjectName(_fromUtf8("dpmPluginDescription_textEdit"))
        self.dpm_layout.addWidget(self.dpmPluginDescription_textEdit, 4, 1, 1, 1)
        self.dpmSave_button = QtGui.QPushButton(self.dpm_box)
        self.dpmSave_button.setObjectName(_fromUtf8("dpmSave_button"))
        self.dpm_layout.addWidget(self.dpmSave_button, 8, 2, 1, 1)
        self.dpmPluginStructure_label = QtGui.QLabel(self.dpm_box)
        self.dpmPluginStructure_label.setObjectName(_fromUtf8("dpmPluginStructure_label"))
        self.dpm_layout.addWidget(self.dpmPluginStructure_label, 1, 0, 1, 1)
        self.dpmPoi_label = QtGui.QLabel(self.dpm_box)
        self.dpmPoi_label.setObjectName(_fromUtf8("dpmPoi_label"))
        self.dpm_layout.addWidget(self.dpmPoi_label, 6, 0, 1, 1)
        self.dpmPluginStructure_button = QtGui.QPushButton(self.dpm_box)
        self.dpmPluginStructure_button.setObjectName(_fromUtf8("dpmPluginStructure_button"))
        self.dpm_layout.addWidget(self.dpmPluginStructure_button, 1, 2, 1, 1)
        self.dpmPluginPredefined_button = QtGui.QPushButton(self.dpm_box)
        self.dpmPluginPredefined_button.setObjectName(_fromUtf8("dpmPluginPredefined_button"))
        self.dpm_layout.addWidget(self.dpmPluginPredefined_button, 2, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.dpm_layout.addItem(spacerItem1, 7, 1, 1, 1)
        self.verticalLayout_15.addLayout(self.dpm_layout)
        self.detailed_layout.addWidget(self.dpm_box)
        self.dpoim_box = QtGui.QGroupBox(self.management_tab)
        self.dpoim_box.setObjectName(_fromUtf8("dpoim_box"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.dpoim_box)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.dpoim_topGrid = QtGui.QGridLayout()
        self.dpoim_topGrid.setObjectName(_fromUtf8("dpoim_topGrid"))
        self.dpoimPoiType_dropdown = QtGui.QComboBox(self.dpoim_box)
        self.dpoimPoiType_dropdown.setObjectName(_fromUtf8("dpoimPoiType_dropdown"))
        self.dpoim_topGrid.addWidget(self.dpoimPoiType_dropdown, 1, 1, 1, 1)
        self.dpoimPlugin_dropdown = QtGui.QComboBox(self.dpoim_box)
        self.dpoimPlugin_dropdown.setObjectName(_fromUtf8("dpoimPlugin_dropdown"))
        self.dpoim_topGrid.addWidget(self.dpoimPlugin_dropdown, 0, 1, 1, 1)
        self.dpoimPoiType_label = QtGui.QLabel(self.dpoim_box)
        self.dpoimPoiType_label.setObjectName(_fromUtf8("dpoimPoiType_label"))
        self.dpoim_topGrid.addWidget(self.dpoimPoiType_label, 1, 0, 1, 1)
        self.dpoimPlugin_label = QtGui.QLabel(self.dpoim_box)
        self.dpoimPlugin_label.setObjectName(_fromUtf8("dpoimPlugin_label"))
        self.dpoim_topGrid.addWidget(self.dpoimPlugin_label, 0, 0, 1, 1)
        self.verticalLayout_18.addLayout(self.dpoim_topGrid)
        self.dpoim_text = QtGui.QTextEdit(self.dpoim_box)
        self.dpoim_text.setObjectName(_fromUtf8("dpoim_text"))
        self.verticalLayout_18.addWidget(self.dpoim_text)
        self.dpoim_lowGrid = QtGui.QGridLayout()
        self.dpoim_lowGrid.setObjectName(_fromUtf8("dpoim_lowGrid"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.dpoim_lowGrid.addItem(spacerItem2, 0, 1, 1, 1)
        self.dpoimDelete_button = QtGui.QPushButton(self.dpoim_box)
        self.dpoimDelete_button.setObjectName(_fromUtf8("dpoimDelete_button"))
        self.dpoim_lowGrid.addWidget(self.dpoimDelete_button, 0, 0, 1, 1)
        self.dpoimSave_button = QtGui.QPushButton(self.dpoim_box)
        self.dpoimSave_button.setObjectName(_fromUtf8("dpoimSave_button"))
        self.dpoim_lowGrid.addWidget(self.dpoimSave_button, 0, 2, 1, 1)
        self.verticalLayout_18.addLayout(self.dpoim_lowGrid)
        self.detailed_layout.addWidget(self.dpoim_box)
        self.horizontalLayout_3.addLayout(self.detailed_layout)
        self.central_tabs.addTab(self.management_tab, _fromUtf8(""))
        self.verticalLayout_13.addWidget(self.central_tabs)
        BATT5.setCentralWidget(self.central_layout)
        self.menubar = QtGui.QMenuBar(BATT5)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1142, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.file_menu = QtGui.QMenu(self.menubar)
        self.file_menu.setObjectName(_fromUtf8("file_menu"))
        self.windows_menu = QtGui.QMenu(self.menubar)
        self.windows_menu.setObjectName(_fromUtf8("windows_menu"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        BATT5.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(BATT5)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BATT5.setStatusBar(self.statusbar)
        self.actionNew_Project = QtGui.QAction(BATT5)
        self.actionNew_Project.setObjectName(_fromUtf8("actionNew_Project"))
        self.actionSave = QtGui.QAction(BATT5)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionOpen = QtGui.QAction(BATT5)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave_Analysis = QtGui.QAction(BATT5)
        self.actionSave_Analysis.setObjectName(_fromUtf8("actionSave_Analysis"))
        self.actionSave_as = QtGui.QAction(BATT5)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.file_menu.addAction(self.actionNew_Project)
        self.file_menu.addAction(self.actionOpen)
        self.file_menu.addAction(self.actionSave)
        self.file_menu.addAction(self.actionSave_as)
        self.file_menu.addAction(self.actionSave_Analysis)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.windows_menu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(BATT5)
        self.central_tabs.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(BATT5)

    def retranslateUi(self, BATT5):
        BATT5.setWindowTitle(_translate("BATT5", "MainWindow", None))
        self.project_box.setTitle(_translate("BATT5", "Projects", None))
        self.projectSearch_lineEdit.setText(_translate("BATT5", "Search", None))
        self.projectNavigator_tree.headerItem().setText(0, _translate("BATT5", "Projects", None))
        __sortingEnabled = self.projectNavigator_tree.isSortingEnabled()
        self.projectNavigator_tree.setSortingEnabled(False)
        self.projectNavigator_tree.topLevelItem(0).setText(0, _translate("BATT5", "project 1", None))
        self.projectNavigator_tree.topLevelItem(0).child(0).setText(0, _translate("BATT5", "C:users/custom_path/executable.exe", None))
        self.projectNavigator_tree.topLevelItem(1).setText(0, _translate("BATT5", "project 2", None))
        self.projectNavigator_tree.topLevelItem(1).child(0).setText(0, _translate("BATT5", "C:path/some/random/path/ping.exe", None))
        self.projectNavigator_tree.topLevelItem(2).setText(0, _translate("BATT5", "project 3", None))
        self.projectNavigator_tree.topLevelItem(2).child(0).setText(0, _translate("BATT5", "C:Documents/docs/idk/executable.exe", None))
        self.projectNavigator_tree.setSortingEnabled(__sortingEnabled)
        self.projectProperties_text.setHtml(_translate("BATT5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; font-weight:600;\">Project Description: </span><span style=\" font-size:7.8pt;\">This is a description of the project that is currently selected.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt; font-weight:600;\">Project Properties:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">OS: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Binary Type:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Machine:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Class:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Bits:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Language:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Canery:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Crypto:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Nx:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Relocs:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Relro:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Stripped:</span></p></body></html>", None))
        self.pluginSelection_box.setTitle(_translate("BATT5", "Plugin Selection", None))
        self.pluginSelection_dropdown.setItemText(0, _translate("BATT5", "Network Plugin", None))
        self.pluginSelection_dropdown.setItemText(1, _translate("BATT5", "Encryption Plugin", None))
        self.pluginSelection_dropdown.setItemText(2, _translate("BATT5", "Graph Plugin", None))
        self.analyisisControls_box.setTitle(_translate("BATT5", "Analysis Controls", None))
        self.runStaticAnalysis_button.setText(_translate("BATT5", "Run Static Analysis", None))
        self.runDynamicAnalysis_button.setText(_translate("BATT5", "Run Dynamic Analysis", None))
        self.pluginControls_box.setTitle(_translate("BATT5", "Plugin Controls", None))
        self.generateScript_button.setText(_translate("BATT5", "Generate Script", None))
        self.analysis_box.setTitle(_translate("BATT5", "Analysis", None))
        self.radareConsole_box.setTitle(_translate("BATT5", "Radare2 Commane Console", None))
        self.radareConsole_text.setHtml(_translate("BATT5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">&gt;&gt; cmd</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>", None))
        self.comment_box.setTitle(_translate("BATT5", "Comment View", None))
        self.commentSave_button.setText(_translate("BATT5", "Save", None))
        self.commentClear_button.setText(_translate("BATT5", "Clear", None))
        self.poi_box.setTitle(_translate("BATT5", "Points of Interest", None))
        self.poiType_label.setText(_translate("BATT5", "Type", None))
        self.poiSearch_lineEdit.setText(_translate("BATT5", "Search", None))
        __sortingEnabled = self.poi_list.isSortingEnabled()
        self.poi_list.setSortingEnabled(False)
        item = self.poi_list.item(0)
        item.setText(_translate("BATT5", "POI A", None))
        item = self.poi_list.item(1)
        item.setText(_translate("BATT5", "POI B", None))
        item = self.poi_list.item(2)
        item.setText(_translate("BATT5", "POI C", None))
        item = self.poi_list.item(3)
        item.setText(_translate("BATT5", "POI D", None))
        item = self.poi_list.item(4)
        item.setText(_translate("BATT5", "POI E", None))
        item = self.poi_list.item(5)
        item.setText(_translate("BATT5", "POI F", None))
        item = self.poi_list.item(6)
        item.setText(_translate("BATT5", "POI G", None))
        item = self.poi_list.item(7)
        item.setText(_translate("BATT5", "POI H", None))
        item = self.poi_list.item(8)
        item.setText(_translate("BATT5", "POI I", None))
        item = self.poi_list.item(9)
        item.setText(_translate("BATT5", "POI J", None))
        item = self.poi_list.item(10)
        item.setText(_translate("BATT5", "POI K", None))
        item = self.poi_list.item(11)
        item.setText(_translate("BATT5", "POI L", None))
        item = self.poi_list.item(12)
        item.setText(_translate("BATT5", "POI M", None))
        item = self.poi_list.item(13)
        item.setText(_translate("BATT5", "POI N", None))
        item = self.poi_list.item(14)
        item.setText(_translate("BATT5", "POI O", None))
        item = self.poi_list.item(15)
        item.setText(_translate("BATT5", "POI P", None))
        item = self.poi_list.item(16)
        item.setText(_translate("BATT5", "POI Q", None))
        item = self.poi_list.item(17)
        item.setText(_translate("BATT5", "POI R", None))
        item = self.poi_list.item(18)
        item.setText(_translate("BATT5", "POI S", None))
        item = self.poi_list.item(19)
        item.setText(_translate("BATT5", "POI T", None))
        item = self.poi_list.item(20)
        item.setText(_translate("BATT5", "POI U", None))
        item = self.poi_list.item(21)
        item.setText(_translate("BATT5", "POI V", None))
        item = self.poi_list.item(22)
        item.setText(_translate("BATT5", "POI W", None))
        item = self.poi_list.item(23)
        item.setText(_translate("BATT5", "POI X", None))
        item = self.poi_list.item(24)
        item.setText(_translate("BATT5", "POI Y", None))
        item = self.poi_list.item(25)
        item.setText(_translate("BATT5", "POI Z", None))
        self.poi_list.setSortingEnabled(__sortingEnabled)
        self.central_tabs.setTabText(self.central_tabs.indexOf(self.analysis_tab), _translate("BATT5", "Analysis", None))
        self.pluginManagement_box.setTitle(_translate("BATT5", "Plugin Management", None))
        self.pluginManagementSearch_lineEdit.setText(_translate("BATT5", "Search", None))
        self.pluginManagementNew_button.setText(_translate("BATT5", "New", None))
        self.poiManagement_box.setTitle(_translate("BATT5", "Points of Interest Management", None))
        self.poiManagementSeach_lineEdit.setText(_translate("BATT5", "Search", None))
        self.poiManagementNew_button.setText(_translate("BATT5", "New", None))
        self.dpm_box.setTitle(_translate("BATT5", "Detailed Plugin Management", None))
        self.dpmDelete_button.setText(_translate("BATT5", "Delete", None))
        self.dpmPluginDescription_label.setText(_translate("BATT5", "Plugin Description", None))
        self.dpmDefaultOutputField_label.setText(_translate("BATT5", "Default Output Field", None))
        self.dpmPluginPredefined_label.setText(_translate("BATT5", "Plugin Predefined Data Set", None))
        self.dpmPluginName_label.setText(_translate("BATT5", "Plugin Name", None))
        self.dpmSave_button.setText(_translate("BATT5", "Save", None))
        self.dpmPluginStructure_label.setText(_translate("BATT5", "Plugin Structure", None))
        self.dpmPoi_label.setText(_translate("BATT5", "Points of Interest", None))
        self.dpmPluginStructure_button.setText(_translate("BATT5", "Browse", None))
        self.dpmPluginPredefined_button.setText(_translate("BATT5", "Browse", None))
        self.dpoim_box.setTitle(_translate("BATT5", "Detailed Points of Interest Management", None))
        self.dpoimPoiType_label.setText(_translate("BATT5", "Point of Interest Type", None))
        self.dpoimPlugin_label.setText(_translate("BATT5", "Plugin", None))
        self.dpoimDelete_button.setText(_translate("BATT5", "Delete", None))
        self.dpoimSave_button.setText(_translate("BATT5", "Save", None))
        self.central_tabs.setTabText(self.central_tabs.indexOf(self.management_tab), _translate("BATT5", "Management", None))
        self.file_menu.setTitle(_translate("BATT5", "File", None))
        self.windows_menu.setTitle(_translate("BATT5", "Windows", None))
        self.menuHelp.setTitle(_translate("BATT5", "Help", None))
        self.actionNew_Project.setText(_translate("BATT5", "New...", None))
        self.actionSave.setText(_translate("BATT5", "Save", None))
        self.actionOpen.setText(_translate("BATT5", "Open...", None))
        self.actionSave_Analysis.setText(_translate("BATT5", "Save Analysis", None))
        self.actionSave_as.setText(_translate("BATT5", "Save as...", None))

