# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BATT5_SRS_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(824, 443)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.projectsTab = QtWidgets.QWidget()
        self.projectsTab.setObjectName("projectsTab")
        self.tabWidget.addTab(self.projectsTab, "")
        self.analysisTab = QtWidgets.QWidget()
        self.analysisTab.setObjectName("analysisTab")
        self.tabWidget.addTab(self.analysisTab, "")
        self.pluginManagementTab = QtWidgets.QWidget()
        self.pluginManagementTab.setObjectName("pluginManagementTab")
        self.tabWidget.addTab(self.pluginManagementTab, "")
        self.pointsOfInterestTab = QtWidgets.QWidget()
        self.pointsOfInterestTab.setObjectName("pointsOfInterestTab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.pointsOfInterestTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 181, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.poiViewLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.poiViewLabel.setObjectName("poiViewLabel")
        self.gridLayout.addWidget(self.poiViewLabel, 0, 0, 1, 1, QtCore.Qt.AlignLeft)
        self.searchPOI = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.searchPOI.setText("")
        self.searchPOI.setObjectName("searchPOI")
        self.gridLayout.addWidget(self.searchPOI, 1, 0, 1, 1)
        self.poiList = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.poiList.setObjectName("poiList")
        item = QtWidgets.QListWidgetItem()
        self.poiList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.poiList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.poiList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.poiList.addItem(item)
        self.gridLayout.addWidget(self.poiList, 2, 0, 1, 1, QtCore.Qt.AlignLeft)

        self.newPOI = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.newPOI.setObjectName("newPOI")
        self.newPOI.clicked.connect(self.new_clicked)

        self.gridLayout.addWidget(self.newPOI, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.pointsOfInterestTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(220, 30, 521, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pluginPOILabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pluginPOILabel.setObjectName("pluginPOILabel")
        self.gridLayout_2.addWidget(self.pluginPOILabel, 0, 0, 1, 1, QtCore.Qt.AlignRight)
        self.pluginPOIDrop = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.pluginPOIDrop.setObjectName("pluginPOIDrop")
        self.pluginPOIDrop.addItem("")
        self.pluginPOIDrop.addItem("")
        self.pluginPOIDrop.addItem("")
        self.gridLayout_2.addWidget(self.pluginPOIDrop, 0, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.typePOIDrop = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.typePOIDrop.setObjectName("typePOIDrop")
        self.typePOIDrop.addItem("")
        self.typePOIDrop.addItem("")
        self.typePOIDrop.addItem("")
        self.gridLayout_2.addWidget(self.typePOIDrop, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.poiTypeLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.poiTypeLabel.setObjectName("poiTypeLabel")
        self.gridLayout_2.addWidget(self.poiTypeLabel, 1, 0, 1, 1, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line_2 = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.listView = QtWidgets.QListView(self.verticalLayoutWidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.deletePOI = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deletePOI.setObjectName("deletePOI")
        self.deletePOI.clicked.connect(self.delete_clicked)

        self.horizontalLayout_3.addWidget(self.deletePOI, 0, QtCore.Qt.AlignLeft)
        self.savePOI = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.savePOI.setObjectName("savePOI")
        self.savePOI.clicked.connect(self.save_clicked)

        self.horizontalLayout_3.addWidget(self.savePOI, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.detailedPOILabel = QtWidgets.QLabel(self.pointsOfInterestTab)
        self.detailedPOILabel.setGeometry(QtCore.QRect(220, 10, 171, 16))
        self.detailedPOILabel.setObjectName("detailedPOILabel")
        self.tabWidget.addTab(self.pointsOfInterestTab, "")
        self.documentationTab = QtWidgets.QWidget()
        self.documentationTab.setObjectName("documentationTab")
        self.tabWidget.addTab(self.documentationTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 824, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def save_clicked(self):
        print("Save POI")

    def new_clicked(self):
        print("New POI")

    def delete_clicked(self):
        print("Delete POI")

    def view_selected(self,item):
        print("Viewing: "+str(item.text()))

    def type_selected(self,text):
        print("Type Selected: "+text)

    def plugin_selected(self,text):
        print("Plugin Selected: "+text)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.projectsTab), _translate("MainWindow", "Projects"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysisTab), _translate("MainWindow", "Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pluginManagementTab), _translate("MainWindow", "Plugin Management"))
        self.poiViewLabel.setText(_translate("MainWindow", "Point Of Interest View"))
        __sortingEnabled = self.poiList.isSortingEnabled()
        self.poiList.setSortingEnabled(False)
        item = self.poiList.item(0)
        item.setText(_translate("MainWindow", "POI A"))
        item = self.poiList.item(1)
        item.setText(_translate("MainWindow", "POI B"))
        item = self.poiList.item(2)
        item.setText(_translate("MainWindow", "POI C"))
        item = self.poiList.item(3)
        self.poiList.itemClicked.connect(self.view_selected)
        item.setText(_translate("MainWindow", "..."))
        self.poiList.setSortingEnabled(__sortingEnabled)
        self.newPOI.setText(_translate("MainWindow", "New"))
        self.pluginPOILabel.setText(_translate("MainWindow", "Plugin"))
        self.pluginPOIDrop.setItemText(0, _translate("MainWindow", "Plugin A"))
        self.pluginPOIDrop.setItemText(1, _translate("MainWindow", "Plugin B"))
        self.pluginPOIDrop.setItemText(2, _translate("MainWindow", "Plugin C"))
        self.pluginPOIDrop.activated[str].connect(self.plugin_selected)
        self.typePOIDrop.setItemText(0, _translate("MainWindow", "Type A"))
        self.typePOIDrop.setItemText(1, _translate("MainWindow", "Type B"))
        self.typePOIDrop.setItemText(2, _translate("MainWindow", "Type C"))
        self.typePOIDrop.activated[str].connect(self.type_selected)
        self.poiTypeLabel.setText(_translate("MainWindow", "Point of Interest Type"))
        self.deletePOI.setText(_translate("MainWindow", "Delete"))
        self.savePOI.setText(_translate("MainWindow", "Save"))
        self.detailedPOILabel.setText(_translate("MainWindow", "Detailed Point of Interest View"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pointsOfInterestTab), _translate("MainWindow", "Points of Interest"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documentationTab), _translate("MainWindow", "Documentation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
