
  
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BATT5_SRS_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!

import sys
import subprocess
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QFont


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(969, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.488773, y2:0, stop:0.698864 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));")
        self.tabWidget.setObjectName("tabWidget")
        self.project_tab = QtWidgets.QWidget()
        self.project_tab.setObjectName("project_tab")
        self.formLayout_4 = QtWidgets.QFormLayout(self.project_tab)
        self.formLayout_4.setObjectName("formLayout_4")
        self.projectView_layout = QtWidgets.QVBoxLayout()
        self.projectView_layout.setObjectName("projectView_layout")
        self.projectView_label = QtWidgets.QLabel(self.project_tab)
        self.projectView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.projectView_label.setStyleSheet("background-color: rgb(182, 206, 227);")
        self.projectView_label.setObjectName("projectView_label")
        self.projectView_layout.addWidget(self.projectView_label)
        self.project_search = QtWidgets.QLineEdit(self.project_tab)
        self.project_search.setObjectName("project_search")
        self.projectView_layout.addWidget(self.project_search)
        self.project_tree = QtWidgets.QTreeWidget(self.project_tab)
        self.project_tree.setObjectName("project_tree")
        item_0 = QtWidgets.QTreeWidgetItem(self.project_tree)
        item_0 = QtWidgets.QTreeWidgetItem(self.project_tree)
        item_0 = QtWidgets.QTreeWidgetItem(self.project_tree)
        self.projectView_layout.addWidget(self.project_tree)
        self.newProject_button = QtWidgets.QPushButton(self.project_tab)
        self.newProject_button.setObjectName("newProject_button")
        self.projectView_layout.addWidget(self.newProject_button)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.projectView_layout)
        self.detailedProjectView_layout = QtWidgets.QGridLayout()
        self.detailedProjectView_layout.setObjectName("detailedProjectView_layout")
        self.detailedProjectView_label = QtWidgets.QLabel(self.project_tab)
        self.detailedProjectView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.detailedProjectView_label.setStyleSheet("background-color: rgb(182, 206, 227);")
        self.detailedProjectView_label.setObjectName("detailedProjectView_label")
        self.detailedProjectView_layout.addWidget(self.detailedProjectView_label, 0, 0, 1, 3)
        self.projectName_label = QtWidgets.QLabel(self.project_tab)
        self.projectName_label.setObjectName("projectName_label")
        self.detailedProjectView_layout.addWidget(self.projectName_label, 1, 0, 1, 1)
        self.browse_button = QtWidgets.QPushButton(self.project_tab)
        self.browse_button.setObjectName("browse_button")
        self.browse_button.clicked.connect(self.showFileExplorer)
        self.detailedProjectView_layout.addWidget(self.browse_button, 4, 2, 1, 1)
        self.projectName_text = QtWidgets.QLineEdit(self.project_tab)
        self.projectName_text.setObjectName("projectName_text")
        self.detailedProjectView_layout.addWidget(self.projectName_text, 1, 1, 1, 1)
        self.binaryFilePath_label = QtWidgets.QLabel(self.project_tab)
        self.binaryFilePath_label.setObjectName("binaryFilePath_label")
        self.detailedProjectView_layout.addWidget(self.binaryFilePath_label, 4, 0, 1, 1)
        self.projectDescription_label = QtWidgets.QLabel(self.project_tab)
        self.projectDescription_label.setObjectName("projectDescription_label")
        self.detailedProjectView_layout.addWidget(self.projectDescription_label, 2, 0, 1, 1)
        self.binaryFilePath_text = QtWidgets.QLineEdit(self.project_tab)
        self.binaryFilePath_text.setObjectName("binaryFilePath_text")
        self.detailedProjectView_layout.addWidget(self.binaryFilePath_text, 4, 1, 1, 1)
        self.binaryFileProperties_label = QtWidgets.QLabel(self.project_tab)
        self.binaryFileProperties_label.setObjectName("binaryFileProperties_label")
        self.detailedProjectView_layout.addWidget(self.binaryFileProperties_label, 5, 0, 1, 1)
        self.binaryFileProperties_text = QtWidgets.QTreeWidget(self.project_tab)
        self.binaryFileProperties_text.setObjectName("binaryFileProperties_text")
        item_0 = QtWidgets.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtWidgets.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtWidgets.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtWidgets.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtWidgets.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtWidgets.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtWidgets.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtWidgets.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtWidgets.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtWidgets.QTreeWidgetItem(self.binaryFileProperties_text)
        item_0 = QtWidgets.QTreeWidgetItem(self.binaryFileProperties_text)
        self.detailedProjectView_layout.addWidget(self.binaryFileProperties_text, 5, 1, 1, 1)
        self.delete_button = QtWidgets.QPushButton(self.project_tab)
        self.delete_button.setObjectName("delete_button")
        self.detailedProjectView_layout.addWidget(self.delete_button, 6, 0, 1, 1)
        self.save_button = QtWidgets.QPushButton(self.project_tab)
        self.save_button.setObjectName("save_button")
        self.save_button.clicked.connect(self.showErrFile)
        self.detailedProjectView_layout.addWidget(self.save_button, 6, 2, 1, 1)
        self.proJectDescription_text = QtWidgets.QTextEdit(self.project_tab)
        self.proJectDescription_text.setObjectName("proJectDescription_text")
        self.detailedProjectView_layout.addWidget(self.proJectDescription_text, 2, 1, 1, 1)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.detailedProjectView_layout)
        self.tabWidget.addTab(self.project_tab, "")
        self.analysis_tab = QtWidgets.QWidget()
        self.analysis_tab.setObjectName("analysis_tab")
        self.formLayout_3 = QtWidgets.QFormLayout(self.analysis_tab)
        self.formLayout_3.setObjectName("formLayout_3")
        self.pluginPOI_layout = QtWidgets.QVBoxLayout()
        self.pluginPOI_layout.setObjectName("pluginPOI_layout")
        self.pluginPOISelection_layout = QtWidgets.QGridLayout()
        self.pluginPOISelection_layout.setObjectName("pluginPOISelection_layout")
        self.plugin_label = QtWidgets.QLabel(self.analysis_tab)
        self.plugin_label.setMinimumSize(QtCore.QSize(0, 10))
        self.plugin_label.setObjectName("plugin_label")
        self.pluginPOISelection_layout.addWidget(self.plugin_label, 0, 0, 1, 1)
        self.POIType_label = QtWidgets.QLabel(self.analysis_tab)
        self.POIType_label.setMinimumSize(QtCore.QSize(0, 10))
        self.POIType_label.setObjectName("POIType_label")
        self.pluginPOISelection_layout.addWidget(self.POIType_label, 2, 0, 1, 1)
        self.plugin_selection = QtWidgets.QComboBox(self.analysis_tab)
        self.plugin_selection.setObjectName("plugin_selection")
        self.plugin_selection.addItem("")
        self.plugin_selection.addItem("")
        self.plugin_selection.addItem("")
        self.pluginPOISelection_layout.addWidget(self.plugin_selection, 0, 1, 1, 1)
        self.POIType_selection = QtWidgets.QComboBox(self.analysis_tab)
        self.POIType_selection.setObjectName("POIType_selection")
        self.POIType_selection.addItem("")
        self.POIType_selection.addItem("")
        self.POIType_selection.addItem("")
        self.pluginPOISelection_layout.addWidget(self.POIType_selection, 2, 1, 1, 1)
        self.pluginPOI_layout.addLayout(self.pluginPOISelection_layout)
        self.POIView_label = QtWidgets.QLabel(self.analysis_tab)
        self.POIView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.POIView_label.setStyleSheet("background-color: rgb(182, 206, 227);")
        self.POIView_label.setObjectName("POIView_label")
        self.pluginPOI_layout.addWidget(self.POIView_label)
        self.POI_search = QtWidgets.QLineEdit(self.analysis_tab)
        self.POI_search.setObjectName("POI_search")
        self.pluginPOI_layout.addWidget(self.POI_search)
        self.POI_list = QtWidgets.QListWidget(self.analysis_tab)
        self.POI_list.setObjectName("POI_list")
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.POI_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.POI_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.POI_list.addItem(item)
        self.pluginPOI_layout.addWidget(self.POI_list)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.pluginPOI_layout)
        self.detailedPOI_layout = QtWidgets.QGridLayout()
        self.detailedPOI_layout.setObjectName("detailedPOI_layout")
        self.detailedPOIView_label = QtWidgets.QLabel(self.analysis_tab)
        self.detailedPOIView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.detailedPOIView_label.setStyleSheet("background-color: rgb(182, 206, 227);")
        self.detailedPOIView_label.setObjectName("detailedPOIView_label")
        self.detailedPOI_layout.addWidget(self.detailedPOIView_label, 9, 0, 1, 5)
        self.a_button = QtWidgets.QPushButton(self.analysis_tab)
        self.a_button.setObjectName("a_button")
        self.detailedPOI_layout.addWidget(self.a_button, 9, 6, 1, 1, QtCore.Qt.AlignRight)
        self.o_button = QtWidgets.QPushButton(self.analysis_tab)
        self.o_button.setObjectName("o_button")
        self.detailedPOI_layout.addWidget(self.o_button, 11, 6, 1, 1, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.POIContentArea_text = QtWidgets.QTextEdit(self.analysis_tab)
        self.POIContentArea_text.setObjectName("POIContentArea_text")
        self.detailedPOI_layout.addWidget(self.POIContentArea_text, 11, 0, 1, 4)
        self.c_button = QtWidgets.QPushButton(self.analysis_tab)
        self.c_button.setMinimumSize(QtCore.QSize(0, 0))
        self.c_button.setObjectName("c_button")
        self.detailedPOI_layout.addWidget(self.c_button, 11, 4, 1, 1, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.line = QtWidgets.QFrame(self.analysis_tab)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.detailedPOI_layout.addWidget(self.line, 9, 5, 6, 1)
        self.stop_button = QtWidgets.QPushButton(self.analysis_tab)
        self.stop_button.setObjectName("stop_button")
        self.detailedPOI_layout.addWidget(self.stop_button, 8, 6, 1, 1)
        self.dynamicAnalysisRun_button = QtWidgets.QPushButton(self.analysis_tab)
        self.dynamicAnalysisRun_button.setObjectName("dynamicAnalysisRun_button")
        self.detailedPOI_layout.addWidget(self.dynamicAnalysisRun_button, 8, 4, 1, 1)
        self.dynamicAnalysis_label = QtWidgets.QLabel(self.analysis_tab)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.dynamicAnalysis_label.setFont(font)
        self.dynamicAnalysis_label.setObjectName("dynamicAnalysis_label")
        self.detailedPOI_layout.addWidget(self.dynamicAnalysis_label, 8, 3, 1, 1)
        self.staticAnalysisRun_button = QtWidgets.QPushButton(self.analysis_tab)
        self.staticAnalysisRun_button.setObjectName("staticAnalysisRun_button")
        self.detailedPOI_layout.addWidget(self.staticAnalysisRun_button, 8, 1, 1, 1)
        self.staticAnalysis_label = QtWidgets.QLabel(self.analysis_tab)
        self.staticAnalysis_label.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.staticAnalysis_label.setFont(font)
        self.staticAnalysis_label.setObjectName("staticAnalysis_label")
        self.detailedPOI_layout.addWidget(self.staticAnalysis_label, 8, 0, 1, 1)
        self.terminal_text = QtWidgets.QTextEdit(self.analysis_tab)
        self.terminal_text.setObjectName("terminal_text")
        self.detailedPOI_layout.addWidget(self.terminal_text, 12, 0, 3, 4)
        self.formLayout_3.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.detailedPOI_layout)
        self.tabWidget.addTab(self.analysis_tab, "")
        self.pluginManagement_tab = QtWidgets.QWidget()
        self.pluginManagement_tab.setObjectName("pluginManagement_tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.pluginManagement_tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pluginView_layout = QtWidgets.QVBoxLayout()
        self.pluginView_layout.setObjectName("pluginView_layout")
        self.pluginView_label = QtWidgets.QLabel(self.pluginManagement_tab)
        self.pluginView_label.setEnabled(True)
        self.pluginView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.pluginView_label.setMaximumSize(QtCore.QSize(200, 100))
        self.pluginView_label.setStyleSheet("background-color: rgb(182, 206, 227);")
        self.pluginView_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pluginView_label.setObjectName("pluginView_label")
        self.pluginView_layout.addWidget(self.pluginView_label)
        self.pluginView_search = QtWidgets.QLineEdit(self.pluginManagement_tab)
        self.pluginView_search.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pluginView_search.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pluginView_search.setObjectName("pluginView_search")
        self.pluginView_layout.addWidget(self.pluginView_search)
        self.pluginView_list = QtWidgets.QListWidget(self.pluginManagement_tab)
        self.pluginView_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pluginView_list.setObjectName("pluginView_list")
        item = QtWidgets.QListWidgetItem()
        self.pluginView_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.pluginView_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.pluginView_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.pluginView_list.addItem(item)
        self.pluginView_layout.addWidget(self.pluginView_list)
        self.newPlugin_button = QtWidgets.QPushButton(self.pluginManagement_tab)
        self.newPlugin_button.setMaximumSize(QtCore.QSize(200, 16777215))
        self.newPlugin_button.setObjectName("newPlugin_button")
        self.pluginView_layout.addWidget(self.newPlugin_button)
        self.horizontalLayout.addLayout(self.pluginView_layout)
        self.detailedPluginView_layout = QtWidgets.QVBoxLayout()
        self.detailedPluginView_layout.setObjectName("detailedPluginView_layout")
        self.detailedPOI_label = QtWidgets.QLabel(self.pluginManagement_tab)
        self.detailedPOI_label.setMinimumSize(QtCore.QSize(0, 30))
        self.detailedPOI_label.setMaximumSize(QtCore.QSize(16777215, 100))
        self.detailedPOI_label.setStyleSheet("background-color: rgb(182, 206, 227);")
        self.detailedPOI_label.setAlignment(QtCore.Qt.AlignCenter)
        self.detailedPOI_label.setObjectName("detailedPOI_label")
        self.detailedPluginView_layout.addWidget(self.detailedPOI_label)
        self.detailedPluginContent_layout = QtWidgets.QGridLayout()
        self.detailedPluginContent_layout.setObjectName("detailedPluginContent_layout")
        self.savePOI_button = QtWidgets.QPushButton(self.pluginManagement_tab)
        self.savePOI_button.setObjectName("savePOI_button")
        self.detailedPluginContent_layout.addWidget(self.savePOI_button, 7, 2, 1, 1)
        self.pluginPredefDataSet_label = QtWidgets.QLabel(self.pluginManagement_tab)
        self.pluginPredefDataSet_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pluginPredefDataSet_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pluginPredefDataSet_label.setObjectName("pluginPredefDataSet_label")
        self.detailedPluginContent_layout.addWidget(self.pluginPredefDataSet_label, 1, 0, 1, 1)
        self.poi_text = QtWidgets.QTextEdit(self.pluginManagement_tab)
        self.poi_text.setMinimumSize(QtCore.QSize(500, 0))
        self.poi_text.setMaximumSize(QtCore.QSize(500, 150))
        self.poi_text.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));")
        self.poi_text.setObjectName("poi_text")
        self.detailedPluginContent_layout.addWidget(self.poi_text, 5, 1, 1, 1)
        self.pluginStructure_label = QtWidgets.QLabel(self.pluginManagement_tab)
        self.pluginStructure_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pluginStructure_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pluginStructure_label.setObjectName("pluginStructure_label")
        self.detailedPluginContent_layout.addWidget(self.pluginStructure_label, 0, 0, 1, 1)
        self.pluginDescription_text = QtWidgets.QTextEdit(self.pluginManagement_tab)
        self.pluginDescription_text.setMinimumSize(QtCore.QSize(500, 0))
        self.pluginDescription_text.setMaximumSize(QtCore.QSize(500, 150))
        self.pluginDescription_text.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pluginDescription_text.setObjectName("pluginDescription_text")
        self.detailedPluginContent_layout.addWidget(self.pluginDescription_text, 3, 1, 1, 1)
        self.outputField_selection = QtWidgets.QComboBox(self.pluginManagement_tab)
        self.outputField_selection.setMaximumSize(QtCore.QSize(200, 16777215))
        self.outputField_selection.setObjectName("outputField_selection")
        self.outputField_selection.addItem("")
        self.outputField_selection.addItem("")
        self.outputField_selection.addItem("")
        self.detailedPluginContent_layout.addWidget(self.outputField_selection, 4, 1, 1, 1)
        self.poi_label = QtWidgets.QLabel(self.pluginManagement_tab)
        self.poi_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.poi_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.poi_label.setObjectName("poi_label")
        self.detailedPluginContent_layout.addWidget(self.poi_label, 5, 0, 1, 1)
        self.delete_button_2 = QtWidgets.QPushButton(self.pluginManagement_tab)
        self.delete_button_2.setObjectName("delete_button_2")
        self.detailedPluginContent_layout.addWidget(self.delete_button_2, 7, 0, 1, 1)
        self.pluginName_label = QtWidgets.QLabel(self.pluginManagement_tab)
        self.pluginName_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pluginName_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pluginName_label.setObjectName("pluginName_label")
        self.detailedPluginContent_layout.addWidget(self.pluginName_label, 2, 0, 1, 1)
        self.pluginPredefDataSet_text = QtWidgets.QLineEdit(self.pluginManagement_tab)
        self.pluginPredefDataSet_text.setMinimumSize(QtCore.QSize(500, 0))
        self.pluginPredefDataSet_text.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pluginPredefDataSet_text.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pluginPredefDataSet_text.setObjectName("pluginPredefDataSet_text")
        self.detailedPluginContent_layout.addWidget(self.pluginPredefDataSet_text, 1, 1, 1, 1)
        self.browsePluginStructures_buton = QtWidgets.QPushButton(self.pluginManagement_tab)
        self.browsePluginStructures_buton.setStyleSheet("background-color: rgb(228, 228, 228);")
        self.browsePluginStructures_buton.setObjectName("browsePluginStructures_buton")
        self.detailedPluginContent_layout.addWidget(self.browsePluginStructures_buton, 1, 2, 1, 1)
        self.pluginStructure_text = QtWidgets.QLineEdit(self.pluginManagement_tab)
        self.pluginStructure_text.setMinimumSize(QtCore.QSize(500, 0))
        self.pluginStructure_text.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pluginStructure_text.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pluginStructure_text.setObjectName("pluginStructure_text")
        self.detailedPluginContent_layout.addWidget(self.pluginStructure_text, 0, 1, 1, 1)
        self.browsePluginPredef_button = QtWidgets.QPushButton(self.pluginManagement_tab)
        self.browsePluginPredef_button.setStyleSheet("background-color: rgb(228, 228, 228);")
        self.browsePluginPredef_button.setObjectName("browsePluginPredef_button")
        self.detailedPluginContent_layout.addWidget(self.browsePluginPredef_button, 0, 2, 1, 1)
        self.pluginDescription_label = QtWidgets.QLabel(self.pluginManagement_tab)
        self.pluginDescription_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.pluginDescription_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.pluginDescription_label.setObjectName("pluginDescription_label")
        self.detailedPluginContent_layout.addWidget(self.pluginDescription_label, 3, 0, 1, 1)
        self.pluginName_text = QtWidgets.QLineEdit(self.pluginManagement_tab)
        self.pluginName_text.setMinimumSize(QtCore.QSize(500, 0))
        self.pluginName_text.setMaximumSize(QtCore.QSize(500, 16777215))
        self.pluginName_text.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.488955, y1:1, x2:0.499409, y2:0.148, stop:0 rgba(240, 240, 240, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pluginName_text.setObjectName("pluginName_text")
        self.detailedPluginContent_layout.addWidget(self.pluginName_text, 2, 1, 1, 1)
        self.defaultOutField_label = QtWidgets.QLabel(self.pluginManagement_tab)
        self.defaultOutField_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.defaultOutField_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.defaultOutField_label.setObjectName("defaultOutField_label")
        self.detailedPluginContent_layout.addWidget(self.defaultOutField_label, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.detailedPluginContent_layout.addItem(spacerItem, 6, 1, 1, 1)
        self.detailedPluginView_layout.addLayout(self.detailedPluginContent_layout)
        self.horizontalLayout.addLayout(self.detailedPluginView_layout)
        self.tabWidget.addTab(self.pluginManagement_tab, "")
        self.pointsOfInterest_tab = QtWidgets.QWidget()
        self.pointsOfInterest_tab.setObjectName("pointsOfInterest_tab")
        self.formLayout = QtWidgets.QFormLayout(self.pointsOfInterest_tab)
        self.formLayout.setObjectName("formLayout")
        self.poiView_layout = QtWidgets.QVBoxLayout()
        self.poiView_layout.setObjectName("poiView_layout")
        self.poiView_label = QtWidgets.QLabel(self.pointsOfInterest_tab)
        self.poiView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.poiView_label.setStyleSheet("background-color: rgb(182, 206, 227);")
        self.poiView_label.setObjectName("poiView_label")
        self.poiView_layout.addWidget(self.poiView_label)
        self.poiSearchBar_search = QtWidgets.QLineEdit(self.pointsOfInterest_tab)
        self.poiSearchBar_search.setObjectName("poiSearchBar_search")
        self.poiView_layout.addWidget(self.poiSearchBar_search)
        self.poi_list = QtWidgets.QListWidget(self.pointsOfInterest_tab)
        self.poi_list.setObjectName("poi_list")
        item = QtWidgets.QListWidgetItem()
        self.poi_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.poi_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.poi_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.poi_list.addItem(item)
        self.poiView_layout.addWidget(self.poi_list)
        self.newPOI_button = QtWidgets.QPushButton(self.pointsOfInterest_tab)
        self.newPOI_button.setObjectName("newPOI_button")
        self.poiView_layout.addWidget(self.newPOI_button, 0, QtCore.Qt.AlignHCenter)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.poiView_layout)
        self.detailedPOIView_layout = QtWidgets.QGridLayout()
        self.detailedPOIView_layout.setObjectName("detailedPOIView_layout")
        self.deleteSave_layout = QtWidgets.QHBoxLayout()
        self.deleteSave_layout.setObjectName("deleteSave_layout")
        self.deletePOI_button = QtWidgets.QPushButton(self.pointsOfInterest_tab)
        self.deletePOI_button.setObjectName("deletePOI_button")
        self.deleteSave_layout.addWidget(self.deletePOI_button, 0, QtCore.Qt.AlignLeft)
        self.savePOI_button_2 = QtWidgets.QPushButton(self.pointsOfInterest_tab)
        self.savePOI_button_2.setObjectName("savePOI_button_2")
        self.deleteSave_layout.addWidget(self.savePOI_button_2, 0, QtCore.Qt.AlignRight)
        self.detailedPOIView_layout.addLayout(self.deleteSave_layout, 2, 0, 1, 1)
        self.detailedPOIView_text = QtWidgets.QListView(self.pointsOfInterest_tab)
        self.detailedPOIView_text.setObjectName("detailedPOIView_text")
        self.detailedPOIView_layout.addWidget(self.detailedPOIView_text, 1, 0, 1, 1)
        self.detailedPOIViewSelection_layout = QtWidgets.QGridLayout()
        self.detailedPOIViewSelection_layout.setObjectName("detailedPOIViewSelection_layout")
        self.pluginPOI_label = QtWidgets.QLabel(self.pointsOfInterest_tab)
        self.pluginPOI_label.setObjectName("pluginPOI_label")
        self.detailedPOIViewSelection_layout.addWidget(self.pluginPOI_label, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.poiType_label = QtWidgets.QLabel(self.pointsOfInterest_tab)
        self.poiType_label.setObjectName("poiType_label")
        self.detailedPOIViewSelection_layout.addWidget(self.poiType_label, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.typePOI_selection = QtWidgets.QComboBox(self.pointsOfInterest_tab)
        self.typePOI_selection.setObjectName("typePOI_selection")
        self.typePOI_selection.addItem("")
        self.typePOI_selection.addItem("")
        self.typePOI_selection.addItem("")
        self.detailedPOIViewSelection_layout.addWidget(self.typePOI_selection, 2, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.plugin_selection_2 = QtWidgets.QComboBox(self.pointsOfInterest_tab)
        self.plugin_selection_2.setObjectName("plugin_selection_2")
        self.plugin_selection_2.addItem("")
        self.plugin_selection_2.addItem("")
        self.plugin_selection_2.addItem("")
        self.detailedPOIViewSelection_layout.addWidget(self.plugin_selection_2, 1, 1, 1, 1, QtCore.Qt.AlignLeft)
        self.detailedPOIView_label_2 = QtWidgets.QLabel(self.pointsOfInterest_tab)
        self.detailedPOIView_label_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.detailedPOIView_label_2.setFont(font)
        self.detailedPOIView_label_2.setStyleSheet("background-color: rgb(182, 206, 227);")
        self.detailedPOIView_label_2.setObjectName("detailedPOIView_label_2")
        self.detailedPOIViewSelection_layout.addWidget(self.detailedPOIView_label_2, 0, 0, 1, 2)
        self.detailedPOIView_layout.addLayout(self.detailedPOIViewSelection_layout, 0, 0, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.detailedPOIView_layout)
        self.tabWidget.addTab(self.pointsOfInterest_tab, "")
        self.documentation_tab = QtWidgets.QWidget()
        self.documentation_tab.setObjectName("documentation_tab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.documentation_tab)
        self.formLayout_2.setObjectName("formLayout_2")
        self.documentView_layout = QtWidgets.QVBoxLayout()
        self.documentView_layout.setObjectName("documentView_layout")
        self.documentView_label = QtWidgets.QLabel(self.documentation_tab)
        self.documentView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.documentView_label.setStyleSheet("background-color: rgb(182, 206, 227);")
        self.documentView_label.setAlignment(QtCore.Qt.AlignCenter)
        self.documentView_label.setObjectName("documentView_label")
        self.documentView_layout.addWidget(self.documentView_label)
        self.documentView_search = QtWidgets.QLineEdit(self.documentation_tab)
        self.documentView_search.setObjectName("documentView_search")
        self.documentView_layout.addWidget(self.documentView_search)
        self.documentView_text = QtWidgets.QTextEdit(self.documentation_tab)
        self.documentView_text.setObjectName("documentView_text")
        self.documentView_layout.addWidget(self.documentView_text)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.documentView_layout)
        self.detailedDocumentView_layout = QtWidgets.QVBoxLayout()
        self.detailedDocumentView_layout.setObjectName("detailedDocumentView_layout")
        self.detailedDocumentView_label = QtWidgets.QLabel(self.documentation_tab)
        self.detailedDocumentView_label.setMinimumSize(QtCore.QSize(0, 30))
        self.detailedDocumentView_label.setStyleSheet("background-color: rgb(182, 206, 227);")
        self.detailedDocumentView_label.setAlignment(QtCore.Qt.AlignCenter)
        self.detailedDocumentView_label.setObjectName("detailedDocumentView_label")
        self.detailedDocumentView_layout.addWidget(self.detailedDocumentView_label)
        self.documentContentArea_text = QtWidgets.QTextBrowser(self.documentation_tab)
        self.documentContentArea_text.setObjectName("documentContentArea_text")
        self.detailedDocumentView_layout.addWidget(self.documentContentArea_text)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.detailedDocumentView_layout)
        self.tabWidget.addTab(self.documentation_tab, "")
        self.horizontalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 969, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.projectView_label.setText(_translate("MainWindow", "                                 Project View"))
        self.project_search.setText(_translate("MainWindow", "Search"))
        self.project_tree.headerItem().setText(0, _translate("MainWindow", "Projects"))
        __sortingEnabled = self.project_tree.isSortingEnabled()
        self.project_tree.setSortingEnabled(False)
        self.project_tree.topLevelItem(0).setText(0, _translate("MainWindow", "Project A"))
        self.project_tree.topLevelItem(1).setText(0, _translate("MainWindow", "Project B"))
        self.project_tree.topLevelItem(2).setText(0, _translate("MainWindow", "Project C"))
        self.project_tree.setSortingEnabled(__sortingEnabled)
        self.newProject_button.setText(_translate("MainWindow", "New"))
        self.detailedProjectView_label.setText(_translate("MainWindow", "                                                                   Detailed Project View"))
        self.projectName_label.setText(_translate("MainWindow", "Project Name"))
        self.browse_button.setText(_translate("MainWindow", "Browse"))
        self.binaryFilePath_label.setText(_translate("MainWindow", "Binary File Path"))
        self.projectDescription_label.setText(_translate("MainWindow", "Project Description"))
        self.binaryFileProperties_label.setText(_translate("MainWindow", "Binary File Properties"))
        self.binaryFileProperties_text.headerItem().setText(0, _translate("MainWindow", "Name"))
        self.binaryFileProperties_text.headerItem().setText(1, _translate("MainWindow", "Value"))
        __sortingEnabled = self.binaryFileProperties_text.isSortingEnabled()
        self.binaryFileProperties_text.setSortingEnabled(False)
        self.binaryFileProperties_text.topLevelItem(0).setText(0, _translate("MainWindow", "OS"))
        self.binaryFileProperties_text.topLevelItem(0).setText(1, _translate("MainWindow", "Parsed Value"))
        self.binaryFileProperties_text.topLevelItem(1).setText(0, _translate("MainWindow", "Machine"))
        self.binaryFileProperties_text.topLevelItem(1).setText(1, _translate("MainWindow", "Parsed Value"))
        self.binaryFileProperties_text.topLevelItem(2).setText(0, _translate("MainWindow", "Class"))
        self.binaryFileProperties_text.topLevelItem(2).setText(1, _translate("MainWindow", "Parsed Value"))
        self.binaryFileProperties_text.topLevelItem(3).setText(0, _translate("MainWindow", "Bits"))
        self.binaryFileProperties_text.topLevelItem(3).setText(1, _translate("MainWindow", "Parsed Value"))
        self.binaryFileProperties_text.topLevelItem(4).setText(0, _translate("MainWindow", "Language"))
        self.binaryFileProperties_text.topLevelItem(4).setText(1, _translate("MainWindow", "Parsed Value"))
        self.binaryFileProperties_text.topLevelItem(5).setText(0, _translate("MainWindow", "Canary"))
        self.binaryFileProperties_text.topLevelItem(5).setText(1, _translate("MainWindow", "Parsed Value"))
        self.binaryFileProperties_text.topLevelItem(6).setText(0, _translate("MainWindow", "Nx"))
        self.binaryFileProperties_text.topLevelItem(6).setText(1, _translate("MainWindow", "Parsed Value"))
        self.binaryFileProperties_text.topLevelItem(7).setText(0, _translate("MainWindow", "Pic"))
        self.binaryFileProperties_text.topLevelItem(7).setText(1, _translate("MainWindow", "Parsed Value"))
        self.binaryFileProperties_text.topLevelItem(8).setText(0, _translate("MainWindow", "Relocs"))
        self.binaryFileProperties_text.topLevelItem(8).setText(1, _translate("MainWindow", "Parsed Value"))
        self.binaryFileProperties_text.topLevelItem(9).setText(0, _translate("MainWindow", "Relro"))
        self.binaryFileProperties_text.topLevelItem(9).setText(1, _translate("MainWindow", "Parsed Value"))
        self.binaryFileProperties_text.topLevelItem(10).setText(0, _translate("MainWindow", "Stripped"))
        self.binaryFileProperties_text.topLevelItem(10).setText(1, _translate("MainWindow", "Parsed Value"))
        self.binaryFileProperties_text.setSortingEnabled(__sortingEnabled)
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.project_tab), _translate("MainWindow", "Projects"))
        self.plugin_label.setText(_translate("MainWindow", "Plugin"))
        self.POIType_label.setText(_translate("MainWindow", "Point Of Interest Type"))
        self.plugin_selection.setItemText(0, _translate("MainWindow", "Plugin A"))
        self.plugin_selection.setItemText(1, _translate("MainWindow", "Plugin B"))
        self.plugin_selection.setItemText(2, _translate("MainWindow", "Plugin C"))
        self.POIType_selection.setItemText(0, _translate("MainWindow", "Type A"))
        self.POIType_selection.setItemText(1, _translate("MainWindow", "Type B"))
        self.POIType_selection.setItemText(2, _translate("MainWindow", "Type C"))
        self.POIView_label.setText(_translate("MainWindow", "                   Point Of Interest View"))
        self.POI_search.setText(_translate("MainWindow", "Search"))
        __sortingEnabled = self.POI_list.isSortingEnabled()
        self.POI_list.setSortingEnabled(False)
        item = self.POI_list.item(0)
        item.setText(_translate("MainWindow", "POI A"))
        item = self.POI_list.item(1)
        item.setText(_translate("MainWindow", "POI B"))
        item = self.POI_list.item(2)
        item.setText(_translate("MainWindow", "POI C"))
        self.POI_list.setSortingEnabled(__sortingEnabled)
        self.detailedPOIView_label.setText(_translate("MainWindow", "                            Detailed Point Of Interest View"))
        self.a_button.setText(_translate("MainWindow", "A"))
        self.o_button.setText(_translate("MainWindow", "O"))
        self.POIContentArea_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Point Of Interest Content Area</span></p></body></html>"))
        self.c_button.setText(_translate("MainWindow", "C"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.dynamicAnalysisRun_button.setText(_translate("MainWindow", "Run"))
        self.dynamicAnalysis_label.setText(_translate("MainWindow", "Dynamic Analysis"))
        self.staticAnalysisRun_button.setText(_translate("MainWindow", "Run"))
        self.staticAnalysis_label.setText(_translate("MainWindow", "Static Analysis"))
        self.terminal_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt;\">Terminal Window Content Area</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.analysis_tab), _translate("MainWindow", "Analysis"))
        self.pluginView_label.setText(_translate("MainWindow", "Plugin View"))
        self.pluginView_search.setText(_translate("MainWindow", "Search"))
        __sortingEnabled = self.pluginView_list.isSortingEnabled()
        self.pluginView_list.setSortingEnabled(False)
        item = self.pluginView_list.item(0)
        item.setText(_translate("MainWindow", "Plugin A"))
        item = self.pluginView_list.item(1)
        item.setText(_translate("MainWindow", "Plugin B"))
        item = self.pluginView_list.item(2)
        item.setText(_translate("MainWindow", "Plugin C"))
        item = self.pluginView_list.item(3)
        item.setText(_translate("MainWindow", "Plugin D"))
        self.pluginView_list.setSortingEnabled(__sortingEnabled)
        self.newPlugin_button.setText(_translate("MainWindow", "New"))
        self.detailedPOI_label.setText(_translate("MainWindow", "Detailed Plugin View"))
        self.savePOI_button.setText(_translate("MainWindow", "Save"))
        self.pluginPredefDataSet_label.setText(_translate("MainWindow", "Plugin Predefined Data Set"))
        self.pluginStructure_label.setText(_translate("MainWindow", "Plugin Structure"))
        self.outputField_selection.setItemText(0, _translate("MainWindow", "Output Field 1"))
        self.outputField_selection.setItemText(1, _translate("MainWindow", "Output Field 2"))
        self.outputField_selection.setItemText(2, _translate("MainWindow", "OutputField 3"))
        self.poi_label.setText(_translate("MainWindow", "Points of Interest"))
        self.delete_button_2.setText(_translate("MainWindow", "Delete"))
        self.pluginName_label.setText(_translate("MainWindow", "Plugin Name"))
        self.browsePluginStructures_buton.setText(_translate("MainWindow", "Browse"))
        self.browsePluginPredef_button.setText(_translate("MainWindow", "Browse"))
        self.pluginDescription_label.setText(_translate("MainWindow", "Plugin Description"))
        self.defaultOutField_label.setText(_translate("MainWindow", "Default Output Field"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pluginManagement_tab), _translate("MainWindow", "Plugin Management"))
        self.poiView_label.setText(_translate("MainWindow", "                   Point Of Interest View"))
        self.poiSearchBar_search.setText(_translate("MainWindow", "Search"))
        __sortingEnabled = self.poi_list.isSortingEnabled()
        self.poi_list.setSortingEnabled(False)
        item = self.poi_list.item(0)
        item.setText(_translate("MainWindow", "POI A"))
        item = self.poi_list.item(1)
        item.setText(_translate("MainWindow", "POI B"))
        item = self.poi_list.item(2)
        item.setText(_translate("MainWindow", "POI C"))
        item = self.poi_list.item(3)
        item.setText(_translate("MainWindow", "POI D"))
        self.poi_list.setSortingEnabled(__sortingEnabled)
        self.newPOI_button.setText(_translate("MainWindow", "New"))
        self.deletePOI_button.setText(_translate("MainWindow", "Delete"))
        self.savePOI_button_2.setText(_translate("MainWindow", "Save"))
        self.pluginPOI_label.setText(_translate("MainWindow", "Plugin"))
        self.poiType_label.setText(_translate("MainWindow", "Point of Interest Type"))
        self.typePOI_selection.setItemText(0, _translate("MainWindow", "Type A"))
        self.typePOI_selection.setItemText(1, _translate("MainWindow", "Type B"))
        self.typePOI_selection.setItemText(2, _translate("MainWindow", "Type C"))
        self.plugin_selection_2.setItemText(0, _translate("MainWindow", "Plugin A"))
        self.plugin_selection_2.setItemText(1, _translate("MainWindow", "Plugin B"))
        self.plugin_selection_2.setItemText(2, _translate("MainWindow", "Plugin C"))
        self.detailedPOIView_label_2.setText(_translate("MainWindow", "                                                            Detailed Point Of Interest View"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pointsOfInterest_tab), _translate("MainWindow", "Points of Interest"))
        self.documentView_label.setText(_translate("MainWindow", "Document View"))
        self.documentView_search.setText(_translate("MainWindow", "Search"))
        self.documentView_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">BEAT Documentation</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Plugin Structure</span></p></body></html>"))
        self.detailedDocumentView_label.setText(_translate("MainWindow", "Detailed Document View"))
        self.documentContentArea_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Document Content Area</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documentation_tab), _translate("MainWindow", "Documentation"))

    def showFileExplorer(self):
        subprocess.Popen(r'explorer')

    def showErrFile(self):
        self.window = ErrFile()
        self.window.show()


class ErrFile(QWidget):
    def __init__(self):
        super(ErrFile, self).__init__()
        self.left = 450
        self.top = 250
        self.width = 420
        self.height = 150

        msg = QLabel("A project is associated with one binary file and cannot be saved \n"
                     "without a binary file. Please provide a binary file.")

        okButton = QPushButton("OK")
        okButton.clicked.connect(self.close)

        hbox = QHBoxLayout()
        hbox.addStretch(10)
        hbox.addWidget(okButton)

        vbox = QVBoxLayout()
        vbox.addStretch(1)
        vbox.addWidget(msg)
        vbox.addLayout(hbox)

        self.setWindowTitle("Error Message: File Specified")
        self.setGeometry(self.left, self.top, self.width, self.height)
        self.setLayout(vbox)


class Errx86(QWidget):
    def __init__(self):
        super(Errx86, self).__init__()
        self.left = 450
        self.top = 250
        self.width = 420
        self.height = 150

        msg = QLabel("The system only supports files that are of x86 architecture")

        okButton = QPushButton("OK")

        hbox = QHBoxLayout()
        hbox.addStretch(10)
        hbox.addWidget(okButton)

        vbox = QVBoxLayout()
        vbox.addStretch(1)
        vbox.addWidget(msg)
        vbox.addLayout(hbox)

        self.setWindowTitle("Error Message: x86 architecture binary file")
        self.setGeometry(self.left, self.top, self.width, self.height)
        self.setLayout(vbox)


class ErrBFile(QWidget):
    def __init__(self):
        super(ErrBFile, self).__init__()
        self.left = 450
        self.top = 250
        self.width = 420
        self.height = 150

        msg = QLabel("(Returning any Radare2's error message if there are issues extracting\n"
                     "properties from the binary file.)")

        okButton = QPushButton("OK")

        hbox = QHBoxLayout()
        hbox.addStretch(10)
        hbox.addWidget(okButton)

        vbox = QVBoxLayout()
        vbox.addStretch(1)
        vbox.addWidget(msg)
        vbox.addLayout(hbox)

        self.setWindowTitle("Error Message: Binary File Property Extraction")
        self.setGeometry(self.left, self.top, self.width, self.height)
        self.setLayout(vbox)