# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newProjectWind.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(533, 503)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.create_button = QtWidgets.QPushButton(Form)
        self.create_button.setObjectName("create_button")
        self.gridLayout.addWidget(self.create_button, 7, 3, 1, 1, QtCore.Qt.AlignRight)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setStyleSheet("background-color: rgb(182, 206, 227);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(Form)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 7, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.browse_button = QtWidgets.QPushButton(Form)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout.addWidget(self.browse_button, 3, 3, 1, 1)
        self.projectDescription_textEdit = QtWidgets.QTextEdit(Form)
        self.projectDescription_textEdit.setMaximumSize(QtCore.QSize(16777215, 100))
        self.projectDescription_textEdit.setObjectName("projectDescription_textEdit")
        self.gridLayout.addWidget(self.projectDescription_textEdit, 2, 1, 1, 1)
        self.projectName_lineEdit = QtWidgets.QLineEdit(Form)
        self.projectName_lineEdit.setObjectName("projectName_lineEdit")
        self.gridLayout.addWidget(self.projectName_lineEdit, 1, 1, 1, 1)
        self.properties_treeWidget = QtWidgets.QTreeWidget(Form)
        self.properties_treeWidget.setObjectName("properties_treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.properties_treeWidget)
        self.gridLayout.addWidget(self.properties_treeWidget, 5, 1, 1, 1)
        self.path_lineEdit = QtWidgets.QLineEdit(Form)
        self.path_lineEdit.setReadOnly(True)
        self.path_lineEdit.setClearButtonEnabled(False)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.gridLayout.addWidget(self.path_lineEdit, 3, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Project Name"))
        self.create_button.setText(_translate("Form", "Create"))
        self.label.setText(_translate("Form", "Create A New Project"))
        self.label_5.setText(_translate("Form", "Binary File Properties"))
        self.cancel_button.setText(_translate("Form", "Cancel"))
        self.label_4.setText(_translate("Form", "Binary File Path"))
        self.label_3.setText(_translate("Form", "Project Description"))
        self.browse_button.setText(_translate("Form", "Browse"))
        self.properties_treeWidget.headerItem().setText(0, _translate("Form", "Name"))
        self.properties_treeWidget.headerItem().setText(1, _translate("Form", "Value"))
        __sortingEnabled = self.properties_treeWidget.isSortingEnabled()
        self.properties_treeWidget.setSortingEnabled(False)
        self.properties_treeWidget.topLevelItem(0).setText(0, _translate("Form", "OS"))
        self.properties_treeWidget.topLevelItem(1).setText(0, _translate("Form", "Arch"))
        self.properties_treeWidget.topLevelItem(2).setText(0, _translate("Form", "Binary Type"))
        self.properties_treeWidget.topLevelItem(3).setText(0, _translate("Form", "Machine"))
        self.properties_treeWidget.topLevelItem(4).setText(0, _translate("Form", "Class"))
        self.properties_treeWidget.topLevelItem(5).setText(0, _translate("Form", "Bits"))
        self.properties_treeWidget.topLevelItem(6).setText(0, _translate("Form", "Language"))
        self.properties_treeWidget.topLevelItem(7).setText(0, _translate("Form", "Canary"))
        self.properties_treeWidget.topLevelItem(8).setText(0, _translate("Form", "Crypto"))
        self.properties_treeWidget.topLevelItem(9).setText(0, _translate("Form", "Nx"))
        self.properties_treeWidget.topLevelItem(10).setText(0, _translate("Form", "Pic"))
        self.properties_treeWidget.topLevelItem(11).setText(0, _translate("Form", "Relocs"))
        self.properties_treeWidget.topLevelItem(12).setText(0, _translate("Form", "Relro"))
        self.properties_treeWidget.topLevelItem(13).setText(0, _translate("Form", "Stripped"))
        self.properties_treeWidget.setSortingEnabled(__sortingEnabled)
