# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BATT5_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BATT5(object):
    def setupUi(self, BATT5):
        BATT5.setObjectName("BATT5")
        BATT5.resize(991, 765)
        self.central_layout = QtWidgets.QWidget(BATT5)
        self.central_layout.setObjectName("central_layout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.central_layout)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.central_tabs = QtWidgets.QTabWidget(self.central_layout)
        self.central_tabs.setObjectName("central_tabs")
        self.analysis_tab = QtWidgets.QWidget()
        self.analysis_tab.setObjectName("analysis_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.analysis_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.changeViews_stack = QtWidgets.QStackedWidget(self.analysis_tab)
        self.changeViews_stack.setObjectName("changeViews_stack")
        self.current_view = QtWidgets.QWidget()
        self.current_view.setObjectName("current_view")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.current_view)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.project_sublayout = QtWidgets.QVBoxLayout()
        self.project_sublayout.setObjectName("project_sublayout")
        self.project_box = QtWidgets.QGroupBox(self.current_view)
        self.project_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.project_box.setAcceptDrops(False)
        self.project_box.setAutoFillBackground(False)
        self.project_box.setStyleSheet("")
        self.project_box.setFlat(False)
        self.project_box.setCheckable(False)
        self.project_box.setObjectName("project_box")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.project_box)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.projectSearch_lineEdit = QtWidgets.QLineEdit(self.project_box)
        self.projectSearch_lineEdit.setMaximumSize(QtCore.QSize(275, 16777215))
        self.projectSearch_lineEdit.setStyleSheet("color: rgb(136, 138, 133);")
        self.projectSearch_lineEdit.setObjectName("projectSearch_lineEdit")
        self.verticalLayout_7.addWidget(self.projectSearch_lineEdit)
        self.projectNavigator_tree = QtWidgets.QTreeWidget(self.project_box)
        self.projectNavigator_tree.setMinimumSize(QtCore.QSize(275, 0))
        self.projectNavigator_tree.setMaximumSize(QtCore.QSize(250, 16777215))
        self.projectNavigator_tree.setObjectName("projectNavigator_tree")
        self.verticalLayout_7.addWidget(self.projectNavigator_tree)
        self.projectProperties_text = QtWidgets.QTextBrowser(self.project_box)
        self.projectProperties_text.setMinimumSize(QtCore.QSize(275, 0))
        self.projectProperties_text.setMaximumSize(QtCore.QSize(250, 16777215))
        self.projectProperties_text.setObjectName("projectProperties_text")
        self.verticalLayout_7.addWidget(self.projectProperties_text)
        self.project_sublayout.addWidget(self.project_box)
        self.pluginSelection_box = QtWidgets.QGroupBox(self.current_view)
        self.pluginSelection_box.setMinimumSize(QtCore.QSize(250, 65))
        self.pluginSelection_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pluginSelection_box.setObjectName("pluginSelection_box")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pluginSelection_box)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pluginSelection_dropdown = QtWidgets.QComboBox(self.pluginSelection_box)
        self.pluginSelection_dropdown.setMinimumSize(QtCore.QSize(275, 0))
        self.pluginSelection_dropdown.setMaximumSize(QtCore.QSize(245, 16777215))
        self.pluginSelection_dropdown.setObjectName("pluginSelection_dropdown")
        self.verticalLayout_8.addWidget(self.pluginSelection_dropdown)
        self.project_sublayout.addWidget(self.pluginSelection_box)
        self.analyisisControls_box = QtWidgets.QGroupBox(self.current_view)
        self.analyisisControls_box.setMinimumSize(QtCore.QSize(300, 100))
        self.analyisisControls_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.analyisisControls_box.setObjectName("analyisisControls_box")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.analyisisControls_box)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.runStaticAnalysis_button = QtWidgets.QPushButton(self.analyisisControls_box)
        self.runStaticAnalysis_button.setObjectName("runStaticAnalysis_button")
        self.verticalLayout_9.addWidget(self.runStaticAnalysis_button)
        self.runDynamicAnalysis_button = QtWidgets.QPushButton(self.analyisisControls_box)
        self.runDynamicAnalysis_button.setStyleSheet("color: rgb(136, 138, 133);\n"
"background-color: rgb(186, 189, 182);")
        self.runDynamicAnalysis_button.setObjectName("runDynamicAnalysis_button")
        self.verticalLayout_9.addWidget(self.runDynamicAnalysis_button)
        self.project_sublayout.addWidget(self.analyisisControls_box, 0, QtCore.Qt.AlignLeft)
        self.pluginControls_box = QtWidgets.QGroupBox(self.current_view)
        self.pluginControls_box.setMinimumSize(QtCore.QSize(300, 70))
        self.pluginControls_box.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pluginControls_box.setObjectName("pluginControls_box")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pluginControls_box)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.generateScript_button = QtWidgets.QPushButton(self.pluginControls_box)
        self.generateScript_button.setObjectName("generateScript_button")
        self.verticalLayout_10.addWidget(self.generateScript_button)
        self.project_sublayout.addWidget(self.pluginControls_box)
        self.horizontalLayout_4.addLayout(self.project_sublayout)
        self.detailedAnalysis_sublayout = QtWidgets.QVBoxLayout()
        self.detailedAnalysis_sublayout.setObjectName("detailedAnalysis_sublayout")
        self.analysis_box = QtWidgets.QGroupBox(self.current_view)
        self.analysis_box.setObjectName("analysis_box")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.analysis_box)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.POI_tableWidget = QtWidgets.QTableView(self.analysis_box)
        self.POI_tableWidget.setObjectName("POI_tableWidget")
        self.verticalLayout_16.addWidget(self.POI_tableWidget)
        self.detailedAnalysis_sublayout.addWidget(self.analysis_box)
        self.radareConsole_box = QtWidgets.QGroupBox(self.current_view)
        self.radareConsole_box.setMinimumSize(QtCore.QSize(300, 225))
        self.radareConsole_box.setMaximumSize(QtCore.QSize(16777215, 218))
        self.radareConsole_box.setObjectName("radareConsole_box")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.radareConsole_box)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.radareConsoleOut_text = QtWidgets.QTextBrowser(self.radareConsole_box)
        self.radareConsoleOut_text.setObjectName("radareConsoleOut_text")
        self.verticalLayout_17.addWidget(self.radareConsoleOut_text)
        self.radareConsoleIn_lineEdit = QtWidgets.QLineEdit(self.radareConsole_box)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.radareConsoleIn_lineEdit.setPalette(palette)
        self.radareConsoleIn_lineEdit.setStyleSheet("color: rgb(136, 138, 133);")
        self.radareConsoleIn_lineEdit.setObjectName("radareConsoleIn_lineEdit")
        self.verticalLayout_17.addWidget(self.radareConsoleIn_lineEdit)
        self.detailedAnalysis_sublayout.addWidget(self.radareConsole_box)
        self.horizontalLayout_4.addLayout(self.detailedAnalysis_sublayout)
        self.commentAndPoi_sublayout = QtWidgets.QVBoxLayout()
        self.commentAndPoi_sublayout.setObjectName("commentAndPoi_sublayout")
        self.comment_box = QtWidgets.QGroupBox(self.current_view)
        self.comment_box.setMaximumSize(QtCore.QSize(300, 150))
        self.comment_box.setObjectName("comment_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.comment_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comment_text = QtWidgets.QTextEdit(self.comment_box)
        self.comment_text.setMinimumSize(QtCore.QSize(0, 0))
        self.comment_text.setMaximumSize(QtCore.QSize(16777215, 75))
        self.comment_text.setObjectName("comment_text")
        self.verticalLayout_2.addWidget(self.comment_text)
        self.commentButton_layout = QtWidgets.QGridLayout()
        self.commentButton_layout.setObjectName("commentButton_layout")
        self.commentSave_button = QtWidgets.QPushButton(self.comment_box)
        self.commentSave_button.setObjectName("commentSave_button")
        self.commentButton_layout.addWidget(self.commentSave_button, 0, 0, 1, 1)
        self.commentClear_button = QtWidgets.QPushButton(self.comment_box)
        self.commentClear_button.setObjectName("commentClear_button")
        self.commentButton_layout.addWidget(self.commentClear_button, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.commentButton_layout)
        self.commentAndPoi_sublayout.addWidget(self.comment_box)
        self.poi_box = QtWidgets.QGroupBox(self.current_view)
        self.poi_box.setMinimumSize(QtCore.QSize(0, 50))
        self.poi_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.poi_box.setObjectName("poi_box")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.poi_box)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.poi_layout = QtWidgets.QGridLayout()
        self.poi_layout.setObjectName("poi_layout")
        self.poiType_label = QtWidgets.QLabel(self.poi_box)
        self.poiType_label.setObjectName("poiType_label")
        self.poi_layout.addWidget(self.poiType_label, 0, 0, 1, 1)
        self.poiType_dropdown = QtWidgets.QComboBox(self.poi_box)
        self.poiType_dropdown.setObjectName("poiType_dropdown")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poi_layout.addWidget(self.poiType_dropdown, 0, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.poi_layout)
        self.poiSearch_lineEdit = QtWidgets.QLineEdit(self.poi_box)
        self.poiSearch_lineEdit.setStyleSheet("color: rgb(136, 138, 133);")
        self.poiSearch_lineEdit.setObjectName("poiSearch_lineEdit")
        self.verticalLayout_11.addWidget(self.poiSearch_lineEdit)
        self.poi_list = QtWidgets.QListWidget(self.poi_box)
        self.poi_list.setMinimumSize(QtCore.QSize(275, 0))
        self.poi_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.poi_list.setObjectName("poi_list")
        self.verticalLayout_11.addWidget(self.poi_list)
        self.commentAndPoi_sublayout.addWidget(self.poi_box)
        self.viewCurrent_box = QtWidgets.QGroupBox(self.current_view)
        self.viewCurrent_box.setObjectName("viewCurrent_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.viewCurrent_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.switchToHistory_button = QtWidgets.QPushButton(self.viewCurrent_box)
        self.switchToHistory_button.setObjectName("switchToHistory_button")
        self.verticalLayout_3.addWidget(self.switchToHistory_button)
        self.commentAndPoi_sublayout.addWidget(self.viewCurrent_box)
        self.horizontalLayout_4.addLayout(self.commentAndPoi_sublayout)
        self.changeViews_stack.addWidget(self.current_view)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.project_sublayout_h = QtWidgets.QVBoxLayout()
        self.project_sublayout_h.setObjectName("project_sublayout_h")
        self.project_box_h = QtWidgets.QGroupBox(self.page_4)
        self.project_box_h.setMaximumSize(QtCore.QSize(300, 350))
        self.project_box_h.setAcceptDrops(False)
        self.project_box_h.setAutoFillBackground(False)
        self.project_box_h.setStyleSheet("")
        self.project_box_h.setFlat(False)
        self.project_box_h.setCheckable(False)
        self.project_box_h.setObjectName("project_box_h")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.project_box_h)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.projectProperties_text_h = QtWidgets.QTextBrowser(self.project_box_h)
        self.projectProperties_text_h.setMinimumSize(QtCore.QSize(275, 0))
        self.projectProperties_text_h.setMaximumSize(QtCore.QSize(250, 300))
        self.projectProperties_text_h.setObjectName("projectProperties_text_h")
        self.verticalLayout_22.addWidget(self.projectProperties_text_h)
        self.project_sublayout_h.addWidget(self.project_box_h)
        self.daRuns_box = QtWidgets.QGroupBox(self.page_4)
        self.daRuns_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.daRuns_box.setObjectName("daRuns_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.daRuns_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.daRuns_list = QtWidgets.QListWidget(self.daRuns_box)
        self.daRuns_list.setObjectName("daRuns_list")
        self.verticalLayout_6.addWidget(self.daRuns_list)
        self.project_sublayout_h.addWidget(self.daRuns_box)
        self.horizontalLayout.addLayout(self.project_sublayout_h)
        self.detailedAnalysis_sublayout_2 = QtWidgets.QVBoxLayout()
        self.detailedAnalysis_sublayout_2.setObjectName("detailedAnalysis_sublayout_2")
        self.daRunDetails_box = QtWidgets.QGroupBox(self.page_4)
        self.daRunDetails_box.setObjectName("daRunDetails_box")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.daRunDetails_box)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.daRunDetails_table = QtWidgets.QTableWidget(self.daRunDetails_box)
        self.daRunDetails_table.setObjectName("daRunDetails_table")
        self.daRunDetails_table.setColumnCount(0)
        self.daRunDetails_table.setRowCount(0)
        self.verticalLayout_20.addWidget(self.daRunDetails_table)
        self.detailedAnalysis_sublayout_2.addWidget(self.daRunDetails_box)
        self.horizontalLayout.addLayout(self.detailedAnalysis_sublayout_2)
        self.commentAndPoi_sublayout_2 = QtWidgets.QVBoxLayout()
        self.commentAndPoi_sublayout_2.setObjectName("commentAndPoi_sublayout_2")
        self.comment_box_2 = QtWidgets.QGroupBox(self.page_4)
        self.comment_box_2.setMaximumSize(QtCore.QSize(300, 150))
        self.comment_box_2.setObjectName("comment_box_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.comment_box_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comment_text_2 = QtWidgets.QTextEdit(self.comment_box_2)
        self.comment_text_2.setMinimumSize(QtCore.QSize(0, 0))
        self.comment_text_2.setMaximumSize(QtCore.QSize(16777215, 75))
        self.comment_text_2.setObjectName("comment_text_2")
        self.verticalLayout_4.addWidget(self.comment_text_2)
        self.commentButton_layout_2 = QtWidgets.QGridLayout()
        self.commentButton_layout_2.setObjectName("commentButton_layout_2")
        self.commentSave_button_2 = QtWidgets.QPushButton(self.comment_box_2)
        self.commentSave_button_2.setObjectName("commentSave_button_2")
        self.commentButton_layout_2.addWidget(self.commentSave_button_2, 0, 0, 1, 1)
        self.commentClear_button_2 = QtWidgets.QPushButton(self.comment_box_2)
        self.commentClear_button_2.setObjectName("commentClear_button_2")
        self.commentButton_layout_2.addWidget(self.commentClear_button_2, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.commentButton_layout_2)
        self.commentAndPoi_sublayout_2.addWidget(self.comment_box_2)
        self.poi_box_2 = QtWidgets.QGroupBox(self.page_4)
        self.poi_box_2.setMinimumSize(QtCore.QSize(0, 50))
        self.poi_box_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.poi_box_2.setObjectName("poi_box_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.poi_box_2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.poi_layout_2 = QtWidgets.QGridLayout()
        self.poi_layout_2.setObjectName("poi_layout_2")
        self.poiType_dropdown_2 = QtWidgets.QComboBox(self.poi_box_2)
        self.poiType_dropdown_2.setObjectName("poiType_dropdown_2")
        self.poiType_dropdown_2.addItem("")
        self.poiType_dropdown_2.addItem("")
        self.poiType_dropdown_2.addItem("")
        self.poiType_dropdown_2.addItem("")
        self.poiType_dropdown_2.addItem("")
        self.poiType_dropdown_2.addItem("")
        self.poiType_dropdown_2.addItem("")
        self.poi_layout_2.addWidget(self.poiType_dropdown_2, 0, 1, 1, 1)
        self.poiType_label_2 = QtWidgets.QLabel(self.poi_box_2)
        self.poiType_label_2.setObjectName("poiType_label_2")
        self.poi_layout_2.addWidget(self.poiType_label_2, 0, 0, 1, 1)
        self.verticalLayout_19.addLayout(self.poi_layout_2)
        self.poiSearch_lineEdit_2 = QtWidgets.QLineEdit(self.poi_box_2)
        self.poiSearch_lineEdit_2.setStyleSheet("color: rgb(136, 138, 133);")
        self.poiSearch_lineEdit_2.setObjectName("poiSearch_lineEdit_2")
        self.verticalLayout_19.addWidget(self.poiSearch_lineEdit_2)
        self.poi_list_2 = QtWidgets.QListWidget(self.poi_box_2)
        self.poi_list_2.setMinimumSize(QtCore.QSize(275, 0))
        self.poi_list_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.poi_list_2.setObjectName("poi_list_2")
        self.verticalLayout_19.addWidget(self.poi_list_2)
        self.commentAndPoi_sublayout_2.addWidget(self.poi_box_2)
        self.switchToCurrent_box = QtWidgets.QGroupBox(self.page_4)
        self.switchToCurrent_box.setObjectName("switchToCurrent_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.switchToCurrent_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.switchToCurrent_button = QtWidgets.QPushButton(self.switchToCurrent_box)
        self.switchToCurrent_button.setObjectName("switchToCurrent_button")
        self.verticalLayout_5.addWidget(self.switchToCurrent_button)
        self.commentAndPoi_sublayout_2.addWidget(self.switchToCurrent_box)
        self.horizontalLayout.addLayout(self.commentAndPoi_sublayout_2)
        self.changeViews_stack.addWidget(self.page_4)
        self.horizontalLayout_2.addWidget(self.changeViews_stack)
        self.central_tabs.addTab(self.analysis_tab, "")
        self.management_tab = QtWidgets.QWidget()
        self.management_tab.setObjectName("management_tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.management_tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.management_layout = QtWidgets.QVBoxLayout()
        self.management_layout.setObjectName("management_layout")
        self.pluginManagement_box = QtWidgets.QGroupBox(self.management_tab)
        self.pluginManagement_box.setMinimumSize(QtCore.QSize(200, 0))
        self.pluginManagement_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pluginManagement_box.setStyleSheet("")
        self.pluginManagement_box.setObjectName("pluginManagement_box")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pluginManagement_box)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pluginManagementSearch_lineEdit = QtWidgets.QLineEdit(self.pluginManagement_box)
        self.pluginManagementSearch_lineEdit.setStyleSheet("color: rgb(136, 138, 133);")
        self.pluginManagementSearch_lineEdit.setObjectName("pluginManagementSearch_lineEdit")
        self.verticalLayout_12.addWidget(self.pluginManagementSearch_lineEdit)
        self.pluginManagement_list = QtWidgets.QListWidget(self.pluginManagement_box)
        self.pluginManagement_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pluginManagement_list.setObjectName("pluginManagement_list")
        self.verticalLayout_12.addWidget(self.pluginManagement_list)
        self.pluginManagementNew_button = QtWidgets.QPushButton(self.pluginManagement_box)
        self.pluginManagementNew_button.setObjectName("pluginManagementNew_button")
        self.verticalLayout_12.addWidget(self.pluginManagementNew_button)
        self.management_layout.addWidget(self.pluginManagement_box, 0, QtCore.Qt.AlignLeft)
        self.poiManagement_box = QtWidgets.QGroupBox(self.management_tab)
        self.poiManagement_box.setMinimumSize(QtCore.QSize(200, 0))
        self.poiManagement_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.poiManagement_box.setObjectName("poiManagement_box")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.poiManagement_box)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.poiManagementSeach_lineEdit = QtWidgets.QLineEdit(self.poiManagement_box)
        self.poiManagementSeach_lineEdit.setStyleSheet("color: rgb(136, 138, 133);")
        self.poiManagementSeach_lineEdit.setObjectName("poiManagementSeach_lineEdit")
        self.verticalLayout_14.addWidget(self.poiManagementSeach_lineEdit)
        self.poiManagement_list = QtWidgets.QListWidget(self.poiManagement_box)
        self.poiManagement_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.poiManagement_list.setObjectName("poiManagement_list")
        self.verticalLayout_14.addWidget(self.poiManagement_list)
        self.poiManagementNew_button = QtWidgets.QPushButton(self.poiManagement_box)
        self.poiManagementNew_button.setObjectName("poiManagementNew_button")
        self.verticalLayout_14.addWidget(self.poiManagementNew_button)
        self.management_layout.addWidget(self.poiManagement_box, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addLayout(self.management_layout)
        self.detailed_layout = QtWidgets.QVBoxLayout()
        self.detailed_layout.setObjectName("detailed_layout")
        self.dpm_box = QtWidgets.QGroupBox(self.management_tab)
        self.dpm_box.setObjectName("dpm_box")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.dpm_box)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.dpmCreate_label = QtWidgets.QLabel(self.dpm_box)
        self.dpmCreate_label.setMinimumSize(QtCore.QSize(350, 0))
        self.dpmCreate_label.setMaximumSize(QtCore.QSize(93, 16777215))
        self.dpmCreate_label.setObjectName("dpmCreate_label")
        self.horizontalLayout_5.addWidget(self.dpmCreate_label)
        self.dpmCreate_dropdown = QtWidgets.QComboBox(self.dpm_box)
        self.dpmCreate_dropdown.setObjectName("dpmCreate_dropdown")
        self.dpmCreate_dropdown.addItem("")
        self.dpmCreate_dropdown.addItem("")
        self.horizontalLayout_5.addWidget(self.dpmCreate_dropdown)
        self.verticalLayout_15.addLayout(self.horizontalLayout_5)
        self.createPlugin_stack = QtWidgets.QStackedWidget(self.dpm_box)
        self.createPlugin_stack.setObjectName("createPlugin_stack")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dpmPluginStructure_lineEdit = QtWidgets.QLineEdit(self.page)
        self.dpmPluginStructure_lineEdit.setObjectName("dpmPluginStructure_lineEdit")
        self.gridLayout_2.addWidget(self.dpmPluginStructure_lineEdit, 0, 1, 1, 1)
        self.dpmPluginStructure_label = QtWidgets.QLabel(self.page)
        self.dpmPluginStructure_label.setMinimumSize(QtCore.QSize(115, 0))
        self.dpmPluginStructure_label.setMaximumSize(QtCore.QSize(115, 16777215))
        self.dpmPluginStructure_label.setObjectName("dpmPluginStructure_label")
        self.gridLayout_2.addWidget(self.dpmPluginStructure_label, 0, 0, 1, 1)
        self.dpmPluginStructure_button = QtWidgets.QPushButton(self.page)
        self.dpmPluginStructure_button.setObjectName("dpmPluginStructure_button")
        self.gridLayout_2.addWidget(self.dpmPluginStructure_button, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.createPlugin_stack.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.dpmManualPlugin_layout = QtWidgets.QHBoxLayout()
        self.dpmManualPlugin_layout.setObjectName("dpmManualPlugin_layout")
        self.dpmPluginName_label = QtWidgets.QLabel(self.page_2)
        self.dpmPluginName_label.setMinimumSize(QtCore.QSize(140, 0))
        self.dpmPluginName_label.setObjectName("dpmPluginName_label")
        self.dpmManualPlugin_layout.addWidget(self.dpmPluginName_label)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dpmManualPlugin_layout.addWidget(self.lineEdit_2)
        self.verticalLayout_24.addLayout(self.dpmManualPlugin_layout)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setMinimumSize(QtCore.QSize(140, 0))
        self.label_4.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_9.addWidget(self.lineEdit_4)
        self.verticalLayout_24.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setMinimumSize(QtCore.QSize(140, 0))
        self.label_5.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_8.addWidget(self.lineEdit_3)
        self.verticalLayout_24.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setMinimumSize(QtCore.QSize(140, 0))
        self.label_6.setMaximumSize(QtCore.QSize(140, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_10.addWidget(self.lineEdit_5)
        self.verticalLayout_24.addLayout(self.horizontalLayout_10)
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_24.addWidget(self.label_8)
        self.createPlugin_stack.addWidget(self.page_2)
        self.verticalLayout_15.addWidget(self.createPlugin_stack)
        self.dpoim_lowGrid_2 = QtWidgets.QGridLayout()
        self.dpoim_lowGrid_2.setObjectName("dpoim_lowGrid_2")
        self.dpoimDelete_button_2 = QtWidgets.QPushButton(self.dpm_box)
        self.dpoimDelete_button_2.setObjectName("dpoimDelete_button_2")
        self.dpoim_lowGrid_2.addWidget(self.dpoimDelete_button_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dpoim_lowGrid_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.dpoimSave_button_2 = QtWidgets.QPushButton(self.dpm_box)
        self.dpoimSave_button_2.setObjectName("dpoimSave_button_2")
        self.dpoim_lowGrid_2.addWidget(self.dpoimSave_button_2, 0, 2, 1, 1)
        self.verticalLayout_15.addLayout(self.dpoim_lowGrid_2)
        self.detailed_layout.addWidget(self.dpm_box)
        self.dpoim_box = QtWidgets.QGroupBox(self.management_tab)
        self.dpoim_box.setObjectName("dpoim_box")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.dpoim_box)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.dpoim_topGrid = QtWidgets.QGridLayout()
        self.dpoim_topGrid.setObjectName("dpoim_topGrid")
        self.dpoimPoiType_dropdown = QtWidgets.QComboBox(self.dpoim_box)
        self.dpoimPoiType_dropdown.setObjectName("dpoimPoiType_dropdown")
        self.dpoimPoiType_dropdown.addItem("")
        self.dpoimPoiType_dropdown.addItem("")
        self.dpoimPoiType_dropdown.addItem("")
        self.dpoimPoiType_dropdown.addItem("")
        self.dpoimPoiType_dropdown.addItem("")
        self.dpoimPoiType_dropdown.addItem("")
        self.dpoimPoiType_dropdown.addItem("")
        self.dpoim_topGrid.addWidget(self.dpoimPoiType_dropdown, 2, 1, 1, 1)
        self.dpoimPlugin_dropdown = QtWidgets.QComboBox(self.dpoim_box)
        self.dpoimPlugin_dropdown.setObjectName("dpoimPlugin_dropdown")
        self.dpoim_topGrid.addWidget(self.dpoimPlugin_dropdown, 1, 1, 1, 1)
        self.dpoimPlugin_label = QtWidgets.QLabel(self.dpoim_box)
        self.dpoimPlugin_label.setObjectName("dpoimPlugin_label")
        self.dpoim_topGrid.addWidget(self.dpoimPlugin_label, 1, 0, 1, 1)
        self.dpoimPoiType_label = QtWidgets.QLabel(self.dpoim_box)
        self.dpoimPoiType_label.setObjectName("dpoimPoiType_label")
        self.dpoim_topGrid.addWidget(self.dpoimPoiType_label, 2, 0, 1, 1)
        self.verticalLayout_18.addLayout(self.dpoim_topGrid)
        self.addPOI_stack = QtWidgets.QStackedWidget(self.dpoim_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addPOI_stack.sizePolicy().hasHeightForWidth())
        self.addPOI_stack.setSizePolicy(sizePolicy)
        self.addPOI_stack.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.addPOI_stack.setObjectName("addPOI_stack")
        self.fromPredef_page = QtWidgets.QWidget()
        self.fromPredef_page.setObjectName("fromPredef_page")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.fromPredef_page)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dpoimPredefined_lineEdit = QtWidgets.QLineEdit(self.fromPredef_page)
        self.dpoimPredefined_lineEdit.setObjectName("dpoimPredefined_lineEdit")
        self.gridLayout.addWidget(self.dpoimPredefined_lineEdit, 0, 1, 1, 1)
        self.dpoimPredefined_label = QtWidgets.QLabel(self.fromPredef_page)
        self.dpoimPredefined_label.setMinimumSize(QtCore.QSize(115, 0))
        self.dpoimPredefined_label.setObjectName("dpoimPredefined_label")
        self.gridLayout.addWidget(self.dpoimPredefined_label, 0, 0, 1, 1)
        self.dpoimPredefined_button = QtWidgets.QPushButton(self.fromPredef_page)
        self.dpoimPredefined_button.setObjectName("dpoimPredefined_button")
        self.gridLayout.addWidget(self.dpoimPredefined_button, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.verticalLayout_21.addLayout(self.gridLayout)
        self.addPOI_stack.addWidget(self.fromPredef_page)
        self.function_page = QtWidgets.QWidget()
        self.function_page.setObjectName("function_page")
        self.formLayout_3 = QtWidgets.QFormLayout(self.function_page)
        self.formLayout_3.setObjectName("formLayout_3")
        self.funcName_label = QtWidgets.QLabel(self.function_page)
        self.funcName_label.setObjectName("funcName_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.funcName_label)
        self.funcName_lineEdit = QtWidgets.QLineEdit(self.function_page)
        self.funcName_lineEdit.setObjectName("funcName_lineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.funcName_lineEdit)
        self.funcNumParam_label = QtWidgets.QLabel(self.function_page)
        self.funcNumParam_label.setObjectName("funcNumParam_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.funcNumParam_label)
        self.funcRetType_label = QtWidgets.QLabel(self.function_page)
        self.funcRetType_label.setObjectName("funcRetType_label")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.funcRetType_label)
        self.funcRetType_lineEdit = QtWidgets.QLineEdit(self.function_page)
        self.funcRetType_lineEdit.setObjectName("funcRetType_lineEdit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.funcRetType_lineEdit)
        self.funcRetVal_label = QtWidgets.QLabel(self.function_page)
        self.funcRetVal_label.setObjectName("funcRetVal_label")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.funcRetVal_label)
        self.funcRetCal_lineEdit = QtWidgets.QLineEdit(self.function_page)
        self.funcRetCal_lineEdit.setObjectName("funcRetCal_lineEdit")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.funcRetCal_lineEdit)
        self.funcCallFrom_label = QtWidgets.QLabel(self.function_page)
        self.funcCallFrom_label.setObjectName("funcCallFrom_label")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.funcCallFrom_label)
        self.funcCallFrom_lineEdit = QtWidgets.QLineEdit(self.function_page)
        self.funcCallFrom_lineEdit.setObjectName("funcCallFrom_lineEdit")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.funcCallFrom_lineEdit)
        self.funcDestAddress_label = QtWidgets.QLabel(self.function_page)
        self.funcDestAddress_label.setObjectName("funcDestAddress_label")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.funcDestAddress_label)
        self.funcDestAddress_lineEdit = QtWidgets.QLineEdit(self.function_page)
        self.funcDestAddress_lineEdit.setObjectName("funcDestAddress_lineEdit")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.funcDestAddress_lineEdit)
        self.funcNumParam_lineEdit = QtWidgets.QLineEdit(self.function_page)
        self.funcNumParam_lineEdit.setObjectName("funcNumParam_lineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.funcNumParam_lineEdit)
        self.funcParamDetails_label = QtWidgets.QLabel(self.function_page)
        self.funcParamDetails_label.setObjectName("funcParamDetails_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.funcParamDetails_label)
        self.funcParamDetails_button = QtWidgets.QPushButton(self.function_page)
        self.funcParamDetails_button.setObjectName("funcParamDetails_button")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.funcParamDetails_button)
        self.addPOI_stack.addWidget(self.function_page)
        self.string_page = QtWidgets.QWidget()
        self.string_page.setObjectName("string_page")
        self.formLayout_4 = QtWidgets.QFormLayout(self.string_page)
        self.formLayout_4.setObjectName("formLayout_4")
        self.strName_label = QtWidgets.QLabel(self.string_page)
        self.strName_label.setObjectName("strName_label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.strName_label)
        self.strType_label = QtWidgets.QLabel(self.string_page)
        self.strType_label.setObjectName("strType_label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.strType_label)
        self.strSize_label = QtWidgets.QLabel(self.string_page)
        self.strSize_label.setObjectName("strSize_label")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.strSize_label)
        self.strCallFrom_label = QtWidgets.QLabel(self.string_page)
        self.strCallFrom_label.setObjectName("strCallFrom_label")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.strCallFrom_label)
        self.strDest_label = QtWidgets.QLabel(self.string_page)
        self.strDest_label.setObjectName("strDest_label")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.strDest_label)
        self.strSection_label = QtWidgets.QLabel(self.string_page)
        self.strSection_label.setObjectName("strSection_label")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.strSection_label)
        self.strName_lineEdit = QtWidgets.QLineEdit(self.string_page)
        self.strName_lineEdit.setObjectName("strName_lineEdit")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.strName_lineEdit)
        self.strType_lineEdit = QtWidgets.QLineEdit(self.string_page)
        self.strType_lineEdit.setObjectName("strType_lineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.strType_lineEdit)
        self.strSize_lineEdit = QtWidgets.QLineEdit(self.string_page)
        self.strSize_lineEdit.setObjectName("strSize_lineEdit")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.strSize_lineEdit)
        self.strCallFrom_lineEdit = QtWidgets.QLineEdit(self.string_page)
        self.strCallFrom_lineEdit.setObjectName("strCallFrom_lineEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.strCallFrom_lineEdit)
        self.strDest_lineEdit = QtWidgets.QLineEdit(self.string_page)
        self.strDest_lineEdit.setObjectName("strDest_lineEdit")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.strDest_lineEdit)
        self.strSection_linEdit = QtWidgets.QLineEdit(self.string_page)
        self.strSection_linEdit.setObjectName("strSection_linEdit")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.strSection_linEdit)
        self.addPOI_stack.addWidget(self.string_page)
        self.variable_page = QtWidgets.QWidget()
        self.variable_page.setObjectName("variable_page")
        self.formLayout_2 = QtWidgets.QFormLayout(self.variable_page)
        self.formLayout_2.setObjectName("formLayout_2")
        self.varName_label = QtWidgets.QLabel(self.variable_page)
        self.varName_label.setObjectName("varName_label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.varName_label)
        self.varName_lineEdit = QtWidgets.QLineEdit(self.variable_page)
        self.varName_lineEdit.setObjectName("varName_lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.varName_lineEdit)
        self.varType_label = QtWidgets.QLabel(self.variable_page)
        self.varType_label.setObjectName("varType_label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.varType_label)
        self.varValue_label = QtWidgets.QLabel(self.variable_page)
        self.varValue_label.setObjectName("varValue_label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.varValue_label)
        self.varSize_label = QtWidgets.QLabel(self.variable_page)
        self.varSize_label.setObjectName("varSize_label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.varSize_label)
        self.varType_lineEdit = QtWidgets.QLineEdit(self.variable_page)
        self.varType_lineEdit.setObjectName("varType_lineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.varType_lineEdit)
        self.varValue_lineEdit = QtWidgets.QLineEdit(self.variable_page)
        self.varValue_lineEdit.setObjectName("varValue_lineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.varValue_lineEdit)
        self.varSize_lineEdit = QtWidgets.QLineEdit(self.variable_page)
        self.varSize_lineEdit.setObjectName("varSize_lineEdit")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.varSize_lineEdit)
        self.addPOI_stack.addWidget(self.variable_page)
        self.DLL_page = QtWidgets.QWidget()
        self.DLL_page.setObjectName("DLL_page")
        self.formLayout_5 = QtWidgets.QFormLayout(self.DLL_page)
        self.formLayout_5.setObjectName("formLayout_5")
        self.dllName_label = QtWidgets.QLabel(self.DLL_page)
        self.dllName_label.setObjectName("dllName_label")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dllName_label)
        self.dllName_lineEdit = QtWidgets.QLineEdit(self.DLL_page)
        self.dllName_lineEdit.setObjectName("dllName_lineEdit")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dllName_lineEdit)
        self.addPOI_stack.addWidget(self.DLL_page)
        self.pckProto_page = QtWidgets.QWidget()
        self.pckProto_page.setObjectName("pckProto_page")
        self.formLayout_6 = QtWidgets.QFormLayout(self.pckProto_page)
        self.formLayout_6.setObjectName("formLayout_6")
        self.protoName_label = QtWidgets.QLabel(self.pckProto_page)
        self.protoName_label.setObjectName("protoName_label")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.protoName_label)
        self.protoFieldName_label = QtWidgets.QLabel(self.pckProto_page)
        self.protoFieldName_label.setObjectName("protoFieldName_label")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.protoFieldName_label)
        self.protoFieldType_label = QtWidgets.QLabel(self.pckProto_page)
        self.protoFieldType_label.setObjectName("protoFieldType_label")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.protoFieldType_label)
        self.protoName_lineEdit = QtWidgets.QLineEdit(self.pckProto_page)
        self.protoName_lineEdit.setObjectName("protoName_lineEdit")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.protoName_lineEdit)
        self.protoFieldName_lineEdit = QtWidgets.QLineEdit(self.pckProto_page)
        self.protoFieldName_lineEdit.setObjectName("protoFieldName_lineEdit")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.protoFieldName_lineEdit)
        self.protoFieldType_lineEdit = QtWidgets.QLineEdit(self.pckProto_page)
        self.protoFieldType_lineEdit.setObjectName("protoFieldType_lineEdit")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.protoFieldType_lineEdit)
        self.addPOI_stack.addWidget(self.pckProto_page)
        self.Struct_page = QtWidgets.QWidget()
        self.Struct_page.setObjectName("Struct_page")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.Struct_page)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.StructTBD_text = QtWidgets.QTextBrowser(self.Struct_page)
        self.StructTBD_text.setObjectName("StructTBD_text")
        self.verticalLayout_30.addWidget(self.StructTBD_text)
        self.addPOI_stack.addWidget(self.Struct_page)
        self.verticalLayout_18.addWidget(self.addPOI_stack)
        self.dpoim_lowGrid = QtWidgets.QGridLayout()
        self.dpoim_lowGrid.setObjectName("dpoim_lowGrid")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dpoim_lowGrid.addItem(spacerItem3, 0, 1, 1, 1)
        self.dpoimDelete_button = QtWidgets.QPushButton(self.dpoim_box)
        self.dpoimDelete_button.setObjectName("dpoimDelete_button")
        self.dpoim_lowGrid.addWidget(self.dpoimDelete_button, 0, 0, 1, 1)
        self.dpoimSave_button = QtWidgets.QPushButton(self.dpoim_box)
        self.dpoimSave_button.setObjectName("dpoimSave_button")
        self.dpoim_lowGrid.addWidget(self.dpoimSave_button, 0, 2, 1, 1)
        self.verticalLayout_18.addLayout(self.dpoim_lowGrid)
        self.detailed_layout.addWidget(self.dpoim_box)
        self.horizontalLayout_3.addLayout(self.detailed_layout)
        self.central_tabs.addTab(self.management_tab, "")
        self.verticalLayout_13.addWidget(self.central_tabs)
        BATT5.setCentralWidget(self.central_layout)
        self.menubar = QtWidgets.QMenuBar(BATT5)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 991, 26))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        BATT5.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BATT5)
        self.statusbar.setObjectName("statusbar")
        BATT5.setStatusBar(self.statusbar)
        self.actionNew_Project = QtWidgets.QAction(BATT5)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionSave = QtWidgets.QAction(BATT5)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(BATT5)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_Analysis = QtWidgets.QAction(BATT5)
        self.actionSave_Analysis.setObjectName("actionSave_Analysis")
        self.actionSave_as = QtWidgets.QAction(BATT5)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionDocumentation = QtWidgets.QAction(BATT5)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionSave_Analysis_2 = QtWidgets.QAction(BATT5)
        self.actionSave_Analysis_2.setObjectName("actionSave_Analysis_2")
        self.actionOpen_Project = QtWidgets.QAction(BATT5)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionExport_Project = QtWidgets.QAction(BATT5)
        self.actionExport_Project.setObjectName("actionExport_Project")
        self.file_menu.addAction(self.actionNew_Project)
        self.file_menu.addAction(self.actionOpen_Project)
        self.file_menu.addAction(self.actionExport_Project)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.actionSave_Analysis_2)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(BATT5)
        self.central_tabs.setCurrentIndex(0)
        self.changeViews_stack.setCurrentIndex(0)
        self.createPlugin_stack.setCurrentIndex(0)
        self.addPOI_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BATT5)

    def retranslateUi(self, BATT5):
        _translate = QtCore.QCoreApplication.translate
        BATT5.setWindowTitle(_translate("BATT5", "MainWindow"))
        self.project_box.setTitle(_translate("BATT5", "Projects"))
        self.projectSearch_lineEdit.setText(_translate("BATT5", "Search.."))
        self.projectNavigator_tree.headerItem().setText(0, _translate("BATT5", "Projects"))
        self.projectProperties_text.setHtml(_translate("BATT5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pluginSelection_box.setTitle(_translate("BATT5", "Plugin Selection"))
        self.analyisisControls_box.setTitle(_translate("BATT5", "Analysis Controls"))
        self.runStaticAnalysis_button.setText(_translate("BATT5", "Run Static Analysis"))
        self.runDynamicAnalysis_button.setText(_translate("BATT5", "Run Dynamic Analysis"))
        self.pluginControls_box.setTitle(_translate("BATT5", "Plugin Controls"))
        self.generateScript_button.setText(_translate("BATT5", "Generate Output Field"))
        self.analysis_box.setTitle(_translate("BATT5", "Analysis"))
        self.radareConsole_box.setTitle(_translate("BATT5", "Command Console"))
        self.radareConsoleIn_lineEdit.setText(_translate("BATT5", "BATT5$"))
        self.comment_box.setTitle(_translate("BATT5", "Comment View"))
        self.commentSave_button.setText(_translate("BATT5", "Save"))
        self.commentClear_button.setText(_translate("BATT5", "Clear"))
        self.poi_box.setTitle(_translate("BATT5", "Points of Interest"))
        self.poiType_label.setText(_translate("BATT5", "Type"))
        self.poiType_dropdown.setItemText(0, _translate("BATT5", "Extract All"))
        self.poiType_dropdown.setItemText(1, _translate("BATT5", "Function"))
        self.poiType_dropdown.setItemText(2, _translate("BATT5", "String"))
        self.poiType_dropdown.setItemText(3, _translate("BATT5", "Variable"))
        self.poiType_dropdown.setItemText(4, _translate("BATT5", "DLL"))
        self.poiType_dropdown.setItemText(5, _translate("BATT5", "Packet Protocol"))
        self.poiType_dropdown.setItemText(6, _translate("BATT5", "Struct"))
        self.poiSearch_lineEdit.setText(_translate("BATT5", "Search.."))
        self.viewCurrent_box.setTitle(_translate("BATT5", "Switch View"))
        self.switchToHistory_button.setText(_translate("BATT5", "Switch to History View"))
        self.project_box_h.setTitle(_translate("BATT5", "Properties"))
        self.projectProperties_text_h.setHtml(_translate("BATT5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.daRuns_box.setTitle(_translate("BATT5", "Dynamic Analysis Runs"))
        self.daRunDetails_box.setTitle(_translate("BATT5", "Dynamic Analysis Run Details"))
        self.comment_box_2.setTitle(_translate("BATT5", "Comment View"))
        self.commentSave_button_2.setText(_translate("BATT5", "Save"))
        self.commentClear_button_2.setText(_translate("BATT5", "Clear"))
        self.poi_box_2.setTitle(_translate("BATT5", "Points of Interest"))
        self.poiType_dropdown_2.setItemText(0, _translate("BATT5", "All"))
        self.poiType_dropdown_2.setItemText(1, _translate("BATT5", "Function"))
        self.poiType_dropdown_2.setItemText(2, _translate("BATT5", "String"))
        self.poiType_dropdown_2.setItemText(3, _translate("BATT5", "Variable"))
        self.poiType_dropdown_2.setItemText(4, _translate("BATT5", "DLL"))
        self.poiType_dropdown_2.setItemText(5, _translate("BATT5", "Packet Protocol"))
        self.poiType_dropdown_2.setItemText(6, _translate("BATT5", "Struct"))
        self.poiType_label_2.setText(_translate("BATT5", "Type"))
        self.poiSearch_lineEdit_2.setText(_translate("BATT5", "Search.."))
        self.switchToCurrent_box.setTitle(_translate("BATT5", "Switch View"))
        self.switchToCurrent_button.setText(_translate("BATT5", "Switch to Curent View"))
        self.central_tabs.setTabText(self.central_tabs.indexOf(self.analysis_tab), _translate("BATT5", "Analysis"))
        self.pluginManagement_box.setTitle(_translate("BATT5", "Plugin Management"))
        self.pluginManagementSearch_lineEdit.setText(_translate("BATT5", "Search.."))
        self.pluginManagementNew_button.setText(_translate("BATT5", "New"))
        self.poiManagement_box.setTitle(_translate("BATT5", "Points of Interest Management"))
        self.poiManagementSeach_lineEdit.setText(_translate("BATT5", "Search.."))
        self.poiManagementNew_button.setText(_translate("BATT5", "New"))
        self.dpm_box.setTitle(_translate("BATT5", "Detailed Plugin Management"))
        self.dpmCreate_label.setText(_translate("BATT5", "Plugin Creation"))
        self.dpmCreate_dropdown.setItemText(0, _translate("BATT5", "Pull From XML File"))
        self.dpmCreate_dropdown.setItemText(1, _translate("BATT5", "Manual Input"))
        self.dpmPluginStructure_label.setText(_translate("BATT5", "Plugin Structure"))
        self.dpmPluginStructure_button.setText(_translate("BATT5", "Browse"))
        self.dpmPluginName_label.setText(_translate("BATT5", "*Name"))
        self.label_4.setText(_translate("BATT5", "*Description"))
        self.label_5.setText(_translate("BATT5", "Output Function Name"))
        self.label_6.setText(_translate("BATT5", "Output Function Source"))
        self.label_8.setText(_translate("BATT5", "POI added through XML or section below"))
        self.dpoimDelete_button_2.setText(_translate("BATT5", "Delete"))
        self.dpoimSave_button_2.setText(_translate("BATT5", "Save"))
        self.dpoim_box.setTitle(_translate("BATT5", "Detailed Points of Interest Management"))
        self.dpoimPoiType_dropdown.setItemText(0, _translate("BATT5", "Pull From Predefined Dataset"))
        self.dpoimPoiType_dropdown.setItemText(1, _translate("BATT5", "Function"))
        self.dpoimPoiType_dropdown.setItemText(2, _translate("BATT5", "String"))
        self.dpoimPoiType_dropdown.setItemText(3, _translate("BATT5", "Variable"))
        self.dpoimPoiType_dropdown.setItemText(4, _translate("BATT5", "DLL"))
        self.dpoimPoiType_dropdown.setItemText(5, _translate("BATT5", "Packet Protocol"))
        self.dpoimPoiType_dropdown.setItemText(6, _translate("BATT5", "Struct"))
        self.dpoimPlugin_label.setText(_translate("BATT5", "Plugin"))
        self.dpoimPoiType_label.setText(_translate("BATT5", "Point of Interest Type"))
        self.dpoimPredefined_label.setText(_translate("BATT5", "Predefined Data Set"))
        self.dpoimPredefined_button.setText(_translate("BATT5", "Browse"))
        self.funcName_label.setText(_translate("BATT5", "*Name:"))
        self.funcNumParam_label.setText(_translate("BATT5", "Num. of Parameters:"))
        self.funcRetType_label.setText(_translate("BATT5", "Return Type:"))
        self.funcRetVal_label.setText(_translate("BATT5", "Return Value:"))
        self.funcCallFrom_label.setText(_translate("BATT5", "Call From Address:"))
        self.funcDestAddress_label.setText(_translate("BATT5", "Destination Address:"))
        self.funcParamDetails_label.setText(_translate("BATT5", "Parameter Details:"))
        self.funcParamDetails_button.setText(_translate("BATT5", "Edit Parameter Details"))
        self.strName_label.setText(_translate("BATT5", "*Name:"))
        self.strType_label.setText(_translate("BATT5", "Type:"))
        self.strSize_label.setText(_translate("BATT5", "Size:"))
        self.strCallFrom_label.setText(_translate("BATT5", "Call From Address:"))
        self.strDest_label.setText(_translate("BATT5", "Destination Address:"))
        self.strSection_label.setText(_translate("BATT5", "Section:"))
        self.varName_label.setText(_translate("BATT5", "*Name:"))
        self.varType_label.setText(_translate("BATT5", "Type:"))
        self.varValue_label.setText(_translate("BATT5", "Value:"))
        self.varSize_label.setText(_translate("BATT5", "Size:"))
        self.dllName_label.setText(_translate("BATT5", "*Name:"))
        self.protoName_label.setText(_translate("BATT5", "*Name:"))
        self.protoFieldName_label.setText(_translate("BATT5", "Field Name:"))
        self.protoFieldType_label.setText(_translate("BATT5", "Field Type:"))
        self.StructTBD_text.setHtml(_translate("BATT5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic; color:#4a4a4a;\">TBD (Structure not defined in SRS)</span></p></body></html>"))
        self.dpoimDelete_button.setText(_translate("BATT5", "Delete"))
        self.dpoimSave_button.setText(_translate("BATT5", "Save"))
        self.central_tabs.setTabText(self.central_tabs.indexOf(self.management_tab), _translate("BATT5", "Management"))
        self.file_menu.setTitle(_translate("BATT5", "File"))
        self.menuHelp.setTitle(_translate("BATT5", "Help"))
        self.actionNew_Project.setText(_translate("BATT5", "New Project"))
        self.actionSave.setText(_translate("BATT5", "Save"))
        self.actionOpen.setText(_translate("BATT5", "Open..."))
        self.actionSave_Analysis.setText(_translate("BATT5", "Save Analysis"))
        self.actionSave_as.setText(_translate("BATT5", "Save as..."))
        self.actionDocumentation.setText(_translate("BATT5", "Documentation"))
        self.actionSave_Analysis_2.setText(_translate("BATT5", "Save Analysis"))
        self.actionOpen_Project.setText(_translate("BATT5", "Open Project"))
        self.actionExport_Project.setText(_translate("BATT5", "Export Project"))

