# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BATT5_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BATT5(object):
    def setupUi(self, BATT5):
        BATT5.setObjectName("BATT5")
        BATT5.resize(1142, 894)
        self.central_layout = QtWidgets.QWidget(BATT5)
        self.central_layout.setObjectName("central_layout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.central_layout)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.central_tabs = QtWidgets.QTabWidget(self.central_layout)
        self.central_tabs.setObjectName("central_tabs")
        self.analysis_tab = QtWidgets.QWidget()
        self.analysis_tab.setObjectName("analysis_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.analysis_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.project_layout = QtWidgets.QHBoxLayout()
        self.project_layout.setObjectName("project_layout")
        self.project_sublayout = QtWidgets.QVBoxLayout()
        self.project_sublayout.setObjectName("project_sublayout")
        self.project_box = QtWidgets.QGroupBox(self.analysis_tab)
        self.project_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.project_box.setAcceptDrops(False)
        self.project_box.setAutoFillBackground(False)
        self.project_box.setStyleSheet("")
        self.project_box.setFlat(False)
        self.project_box.setCheckable(False)
        self.project_box.setObjectName("project_box")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.project_box)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.projectSearch_lineEdit = QtWidgets.QLineEdit(self.project_box)
        self.projectSearch_lineEdit.setMaximumSize(QtCore.QSize(275, 16777215))
        self.projectSearch_lineEdit.setStyleSheet("color: rgb(136, 138, 133);")
        self.projectSearch_lineEdit.setObjectName("projectSearch_lineEdit")
        self.verticalLayout_7.addWidget(self.projectSearch_lineEdit)
        self.projectNavigator_tree = QtWidgets.QTreeWidget(self.project_box)
        self.projectNavigator_tree.setMinimumSize(QtCore.QSize(275, 0))
        self.projectNavigator_tree.setMaximumSize(QtCore.QSize(250, 16777215))
        self.projectNavigator_tree.setObjectName("projectNavigator_tree")
        self.verticalLayout_7.addWidget(self.projectNavigator_tree)
        self.projectProperties_text = QtWidgets.QTextBrowser(self.project_box)
        self.projectProperties_text.setMinimumSize(QtCore.QSize(275, 0))
        self.projectProperties_text.setMaximumSize(QtCore.QSize(250, 16777215))
        self.projectProperties_text.setObjectName("projectProperties_text")
        self.verticalLayout_7.addWidget(self.projectProperties_text)
        self.project_sublayout.addWidget(self.project_box)
        self.pluginSelection_box = QtWidgets.QGroupBox(self.analysis_tab)
        self.pluginSelection_box.setMinimumSize(QtCore.QSize(250, 65))
        self.pluginSelection_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pluginSelection_box.setObjectName("pluginSelection_box")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pluginSelection_box)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pluginSelection_dropdown = QtWidgets.QComboBox(self.pluginSelection_box)
        self.pluginSelection_dropdown.setMinimumSize(QtCore.QSize(275, 0))
        self.pluginSelection_dropdown.setMaximumSize(QtCore.QSize(245, 16777215))
        self.pluginSelection_dropdown.setObjectName("pluginSelection_dropdown")
        self.pluginSelection_dropdown.addItem("")
        self.pluginSelection_dropdown.addItem("")
        self.pluginSelection_dropdown.addItem("")
        self.verticalLayout_8.addWidget(self.pluginSelection_dropdown)
        self.project_sublayout.addWidget(self.pluginSelection_box)
        self.analyisisControls_box = QtWidgets.QGroupBox(self.analysis_tab)
        self.analyisisControls_box.setMinimumSize(QtCore.QSize(300, 85))
        self.analyisisControls_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.analyisisControls_box.setObjectName("analyisisControls_box")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.analyisisControls_box)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.runStaticAnalysis_button = QtWidgets.QPushButton(self.analyisisControls_box)
        self.runStaticAnalysis_button.setObjectName("runStaticAnalysis_button")
        self.verticalLayout_9.addWidget(self.runStaticAnalysis_button)
        self.runDynamicAnalysis_button = QtWidgets.QPushButton(self.analyisisControls_box)
        self.runDynamicAnalysis_button.setStyleSheet("color: rgb(136, 138, 133);\n"
"background-color: rgb(186, 189, 182);")
        self.runDynamicAnalysis_button.setObjectName("runDynamicAnalysis_button")
        self.verticalLayout_9.addWidget(self.runDynamicAnalysis_button)
        self.project_sublayout.addWidget(self.analyisisControls_box, 0, QtCore.Qt.AlignLeft)
        self.pluginControls_box = QtWidgets.QGroupBox(self.analysis_tab)
        self.pluginControls_box.setMinimumSize(QtCore.QSize(300, 50))
        self.pluginControls_box.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pluginControls_box.setObjectName("pluginControls_box")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pluginControls_box)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.generateScript_button = QtWidgets.QPushButton(self.pluginControls_box)
        self.generateScript_button.setObjectName("generateScript_button")
        self.verticalLayout_10.addWidget(self.generateScript_button)
        self.project_sublayout.addWidget(self.pluginControls_box)
        self.project_layout.addLayout(self.project_sublayout)
        self.horizontalLayout_2.addLayout(self.project_layout)
        self.detailedAnalysis_layout = QtWidgets.QHBoxLayout()
        self.detailedAnalysis_layout.setObjectName("detailedAnalysis_layout")
        self.detailedAnalysis_sublayout = QtWidgets.QVBoxLayout()
        self.detailedAnalysis_sublayout.setObjectName("detailedAnalysis_sublayout")
        self.analysis_box = QtWidgets.QGroupBox(self.analysis_tab)
        self.analysis_box.setObjectName("analysis_box")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.analysis_box)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.analysis_text = QtWidgets.QListWidget(self.analysis_box)
        self.analysis_text.setObjectName("analysis_text")
        self.verticalLayout_16.addWidget(self.analysis_text)
        self.detailedAnalysis_sublayout.addWidget(self.analysis_box)
        self.radareConsole_box = QtWidgets.QGroupBox(self.analysis_tab)
        self.radareConsole_box.setMinimumSize(QtCore.QSize(300, 225))
        self.radareConsole_box.setMaximumSize(QtCore.QSize(16777215, 218))
        self.radareConsole_box.setObjectName("radareConsole_box")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.radareConsole_box)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.radareConsole_text = QtWidgets.QPlainTextEdit(self.radareConsole_box)
        self.radareConsole_text.setObjectName("radareConsole_text")
        self.verticalLayout_17.addWidget(self.radareConsole_text)
        self.detailedAnalysis_sublayout.addWidget(self.radareConsole_box)
        self.detailedAnalysis_layout.addLayout(self.detailedAnalysis_sublayout)
        self.horizontalLayout_2.addLayout(self.detailedAnalysis_layout)
        self.commentAndPoi_layout = QtWidgets.QHBoxLayout()
        self.commentAndPoi_layout.setObjectName("commentAndPoi_layout")
        self.commentAndPoi_sublayout = QtWidgets.QVBoxLayout()
        self.commentAndPoi_sublayout.setObjectName("commentAndPoi_sublayout")
        self.comment_box = QtWidgets.QGroupBox(self.analysis_tab)
        self.comment_box.setMaximumSize(QtCore.QSize(300, 300))
        self.comment_box.setObjectName("comment_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.comment_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comment_text = QtWidgets.QTextEdit(self.comment_box)
        self.comment_text.setMinimumSize(QtCore.QSize(0, 0))
        self.comment_text.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comment_text.setObjectName("comment_text")
        self.verticalLayout_2.addWidget(self.comment_text)
        self.commentButton_layout = QtWidgets.QGridLayout()
        self.commentButton_layout.setObjectName("commentButton_layout")
        self.commentSave_button = QtWidgets.QPushButton(self.comment_box)
        self.commentSave_button.setObjectName("commentSave_button")
        self.commentButton_layout.addWidget(self.commentSave_button, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.commentButton_layout.addItem(spacerItem, 0, 1, 1, 1)
        self.commentClear_button = QtWidgets.QPushButton(self.comment_box)
        self.commentClear_button.setObjectName("commentClear_button")
        self.commentButton_layout.addWidget(self.commentClear_button, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.commentButton_layout)
        self.commentAndPoi_sublayout.addWidget(self.comment_box)
        self.poi_box = QtWidgets.QGroupBox(self.analysis_tab)
        self.poi_box.setMinimumSize(QtCore.QSize(0, 50))
        self.poi_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.poi_box.setObjectName("poi_box")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.poi_box)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.poi_layout = QtWidgets.QGridLayout()
        self.poi_layout.setObjectName("poi_layout")
        self.poiType_label = QtWidgets.QLabel(self.poi_box)
        self.poiType_label.setObjectName("poiType_label")
        self.poi_layout.addWidget(self.poiType_label, 0, 0, 1, 1)
        self.poiType_dropdown = QtWidgets.QComboBox(self.poi_box)
        self.poiType_dropdown.setObjectName("poiType_dropdown")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poi_layout.addWidget(self.poiType_dropdown, 0, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.poi_layout)
        self.poiSearch_lineEdit = QtWidgets.QLineEdit(self.poi_box)
        self.poiSearch_lineEdit.setStyleSheet("color: rgb(136, 138, 133);")
        self.poiSearch_lineEdit.setObjectName("poiSearch_lineEdit")
        self.verticalLayout_11.addWidget(self.poiSearch_lineEdit)
        self.poi_list = QtWidgets.QListWidget(self.poi_box)
        self.poi_list.setMinimumSize(QtCore.QSize(275, 0))
        self.poi_list.setObjectName("poi_list")
        self.verticalLayout_11.addWidget(self.poi_list)
        self.commentAndPoi_sublayout.addWidget(self.poi_box)
        self.commentAndPoi_layout.addLayout(self.commentAndPoi_sublayout)
        self.horizontalLayout_2.addLayout(self.commentAndPoi_layout)
        self.central_tabs.addTab(self.analysis_tab, "")
        self.management_tab = QtWidgets.QWidget()
        self.management_tab.setObjectName("management_tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.management_tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.management_layout = QtWidgets.QVBoxLayout()
        self.management_layout.setObjectName("management_layout")
        self.pluginManagement_box = QtWidgets.QGroupBox(self.management_tab)
        self.pluginManagement_box.setMinimumSize(QtCore.QSize(200, 0))
        self.pluginManagement_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pluginManagement_box.setStyleSheet("")
        self.pluginManagement_box.setObjectName("pluginManagement_box")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pluginManagement_box)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pluginManagementSearch_lineEdit = QtWidgets.QLineEdit(self.pluginManagement_box)
        self.pluginManagementSearch_lineEdit.setStyleSheet("color: rgb(136, 138, 133);")
        self.pluginManagementSearch_lineEdit.setObjectName("pluginManagementSearch_lineEdit")
        self.verticalLayout_12.addWidget(self.pluginManagementSearch_lineEdit)
        self.pluginManagement_list = QtWidgets.QListWidget(self.pluginManagement_box)
        self.pluginManagement_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pluginManagement_list.setObjectName("pluginManagement_list")
        self.verticalLayout_12.addWidget(self.pluginManagement_list)
        self.pluginManagementNew_button = QtWidgets.QPushButton(self.pluginManagement_box)
        self.pluginManagementNew_button.setObjectName("pluginManagementNew_button")
        self.verticalLayout_12.addWidget(self.pluginManagementNew_button)
        self.management_layout.addWidget(self.pluginManagement_box, 0, QtCore.Qt.AlignLeft)
        self.poiManagement_box = QtWidgets.QGroupBox(self.management_tab)
        self.poiManagement_box.setMinimumSize(QtCore.QSize(200, 0))
        self.poiManagement_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.poiManagement_box.setObjectName("poiManagement_box")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.poiManagement_box)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.poiManagementSeach_lineEdit = QtWidgets.QLineEdit(self.poiManagement_box)
        self.poiManagementSeach_lineEdit.setStyleSheet("color: rgb(136, 138, 133);")
        self.poiManagementSeach_lineEdit.setObjectName("poiManagementSeach_lineEdit")
        self.verticalLayout_14.addWidget(self.poiManagementSeach_lineEdit)
        self.poiManagement_list = QtWidgets.QListWidget(self.poiManagement_box)
        self.poiManagement_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.poiManagement_list.setObjectName("poiManagement_list")
        self.verticalLayout_14.addWidget(self.poiManagement_list)
        self.poiManagementNew_button = QtWidgets.QPushButton(self.poiManagement_box)
        self.poiManagementNew_button.setObjectName("poiManagementNew_button")
        self.verticalLayout_14.addWidget(self.poiManagementNew_button)
        self.management_layout.addWidget(self.poiManagement_box, 0, QtCore.Qt.AlignLeft)
        self.horizontalLayout_3.addLayout(self.management_layout)
        self.detailed_layout = QtWidgets.QVBoxLayout()
        self.detailed_layout.setObjectName("detailed_layout")
        self.dpm_box = QtWidgets.QGroupBox(self.management_tab)
        self.dpm_box.setObjectName("dpm_box")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.dpm_box)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.dpm_layout = QtWidgets.QGridLayout()
        self.dpm_layout.setObjectName("dpm_layout")
        self.dpm_comboBox = QtWidgets.QComboBox(self.dpm_box)
        self.dpm_comboBox.setMaximumSize(QtCore.QSize(200, 200))
        self.dpm_comboBox.setObjectName("dpm_comboBox")
        self.dpm_layout.addWidget(self.dpm_comboBox, 5, 1, 1, 1)
        self.dpmPluginPredefined_lineEdit = QtWidgets.QLineEdit(self.dpm_box)
        self.dpmPluginPredefined_lineEdit.setObjectName("dpmPluginPredefined_lineEdit")
        self.dpm_layout.addWidget(self.dpmPluginPredefined_lineEdit, 2, 1, 1, 1)
        self.dpmPluginStructure_lineEdit = QtWidgets.QLineEdit(self.dpm_box)
        self.dpmPluginStructure_lineEdit.setObjectName("dpmPluginStructure_lineEdit")
        self.dpm_layout.addWidget(self.dpmPluginStructure_lineEdit, 1, 1, 1, 1)
        self.dpmDelete_button = QtWidgets.QPushButton(self.dpm_box)
        self.dpmDelete_button.setObjectName("dpmDelete_button")
        self.dpm_layout.addWidget(self.dpmDelete_button, 8, 0, 1, 1)
        self.dpmPluginDescription_label = QtWidgets.QLabel(self.dpm_box)
        self.dpmPluginDescription_label.setObjectName("dpmPluginDescription_label")
        self.dpm_layout.addWidget(self.dpmPluginDescription_label, 4, 0, 1, 1)
        self.dpmPluginName_lineEdit = QtWidgets.QLineEdit(self.dpm_box)
        self.dpmPluginName_lineEdit.setObjectName("dpmPluginName_lineEdit")
        self.dpm_layout.addWidget(self.dpmPluginName_lineEdit, 3, 1, 1, 1)
        self.dpmDefaultOutputField_label = QtWidgets.QLabel(self.dpm_box)
        self.dpmDefaultOutputField_label.setObjectName("dpmDefaultOutputField_label")
        self.dpm_layout.addWidget(self.dpmDefaultOutputField_label, 5, 0, 1, 1)
        self.dpmPluginPredefined_label = QtWidgets.QLabel(self.dpm_box)
        self.dpmPluginPredefined_label.setObjectName("dpmPluginPredefined_label")
        self.dpm_layout.addWidget(self.dpmPluginPredefined_label, 2, 0, 1, 1)
        self.dpmPluginName_label = QtWidgets.QLabel(self.dpm_box)
        self.dpmPluginName_label.setObjectName("dpmPluginName_label")
        self.dpm_layout.addWidget(self.dpmPluginName_label, 3, 0, 1, 1)
        self.dpmPoi_textEdit = QtWidgets.QTextEdit(self.dpm_box)
        self.dpmPoi_textEdit.setMaximumSize(QtCore.QSize(16777215, 75))
        self.dpmPoi_textEdit.setObjectName("dpmPoi_textEdit")
        self.dpm_layout.addWidget(self.dpmPoi_textEdit, 6, 1, 1, 1)
        self.dpmPluginDescription_textEdit = QtWidgets.QTextEdit(self.dpm_box)
        self.dpmPluginDescription_textEdit.setMaximumSize(QtCore.QSize(16777215, 75))
        self.dpmPluginDescription_textEdit.setObjectName("dpmPluginDescription_textEdit")
        self.dpm_layout.addWidget(self.dpmPluginDescription_textEdit, 4, 1, 1, 1)
        self.dpmSave_button = QtWidgets.QPushButton(self.dpm_box)
        self.dpmSave_button.setObjectName("dpmSave_button")
        self.dpm_layout.addWidget(self.dpmSave_button, 8, 2, 1, 1)
        self.dpmPluginStructure_label = QtWidgets.QLabel(self.dpm_box)
        self.dpmPluginStructure_label.setObjectName("dpmPluginStructure_label")
        self.dpm_layout.addWidget(self.dpmPluginStructure_label, 1, 0, 1, 1)
        self.dpmPoi_label = QtWidgets.QLabel(self.dpm_box)
        self.dpmPoi_label.setObjectName("dpmPoi_label")
        self.dpm_layout.addWidget(self.dpmPoi_label, 6, 0, 1, 1)
        self.dpmPluginStructure_button = QtWidgets.QPushButton(self.dpm_box)
        self.dpmPluginStructure_button.setObjectName("dpmPluginStructure_button")
        self.dpm_layout.addWidget(self.dpmPluginStructure_button, 1, 2, 1, 1)
        self.dpmPluginPredefined_button = QtWidgets.QPushButton(self.dpm_box)
        self.dpmPluginPredefined_button.setObjectName("dpmPluginPredefined_button")
        self.dpm_layout.addWidget(self.dpmPluginPredefined_button, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.dpm_layout.addItem(spacerItem1, 7, 1, 1, 1)
        self.verticalLayout_15.addLayout(self.dpm_layout)
        self.detailed_layout.addWidget(self.dpm_box)
        self.dpoim_box = QtWidgets.QGroupBox(self.management_tab)
        self.dpoim_box.setObjectName("dpoim_box")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.dpoim_box)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.dpoim_topGrid = QtWidgets.QGridLayout()
        self.dpoim_topGrid.setObjectName("dpoim_topGrid")
        self.dpoimPoiType_dropdown = QtWidgets.QComboBox(self.dpoim_box)
        self.dpoimPoiType_dropdown.setObjectName("dpoimPoiType_dropdown")
        self.dpoim_topGrid.addWidget(self.dpoimPoiType_dropdown, 1, 1, 1, 1)
        self.dpoimPlugin_dropdown = QtWidgets.QComboBox(self.dpoim_box)
        self.dpoimPlugin_dropdown.setObjectName("dpoimPlugin_dropdown")
        self.dpoim_topGrid.addWidget(self.dpoimPlugin_dropdown, 0, 1, 1, 1)
        self.dpoimPoiType_label = QtWidgets.QLabel(self.dpoim_box)
        self.dpoimPoiType_label.setObjectName("dpoimPoiType_label")
        self.dpoim_topGrid.addWidget(self.dpoimPoiType_label, 1, 0, 1, 1)
        self.dpoimPlugin_label = QtWidgets.QLabel(self.dpoim_box)
        self.dpoimPlugin_label.setObjectName("dpoimPlugin_label")
        self.dpoim_topGrid.addWidget(self.dpoimPlugin_label, 0, 0, 1, 1)
        self.verticalLayout_18.addLayout(self.dpoim_topGrid)
        self.dpoim_text = QtWidgets.QTextEdit(self.dpoim_box)
        self.dpoim_text.setObjectName("dpoim_text")
        self.verticalLayout_18.addWidget(self.dpoim_text)
        self.dpoim_lowGrid = QtWidgets.QGridLayout()
        self.dpoim_lowGrid.setObjectName("dpoim_lowGrid")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.dpoim_lowGrid.addItem(spacerItem2, 0, 1, 1, 1)
        self.dpoimDelete_button = QtWidgets.QPushButton(self.dpoim_box)
        self.dpoimDelete_button.setObjectName("dpoimDelete_button")
        self.dpoim_lowGrid.addWidget(self.dpoimDelete_button, 0, 0, 1, 1)
        self.dpoimSave_button = QtWidgets.QPushButton(self.dpoim_box)
        self.dpoimSave_button.setObjectName("dpoimSave_button")
        self.dpoim_lowGrid.addWidget(self.dpoimSave_button, 0, 2, 1, 1)
        self.verticalLayout_18.addLayout(self.dpoim_lowGrid)
        self.detailed_layout.addWidget(self.dpoim_box)
        self.horizontalLayout_3.addLayout(self.detailed_layout)
        self.central_tabs.addTab(self.management_tab, "")
        self.verticalLayout_13.addWidget(self.central_tabs)
        BATT5.setCentralWidget(self.central_layout)
        self.menubar = QtWidgets.QMenuBar(BATT5)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1142, 26))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.windows_menu = QtWidgets.QMenu(self.menubar)
        self.windows_menu.setObjectName("windows_menu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        BATT5.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BATT5)
        self.statusbar.setObjectName("statusbar")
        BATT5.setStatusBar(self.statusbar)
        self.actionNew_Project = QtWidgets.QAction(BATT5)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionSave = QtWidgets.QAction(BATT5)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(BATT5)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_Analysis = QtWidgets.QAction(BATT5)
        self.actionSave_Analysis.setObjectName("actionSave_Analysis")
        self.actionSave_as = QtWidgets.QAction(BATT5)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionDocumentation = QtWidgets.QAction(BATT5)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.file_menu.addAction(self.actionNew_Project)
        self.file_menu.addAction(self.actionOpen)
        self.file_menu.addAction(self.actionSave)
        self.file_menu.addAction(self.actionSave_as)
        self.file_menu.addAction(self.actionSave_Analysis)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.windows_menu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(BATT5)
        self.central_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BATT5)

    def retranslateUi(self, BATT5):
        _translate = QtCore.QCoreApplication.translate
        BATT5.setWindowTitle(_translate("BATT5", "MainWindow"))
        self.project_box.setTitle(_translate("BATT5", "Projects"))
        self.projectSearch_lineEdit.setText(_translate("BATT5", "Search.."))
        self.projectNavigator_tree.headerItem().setText(0, _translate("BATT5", "Projects"))
        self.projectProperties_text.setHtml(_translate("BATT5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Project Description: </span>This is a description of the project that is currently selected.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Project Properties:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">OS: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Binary Type:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Machine:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Class:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Bits:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Language:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Canery:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Crypto:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nx:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Relocs:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Relro:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Stripped:</p></body></html>"))
        self.pluginSelection_box.setTitle(_translate("BATT5", "Plugin Selection"))
        self.pluginSelection_dropdown.setItemText(0, _translate("BATT5", "Network Plugin"))
        self.pluginSelection_dropdown.setItemText(1, _translate("BATT5", "Encryption Plugin"))
        self.pluginSelection_dropdown.setItemText(2, _translate("BATT5", "Graph Plugin"))
        self.analyisisControls_box.setTitle(_translate("BATT5", "Analysis Controls"))
        self.runStaticAnalysis_button.setText(_translate("BATT5", "Run Static Analysis"))
        self.runDynamicAnalysis_button.setText(_translate("BATT5", "Run Dynamic Analysis"))
        self.pluginControls_box.setTitle(_translate("BATT5", "Plugin Controls"))
        self.generateScript_button.setText(_translate("BATT5", "Generate Script"))
        self.analysis_box.setTitle(_translate("BATT5", "Analysis"))
        self.radareConsole_box.setTitle(_translate("BATT5", "Radare2 Command Console"))
        self.comment_box.setTitle(_translate("BATT5", "Comment View"))
        self.commentSave_button.setText(_translate("BATT5", "Save"))
        self.commentClear_button.setText(_translate("BATT5", "Clear"))
        self.poi_box.setTitle(_translate("BATT5", "Points of Interest"))
        self.poiType_label.setText(_translate("BATT5", "Type"))
        self.poiType_dropdown.setItemText(0, _translate("BATT5", "Function"))
        self.poiType_dropdown.setItemText(1, _translate("BATT5", "String"))
        self.poiType_dropdown.setItemText(2, _translate("BATT5", "Variable"))
        self.poiType_dropdown.setItemText(3, _translate("BATT5", "DLL"))
        self.poiType_dropdown.setItemText(4, _translate("BATT5", "Packet Protocol"))
        self.poiType_dropdown.setItemText(5, _translate("BATT5", "Struct"))
        self.poiType_dropdown.setItemText(6, _translate("BATT5", "Extract All"))
        self.poiSearch_lineEdit.setText(_translate("BATT5", "Search.."))
        self.central_tabs.setTabText(self.central_tabs.indexOf(self.analysis_tab), _translate("BATT5", "Analysis"))
        self.pluginManagement_box.setTitle(_translate("BATT5", "Plugin Management"))
        self.pluginManagementSearch_lineEdit.setText(_translate("BATT5", "Search.."))
        self.pluginManagementNew_button.setText(_translate("BATT5", "New"))
        self.poiManagement_box.setTitle(_translate("BATT5", "Points of Interest Management"))
        self.poiManagementSeach_lineEdit.setText(_translate("BATT5", "Search.."))
        self.poiManagementNew_button.setText(_translate("BATT5", "New"))
        self.dpm_box.setTitle(_translate("BATT5", "Detailed Plugin Management"))
        self.dpmDelete_button.setText(_translate("BATT5", "Delete"))
        self.dpmPluginDescription_label.setText(_translate("BATT5", "Plugin Description"))
        self.dpmDefaultOutputField_label.setText(_translate("BATT5", "Default Output Field"))
        self.dpmPluginPredefined_label.setText(_translate("BATT5", "Plugin Predefined Data Set"))
        self.dpmPluginName_label.setText(_translate("BATT5", "Plugin Name"))
        self.dpmSave_button.setText(_translate("BATT5", "Save"))
        self.dpmPluginStructure_label.setText(_translate("BATT5", "Plugin Structure"))
        self.dpmPoi_label.setText(_translate("BATT5", "Points of Interest"))
        self.dpmPluginStructure_button.setText(_translate("BATT5", "Browse"))
        self.dpmPluginPredefined_button.setText(_translate("BATT5", "Browse"))
        self.dpoim_box.setTitle(_translate("BATT5", "Detailed Points of Interest Management"))
        self.dpoimPoiType_label.setText(_translate("BATT5", "Point of Interest Type"))
        self.dpoimPlugin_label.setText(_translate("BATT5", "Plugin"))
        self.dpoimDelete_button.setText(_translate("BATT5", "Delete"))
        self.dpoimSave_button.setText(_translate("BATT5", "Save"))
        self.central_tabs.setTabText(self.central_tabs.indexOf(self.management_tab), _translate("BATT5", "Management"))
        self.file_menu.setTitle(_translate("BATT5", "File"))
        self.windows_menu.setTitle(_translate("BATT5", "Windows"))
        self.menuHelp.setTitle(_translate("BATT5", "Help"))
        self.actionNew_Project.setText(_translate("BATT5", "New..."))
        self.actionSave.setText(_translate("BATT5", "Save"))
        self.actionOpen.setText(_translate("BATT5", "Open..."))
        self.actionSave_Analysis.setText(_translate("BATT5", "Save Analysis"))
        self.actionSave_as.setText(_translate("BATT5", "Save as..."))
        self.actionDocumentation.setText(_translate("BATT5", "Documentation"))

