# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BATT5_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BATT5(object):
    def setupUi(self, BATT5):
        BATT5.setObjectName("BATT5")
        BATT5.setWindowModality(QtCore.Qt.NonModal)
        BATT5.resize(957, 716)
        BATT5.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.central_layout = QtWidgets.QWidget(BATT5)
        self.central_layout.setObjectName("central_layout")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.central_layout)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.central_tabs = QtWidgets.QTabWidget(self.central_layout)
        self.central_tabs.setObjectName("central_tabs")
        self.analysis_tab = QtWidgets.QWidget()
        self.analysis_tab.setObjectName("analysis_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.analysis_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.changeViews_stack = QtWidgets.QStackedWidget(self.analysis_tab)
        self.changeViews_stack.setObjectName("changeViews_stack")
        self.current_view = QtWidgets.QWidget()
        self.current_view.setObjectName("current_view")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.current_view)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.project_sublayout = QtWidgets.QVBoxLayout()
        self.project_sublayout.setObjectName("project_sublayout")
        self.project_box = QtWidgets.QGroupBox(self.current_view)
        self.project_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.project_box.setAcceptDrops(False)
        self.project_box.setAutoFillBackground(False)
        self.project_box.setStyleSheet("")
        self.project_box.setFlat(False)
        self.project_box.setCheckable(False)
        self.project_box.setObjectName("project_box")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.project_box)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.projectSearch_lineEdit = QtWidgets.QLineEdit(self.project_box)
        self.projectSearch_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.projectSearch_lineEdit.setStyleSheet("")
        self.projectSearch_lineEdit.setText("")
        self.projectSearch_lineEdit.setObjectName("projectSearch_lineEdit")
        self.verticalLayout_7.addWidget(self.projectSearch_lineEdit)
        self.projectNavigator_tree = QtWidgets.QTreeWidget(self.project_box)
        self.projectNavigator_tree.setMinimumSize(QtCore.QSize(275, 0))
        self.projectNavigator_tree.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.projectNavigator_tree.setObjectName("projectNavigator_tree")
        self.verticalLayout_7.addWidget(self.projectNavigator_tree)
        self.projectProperties_text = QtWidgets.QTextBrowser(self.project_box)
        self.projectProperties_text.setMinimumSize(QtCore.QSize(275, 0))
        self.projectProperties_text.setMaximumSize(QtCore.QSize(16777215, 400))
        self.projectProperties_text.setObjectName("projectProperties_text")
        self.verticalLayout_7.addWidget(self.projectProperties_text)
        self.project_sublayout.addWidget(self.project_box)
        self.pluginSelection_box = QtWidgets.QGroupBox(self.current_view)
        self.pluginSelection_box.setMinimumSize(QtCore.QSize(250, 65))
        self.pluginSelection_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pluginSelection_box.setObjectName("pluginSelection_box")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.pluginSelection_box)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pluginSelection_dropdown = QtWidgets.QComboBox(self.pluginSelection_box)
        self.pluginSelection_dropdown.setMinimumSize(QtCore.QSize(275, 0))
        self.pluginSelection_dropdown.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pluginSelection_dropdown.setObjectName("pluginSelection_dropdown")
        self.verticalLayout_8.addWidget(self.pluginSelection_dropdown)
        self.project_sublayout.addWidget(self.pluginSelection_box)
        self.analyisisControls_box = QtWidgets.QGroupBox(self.current_view)
        self.analyisisControls_box.setMinimumSize(QtCore.QSize(300, 100))
        self.analyisisControls_box.setMaximumSize(QtCore.QSize(310, 16777215))
        self.analyisisControls_box.setObjectName("analyisisControls_box")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.analyisisControls_box)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.runStaticAnalysis_button = QtWidgets.QPushButton(self.analyisisControls_box)
        self.runStaticAnalysis_button.setObjectName("runStaticAnalysis_button")
        self.verticalLayout_9.addWidget(self.runStaticAnalysis_button)
        self.runDynamicAnalysis_button = QtWidgets.QPushButton(self.analyisisControls_box)
        self.runDynamicAnalysis_button.setStyleSheet("color: rgb(136, 138, 133);\n"
"background-color: rgb(186, 189, 182);")
        self.runDynamicAnalysis_button.setObjectName("runDynamicAnalysis_button")
        self.verticalLayout_9.addWidget(self.runDynamicAnalysis_button)
        self.project_sublayout.addWidget(self.analyisisControls_box, 0, QtCore.Qt.AlignLeft)
        self.pluginControls_box = QtWidgets.QGroupBox(self.current_view)
        self.pluginControls_box.setMinimumSize(QtCore.QSize(300, 70))
        self.pluginControls_box.setMaximumSize(QtCore.QSize(250, 16777215))
        self.pluginControls_box.setObjectName("pluginControls_box")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.pluginControls_box)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.generateScript_button = QtWidgets.QPushButton(self.pluginControls_box)
        self.generateScript_button.setObjectName("generateScript_button")
        self.verticalLayout_10.addWidget(self.generateScript_button)
        self.project_sublayout.addWidget(self.pluginControls_box)
        self.horizontalLayout_4.addLayout(self.project_sublayout)
        self.detailedAnalysis_sublayout = QtWidgets.QVBoxLayout()
        self.detailedAnalysis_sublayout.setObjectName("detailedAnalysis_sublayout")
        self.analysis_box = QtWidgets.QGroupBox(self.current_view)
        self.analysis_box.setObjectName("analysis_box")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.analysis_box)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.viewPoi_stack = QtWidgets.QStackedWidget(self.analysis_box)
        self.viewPoi_stack.setObjectName("viewPoi_stack")
        self.viewFunc_page = QtWidgets.QWidget()
        self.viewFunc_page.setObjectName("viewFunc_page")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.viewFunc_page)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.vewFunc_tree = QtWidgets.QTreeWidget(self.viewFunc_page)
        self.vewFunc_tree.setObjectName("vewFunc_tree")
        self.verticalLayout_29.addWidget(self.vewFunc_tree)
        self.viewPoi_stack.addWidget(self.viewFunc_page)
        self.viewString_page = QtWidgets.QWidget()
        self.viewString_page.setObjectName("viewString_page")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.viewString_page)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.viewString_tree = QtWidgets.QTreeWidget(self.viewString_page)
        self.viewString_tree.setObjectName("viewString_tree")
        self.verticalLayout_30.addWidget(self.viewString_tree)
        self.viewPoi_stack.addWidget(self.viewString_page)
        self.viewVar_page = QtWidgets.QWidget()
        self.viewVar_page.setObjectName("viewVar_page")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.viewVar_page)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.viewVar_tree = QtWidgets.QTreeWidget(self.viewVar_page)
        self.viewVar_tree.setObjectName("viewVar_tree")
        self.verticalLayout_31.addWidget(self.viewVar_tree)
        self.viewPoi_stack.addWidget(self.viewVar_page)
        self.viewDll_page = QtWidgets.QWidget()
        self.viewDll_page.setObjectName("viewDll_page")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.viewDll_page)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.viewDll_tree = QtWidgets.QTreeWidget(self.viewDll_page)
        self.viewDll_tree.setObjectName("viewDll_tree")
        self.verticalLayout_28.addWidget(self.viewDll_tree)
        self.viewPoi_stack.addWidget(self.viewDll_page)
        self.verticalLayout_16.addWidget(self.viewPoi_stack)
        self.detailedAnalysis_sublayout.addWidget(self.analysis_box)
        self.radareConsole_box = QtWidgets.QGroupBox(self.current_view)
        self.radareConsole_box.setMinimumSize(QtCore.QSize(300, 100))
        self.radareConsole_box.setMaximumSize(QtCore.QSize(16777215, 247))
        self.radareConsole_box.setObjectName("radareConsole_box")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.radareConsole_box)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.radareConsoleOut_text = QtWidgets.QTextBrowser(self.radareConsole_box)
        self.radareConsoleOut_text.setObjectName("radareConsoleOut_text")
        self.verticalLayout_17.addWidget(self.radareConsoleOut_text)
        self.radareConsoleIn_lineEdit = QtWidgets.QLineEdit(self.radareConsole_box)
        self.radareConsoleIn_lineEdit.setStyleSheet("")
        self.radareConsoleIn_lineEdit.setText("")
        self.radareConsoleIn_lineEdit.setObjectName("radareConsoleIn_lineEdit")
        self.verticalLayout_17.addWidget(self.radareConsoleIn_lineEdit)
        self.detailedAnalysis_sublayout.addWidget(self.radareConsole_box)
        self.horizontalLayout_4.addLayout(self.detailedAnalysis_sublayout)
        self.commentAndPoi_sublayout = QtWidgets.QVBoxLayout()
        self.commentAndPoi_sublayout.setObjectName("commentAndPoi_sublayout")
        self.comment_box = QtWidgets.QGroupBox(self.current_view)
        self.comment_box.setMaximumSize(QtCore.QSize(300, 150))
        self.comment_box.setObjectName("comment_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.comment_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comment_text = QtWidgets.QTextEdit(self.comment_box)
        self.comment_text.setMinimumSize(QtCore.QSize(0, 0))
        self.comment_text.setMaximumSize(QtCore.QSize(16777215, 75))
        self.comment_text.setObjectName("comment_text")
        self.verticalLayout_2.addWidget(self.comment_text)
        self.commentButton_layout = QtWidgets.QGridLayout()
        self.commentButton_layout.setObjectName("commentButton_layout")
        self.commentSave_button = QtWidgets.QPushButton(self.comment_box)
        self.commentSave_button.setObjectName("commentSave_button")
        self.commentButton_layout.addWidget(self.commentSave_button, 0, 1, 1, 1)
        self.commentClear_button = QtWidgets.QPushButton(self.comment_box)
        self.commentClear_button.setObjectName("commentClear_button")
        self.commentButton_layout.addWidget(self.commentClear_button, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.commentButton_layout)
        self.commentAndPoi_sublayout.addWidget(self.comment_box)
        self.poi_box = QtWidgets.QGroupBox(self.current_view)
        self.poi_box.setMinimumSize(QtCore.QSize(0, 50))
        self.poi_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.poi_box.setObjectName("poi_box")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.poi_box)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.poi_layout = QtWidgets.QGridLayout()
        self.poi_layout.setObjectName("poi_layout")
        self.poiType_label = QtWidgets.QLabel(self.poi_box)
        self.poiType_label.setObjectName("poiType_label")
        self.poi_layout.addWidget(self.poiType_label, 0, 0, 1, 1)
        self.poiType_dropdown = QtWidgets.QComboBox(self.poi_box)
        self.poiType_dropdown.setObjectName("poiType_dropdown")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poiType_dropdown.addItem("")
        self.poi_layout.addWidget(self.poiType_dropdown, 0, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.poi_layout)
        self.check_allpoi = QtWidgets.QCheckBox(self.poi_box)
        self.check_allpoi.setObjectName("check_allpoi")
        self.verticalLayout_11.addWidget(self.check_allpoi)
        self.poiSearch_lineEdit = QtWidgets.QLineEdit(self.poi_box)
        self.poiSearch_lineEdit.setStyleSheet("")
        self.poiSearch_lineEdit.setText("")
        self.poiSearch_lineEdit.setObjectName("poiSearch_lineEdit")
        self.verticalLayout_11.addWidget(self.poiSearch_lineEdit)
        self.poi_list = QtWidgets.QListWidget(self.poi_box)
        self.poi_list.setMinimumSize(QtCore.QSize(275, 0))
        self.poi_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.poi_list.setObjectName("poi_list")
        self.verticalLayout_11.addWidget(self.poi_list)
        self.commentAndPoi_sublayout.addWidget(self.poi_box)
        self.viewCurrent_box = QtWidgets.QGroupBox(self.current_view)
        self.viewCurrent_box.setObjectName("viewCurrent_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.viewCurrent_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.switchToHistory_button = QtWidgets.QPushButton(self.viewCurrent_box)
        self.switchToHistory_button.setObjectName("switchToHistory_button")
        self.verticalLayout_3.addWidget(self.switchToHistory_button)
        self.commentAndPoi_sublayout.addWidget(self.viewCurrent_box)
        self.horizontalLayout_4.addLayout(self.commentAndPoi_sublayout)
        self.changeViews_stack.addWidget(self.current_view)
        self.history_view = QtWidgets.QWidget()
        self.history_view.setObjectName("history_view")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.history_view)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.project_sublayout_h = QtWidgets.QVBoxLayout()
        self.project_sublayout_h.setObjectName("project_sublayout_h")
        self.project_box_h = QtWidgets.QGroupBox(self.history_view)
        self.project_box_h.setMaximumSize(QtCore.QSize(300, 200))
        self.project_box_h.setAcceptDrops(False)
        self.project_box_h.setAutoFillBackground(False)
        self.project_box_h.setStyleSheet("")
        self.project_box_h.setFlat(False)
        self.project_box_h.setCheckable(False)
        self.project_box_h.setObjectName("project_box_h")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.project_box_h)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.projectProperties_text_h = QtWidgets.QTextBrowser(self.project_box_h)
        self.projectProperties_text_h.setMinimumSize(QtCore.QSize(275, 0))
        self.projectProperties_text_h.setMaximumSize(QtCore.QSize(250, 250))
        self.projectProperties_text_h.setObjectName("projectProperties_text_h")
        self.verticalLayout_22.addWidget(self.projectProperties_text_h)
        self.project_sublayout_h.addWidget(self.project_box_h)
        self.daRuns_box = QtWidgets.QGroupBox(self.history_view)
        self.daRuns_box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.daRuns_box.setObjectName("daRuns_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.daRuns_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.daRuns_list = QtWidgets.QListWidget(self.daRuns_box)
        self.daRuns_list.setObjectName("daRuns_list")
        self.verticalLayout_6.addWidget(self.daRuns_list)
        self.project_sublayout_h.addWidget(self.daRuns_box)
        self.recentCmd_box = QtWidgets.QGroupBox(self.history_view)
        self.recentCmd_box.setMaximumSize(QtCore.QSize(300, 200))
        self.recentCmd_box.setObjectName("recentCmd_box")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.recentCmd_box)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.recentCmd_text = QtWidgets.QTextBrowser(self.recentCmd_box)
        self.recentCmd_text.setObjectName("recentCmd_text")
        self.verticalLayout_25.addWidget(self.recentCmd_text)
        self.project_sublayout_h.addWidget(self.recentCmd_box)
        self.horizontalLayout.addLayout(self.project_sublayout_h)
        self.detailedAnalysis_sublayout_2 = QtWidgets.QVBoxLayout()
        self.detailedAnalysis_sublayout_2.setObjectName("detailedAnalysis_sublayout_2")
        self.daRunDetails_box = QtWidgets.QGroupBox(self.history_view)
        self.daRunDetails_box.setObjectName("daRunDetails_box")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.daRunDetails_box)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.daRunDetails_table = QtWidgets.QTableWidget(self.daRunDetails_box)
        self.daRunDetails_table.setObjectName("daRunDetails_table")
        self.daRunDetails_table.setColumnCount(0)
        self.daRunDetails_table.setRowCount(0)
        self.verticalLayout_20.addWidget(self.daRunDetails_table)
        self.detailedAnalysis_sublayout_2.addWidget(self.daRunDetails_box)
        self.horizontalLayout.addLayout(self.detailedAnalysis_sublayout_2)
        self.commentAndPoi_sublayout_2 = QtWidgets.QVBoxLayout()
        self.commentAndPoi_sublayout_2.setObjectName("commentAndPoi_sublayout_2")
        self.comment_box_2 = QtWidgets.QGroupBox(self.history_view)
        self.comment_box_2.setMaximumSize(QtCore.QSize(300, 150))
        self.comment_box_2.setObjectName("comment_box_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.comment_box_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comment_text_2 = QtWidgets.QTextEdit(self.comment_box_2)
        self.comment_text_2.setMinimumSize(QtCore.QSize(0, 0))
        self.comment_text_2.setMaximumSize(QtCore.QSize(16777215, 75))
        self.comment_text_2.setObjectName("comment_text_2")
        self.verticalLayout_4.addWidget(self.comment_text_2)
        self.commentButton_layout_2 = QtWidgets.QGridLayout()
        self.commentButton_layout_2.setObjectName("commentButton_layout_2")
        self.commentSave_button_2 = QtWidgets.QPushButton(self.comment_box_2)
        self.commentSave_button_2.setObjectName("commentSave_button_2")
        self.commentButton_layout_2.addWidget(self.commentSave_button_2, 0, 0, 1, 1)
        self.commentClear_button_2 = QtWidgets.QPushButton(self.comment_box_2)
        self.commentClear_button_2.setObjectName("commentClear_button_2")
        self.commentButton_layout_2.addWidget(self.commentClear_button_2, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.commentButton_layout_2)
        self.commentAndPoi_sublayout_2.addWidget(self.comment_box_2)
        self.poi_box_2 = QtWidgets.QGroupBox(self.history_view)
        self.poi_box_2.setMinimumSize(QtCore.QSize(0, 50))
        self.poi_box_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.poi_box_2.setObjectName("poi_box_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.poi_box_2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.poi_layout_2 = QtWidgets.QGridLayout()
        self.poi_layout_2.setObjectName("poi_layout_2")
        self.poiType_dropdown_2 = QtWidgets.QComboBox(self.poi_box_2)
        self.poiType_dropdown_2.setObjectName("poiType_dropdown_2")
        self.poiType_dropdown_2.addItem("")
        self.poiType_dropdown_2.addItem("")
        self.poiType_dropdown_2.addItem("")
        self.poiType_dropdown_2.addItem("")
        self.poiType_dropdown_2.addItem("")
        self.poiType_dropdown_2.addItem("")
        self.poi_layout_2.addWidget(self.poiType_dropdown_2, 0, 1, 1, 1)
        self.poiType_label_2 = QtWidgets.QLabel(self.poi_box_2)
        self.poiType_label_2.setObjectName("poiType_label_2")
        self.poi_layout_2.addWidget(self.poiType_label_2, 0, 0, 1, 1)
        self.verticalLayout_19.addLayout(self.poi_layout_2)
        self.poiSearch_lineEdit_2 = QtWidgets.QLineEdit(self.poi_box_2)
        self.poiSearch_lineEdit_2.setStyleSheet("color: rgb(136, 138, 133);")
        self.poiSearch_lineEdit_2.setObjectName("poiSearch_lineEdit_2")
        self.verticalLayout_19.addWidget(self.poiSearch_lineEdit_2)
        self.poi_list_2 = QtWidgets.QListWidget(self.poi_box_2)
        self.poi_list_2.setMinimumSize(QtCore.QSize(275, 0))
        self.poi_list_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.poi_list_2.setObjectName("poi_list_2")
        self.verticalLayout_19.addWidget(self.poi_list_2)
        self.commentAndPoi_sublayout_2.addWidget(self.poi_box_2)
        self.switchToCurrent_box = QtWidgets.QGroupBox(self.history_view)
        self.switchToCurrent_box.setObjectName("switchToCurrent_box")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.switchToCurrent_box)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.switchToCurrent_button = QtWidgets.QPushButton(self.switchToCurrent_box)
        self.switchToCurrent_button.setObjectName("switchToCurrent_button")
        self.verticalLayout_5.addWidget(self.switchToCurrent_button)
        self.commentAndPoi_sublayout_2.addWidget(self.switchToCurrent_box)
        self.horizontalLayout.addLayout(self.commentAndPoi_sublayout_2)
        self.changeViews_stack.addWidget(self.history_view)
        self.horizontalLayout_2.addWidget(self.changeViews_stack)
        self.central_tabs.addTab(self.analysis_tab, "")
        self.management_tab = QtWidgets.QWidget()
        self.management_tab.setObjectName("management_tab")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.management_tab)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.pluginManagement_layout = QtWidgets.QHBoxLayout()
        self.pluginManagement_layout.setObjectName("pluginManagement_layout")
        self.pluginManagement_box = QtWidgets.QGroupBox(self.management_tab)
        self.pluginManagement_box.setMinimumSize(QtCore.QSize(300, 0))
        self.pluginManagement_box.setMaximumSize(QtCore.QSize(200, 16777215))
        self.pluginManagement_box.setStyleSheet("")
        self.pluginManagement_box.setObjectName("pluginManagement_box")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.pluginManagement_box)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pluginManagementSearch_lineEdit = QtWidgets.QLineEdit(self.pluginManagement_box)
        self.pluginManagementSearch_lineEdit.setStyleSheet("")
        self.pluginManagementSearch_lineEdit.setText("")
        self.pluginManagementSearch_lineEdit.setObjectName("pluginManagementSearch_lineEdit")
        self.verticalLayout_12.addWidget(self.pluginManagementSearch_lineEdit)
        self.pluginManagement_list = QtWidgets.QListWidget(self.pluginManagement_box)
        self.pluginManagement_list.setMinimumSize(QtCore.QSize(275, 0))
        self.pluginManagement_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pluginManagement_list.setObjectName("pluginManagement_list")
        self.verticalLayout_12.addWidget(self.pluginManagement_list)
        self.pluginManagement_layout.addWidget(self.pluginManagement_box)
        self.dpm_box = QtWidgets.QGroupBox(self.management_tab)
        self.dpm_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dpm_box.setObjectName("dpm_box")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.dpm_box)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.addPluginXml_frame = QtWidgets.QFrame(self.dpm_box)
        self.addPluginXml_frame.setEnabled(True)
        self.addPluginXml_frame.setWhatsThis("")
        self.addPluginXml_frame.setAutoFillBackground(True)
        self.addPluginXml_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addPluginXml_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.addPluginXml_frame.setObjectName("addPluginXml_frame")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.addPluginXml_frame)
        self.verticalLayout_27.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem)
        self.manualPluginAdd = QtWidgets.QGridLayout()
        self.manualPluginAdd.setObjectName("manualPluginAdd")
        self.dpmPluginStructure_lineEdit = QtWidgets.QLineEdit(self.addPluginXml_frame)
        font = QtGui.QFont()
        font.setItalic(True)
        self.dpmPluginStructure_lineEdit.setFont(font)
        self.dpmPluginStructure_lineEdit.setText("")
        self.dpmPluginStructure_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dpmPluginStructure_lineEdit.setReadOnly(True)
        self.dpmPluginStructure_lineEdit.setPlaceholderText("")
        self.dpmPluginStructure_lineEdit.setObjectName("dpmPluginStructure_lineEdit")
        self.manualPluginAdd.addWidget(self.dpmPluginStructure_lineEdit, 1, 1, 1, 1)
        self.dpmPluginStructure_label = QtWidgets.QLabel(self.addPluginXml_frame)
        self.dpmPluginStructure_label.setMinimumSize(QtCore.QSize(140, 0))
        self.dpmPluginStructure_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dpmPluginStructure_label.setObjectName("dpmPluginStructure_label")
        self.manualPluginAdd.addWidget(self.dpmPluginStructure_label, 1, 0, 1, 1)
        self.dpmPluginStructure_button = QtWidgets.QPushButton(self.addPluginXml_frame)
        self.dpmPluginStructure_button.setMinimumSize(QtCore.QSize(100, 0))
        self.dpmPluginStructure_button.setObjectName("dpmPluginStructure_button")
        self.manualPluginAdd.addWidget(self.dpmPluginStructure_button, 1, 2, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.clearXMLPlugin_button = QtWidgets.QPushButton(self.addPluginXml_frame)
        self.clearXMLPlugin_button.setObjectName("clearXMLPlugin_button")
        self.horizontalLayout_6.addWidget(self.clearXMLPlugin_button)
        self.saveXMLPlugin_button = QtWidgets.QPushButton(self.addPluginXml_frame)
        self.saveXMLPlugin_button.setObjectName("saveXMLPlugin_button")
        self.horizontalLayout_6.addWidget(self.saveXMLPlugin_button)
        self.manualPluginAdd.addLayout(self.horizontalLayout_6, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.addPluginXml_frame)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.manualPluginAdd.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout_27.addLayout(self.manualPluginAdd)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem1)
        self.verticalLayout_15.addWidget(self.addPluginXml_frame)
        self.addPluginManual_frame = QtWidgets.QFrame(self.dpm_box)
        self.addPluginManual_frame.setAutoFillBackground(True)
        self.addPluginManual_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addPluginManual_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.addPluginManual_frame.setObjectName("addPluginManual_frame")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.addPluginManual_frame)
        self.verticalLayout_26.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dpmOutFuncName_label = QtWidgets.QLabel(self.addPluginManual_frame)
        self.dpmOutFuncName_label.setMinimumSize(QtCore.QSize(120, 0))
        self.dpmOutFuncName_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dpmOutFuncName_label.setObjectName("dpmOutFuncName_label")
        self.gridLayout_2.addWidget(self.dpmOutFuncName_label, 5, 0, 1, 1)
        self.dpmPluginDesc_lineEdit = QtWidgets.QLineEdit(self.addPluginManual_frame)
        self.dpmPluginDesc_lineEdit.setObjectName("dpmPluginDesc_lineEdit")
        self.gridLayout_2.addWidget(self.dpmPluginDesc_lineEdit, 3, 1, 1, 1)
        self.dpmOutName_lable = QtWidgets.QLabel(self.addPluginManual_frame)
        self.dpmOutName_lable.setMinimumSize(QtCore.QSize(120, 0))
        self.dpmOutName_lable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dpmOutName_lable.setObjectName("dpmOutName_lable")
        self.gridLayout_2.addWidget(self.dpmOutName_lable, 4, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.clearManualPlugin_button = QtWidgets.QPushButton(self.addPluginManual_frame)
        self.clearManualPlugin_button.setObjectName("clearManualPlugin_button")
        self.horizontalLayout_8.addWidget(self.clearManualPlugin_button)
        self.saveManualPlugin_button = QtWidgets.QPushButton(self.addPluginManual_frame)
        self.saveManualPlugin_button.setObjectName("saveManualPlugin_button")
        self.horizontalLayout_8.addWidget(self.saveManualPlugin_button)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 7, 1, 1, 1)
        self.dpmOutFuncSource_label = QtWidgets.QLabel(self.addPluginManual_frame)
        self.dpmOutFuncSource_label.setMinimumSize(QtCore.QSize(120, 0))
        self.dpmOutFuncSource_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dpmOutFuncSource_label.setObjectName("dpmOutFuncSource_label")
        self.gridLayout_2.addWidget(self.dpmOutFuncSource_label, 6, 0, 1, 1)
        self.dpmOutFuncSource_button = QtWidgets.QPushButton(self.addPluginManual_frame)
        self.dpmOutFuncSource_button.setMinimumSize(QtCore.QSize(100, 0))
        self.dpmOutFuncSource_button.setObjectName("dpmOutFuncSource_button")
        self.gridLayout_2.addWidget(self.dpmOutFuncSource_button, 6, 2, 1, 1)
        self.dpmPluginName_lineEdit = QtWidgets.QLineEdit(self.addPluginManual_frame)
        self.dpmPluginName_lineEdit.setObjectName("dpmPluginName_lineEdit")
        self.gridLayout_2.addWidget(self.dpmPluginName_lineEdit, 2, 1, 1, 1)
        self.pluginEditingStatus_label = QtWidgets.QLabel(self.addPluginManual_frame)
        self.pluginEditingStatus_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.pluginEditingStatus_label.setFont(font)
        self.pluginEditingStatus_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pluginEditingStatus_label.setObjectName("pluginEditingStatus_label")
        self.gridLayout_2.addWidget(self.pluginEditingStatus_label, 1, 1, 1, 1)
        self.dpmOutFuncName_lineEdit = QtWidgets.QLineEdit(self.addPluginManual_frame)
        self.dpmOutFuncName_lineEdit.setObjectName("dpmOutFuncName_lineEdit")
        self.gridLayout_2.addWidget(self.dpmOutFuncName_lineEdit, 5, 1, 1, 1)
        self.dpmOutFuncSource_lineEdit = QtWidgets.QLineEdit(self.addPluginManual_frame)
        font = QtGui.QFont()
        font.setItalic(True)
        self.dpmOutFuncSource_lineEdit.setFont(font)
        self.dpmOutFuncSource_lineEdit.setReadOnly(True)
        self.dpmOutFuncSource_lineEdit.setPlaceholderText("")
        self.dpmOutFuncSource_lineEdit.setClearButtonEnabled(False)
        self.dpmOutFuncSource_lineEdit.setObjectName("dpmOutFuncSource_lineEdit")
        self.gridLayout_2.addWidget(self.dpmOutFuncSource_lineEdit, 6, 1, 1, 1)
        self.dpmPluginDesc_label = QtWidgets.QLabel(self.addPluginManual_frame)
        self.dpmPluginDesc_label.setMinimumSize(QtCore.QSize(120, 0))
        self.dpmPluginDesc_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dpmPluginDesc_label.setObjectName("dpmPluginDesc_label")
        self.gridLayout_2.addWidget(self.dpmPluginDesc_label, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.addPluginManual_frame)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 8, 1, 1, 1)
        self.dpmOutName_lineEdit = QtWidgets.QLineEdit(self.addPluginManual_frame)
        self.dpmOutName_lineEdit.setObjectName("dpmOutName_lineEdit")
        self.gridLayout_2.addWidget(self.dpmOutName_lineEdit, 4, 1, 1, 1)
        self.dpmPluginName_label = QtWidgets.QLabel(self.addPluginManual_frame)
        self.dpmPluginName_label.setMinimumSize(QtCore.QSize(140, 0))
        self.dpmPluginName_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dpmPluginName_label.setObjectName("dpmPluginName_label")
        self.gridLayout_2.addWidget(self.dpmPluginName_label, 2, 0, 1, 1)
        self.verticalLayout_26.addLayout(self.gridLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_26.addItem(spacerItem3)
        self.verticalLayout_15.addWidget(self.addPluginManual_frame)
        self.pluginManagement_layout.addWidget(self.dpm_box)
        self.verticalLayout_21.addLayout(self.pluginManagement_layout)
        self.poiMmgmnt_layout = QtWidgets.QHBoxLayout()
        self.poiMmgmnt_layout.setObjectName("poiMmgmnt_layout")
        self.poiManagement_box = QtWidgets.QGroupBox(self.management_tab)
        self.poiManagement_box.setMinimumSize(QtCore.QSize(300, 0))
        self.poiManagement_box.setMaximumSize(QtCore.QSize(30, 16777215))
        self.poiManagement_box.setObjectName("poiManagement_box")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.poiManagement_box)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.poiManagement_box)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.addPoiType_dropdown = QtWidgets.QComboBox(self.poiManagement_box)
        self.addPoiType_dropdown.setMinimumSize(QtCore.QSize(100, 0))
        self.addPoiType_dropdown.setObjectName("addPoiType_dropdown")
        self.addPoiType_dropdown.addItem("")
        self.addPoiType_dropdown.addItem("")
        self.addPoiType_dropdown.addItem("")
        self.addPoiType_dropdown.addItem("")
        self.horizontalLayout_5.addWidget(self.addPoiType_dropdown)
        self.verticalLayout_14.addLayout(self.horizontalLayout_5)
        self.poiManagementSeach_lineEdit = QtWidgets.QLineEdit(self.poiManagement_box)
        self.poiManagementSeach_lineEdit.setStyleSheet("")
        self.poiManagementSeach_lineEdit.setText("")
        self.poiManagementSeach_lineEdit.setObjectName("poiManagementSeach_lineEdit")
        self.verticalLayout_14.addWidget(self.poiManagementSeach_lineEdit)
        self.poiManagement_list = QtWidgets.QListWidget(self.poiManagement_box)
        self.poiManagement_list.setMinimumSize(QtCore.QSize(175, 0))
        self.poiManagement_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.poiManagement_list.setObjectName("poiManagement_list")
        self.verticalLayout_14.addWidget(self.poiManagement_list)
        self.poiMmgmnt_layout.addWidget(self.poiManagement_box)
        self.dpoim_box = QtWidgets.QGroupBox(self.management_tab)
        self.dpoim_box.setObjectName("dpoim_box")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.dpoim_box)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.addPoiXml_frame = QtWidgets.QFrame(self.dpoim_box)
        self.addPoiXml_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.addPoiXml_frame.setAutoFillBackground(True)
        self.addPoiXml_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addPoiXml_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.addPoiXml_frame.setObjectName("addPoiXml_frame")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.addPoiXml_frame)
        self.verticalLayout_23.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem4)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dpoimPredefined_button = QtWidgets.QPushButton(self.addPoiXml_frame)
        self.dpoimPredefined_button.setMinimumSize(QtCore.QSize(100, 0))
        self.dpoimPredefined_button.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dpoimPredefined_button.setObjectName("dpoimPredefined_button")
        self.gridLayout_3.addWidget(self.dpoimPredefined_button, 1, 2, 1, 1)
        self.dpoimPredefined_lineEdit = QtWidgets.QLineEdit(self.addPoiXml_frame)
        font = QtGui.QFont()
        font.setItalic(True)
        self.dpoimPredefined_lineEdit.setFont(font)
        self.dpoimPredefined_lineEdit.setText("")
        self.dpoimPredefined_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.dpoimPredefined_lineEdit.setReadOnly(True)
        self.dpoimPredefined_lineEdit.setPlaceholderText("")
        self.dpoimPredefined_lineEdit.setObjectName("dpoimPredefined_lineEdit")
        self.gridLayout_3.addWidget(self.dpoimPredefined_lineEdit, 1, 1, 1, 1)
        self.dpoimPredefined_label = QtWidgets.QLabel(self.addPoiXml_frame)
        self.dpoimPredefined_label.setMinimumSize(QtCore.QSize(140, 0))
        self.dpoimPredefined_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.dpoimPredefined_label.setObjectName("dpoimPredefined_label")
        self.gridLayout_3.addWidget(self.dpoimPredefined_label, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.clearPredefPoi_button = QtWidgets.QPushButton(self.addPoiXml_frame)
        self.clearPredefPoi_button.setObjectName("clearPredefPoi_button")
        self.horizontalLayout_9.addWidget(self.clearPredefPoi_button)
        self.savePredefPoi_button = QtWidgets.QPushButton(self.addPoiXml_frame)
        self.savePredefPoi_button.setObjectName("savePredefPoi_button")
        self.horizontalLayout_9.addWidget(self.savePredefPoi_button)
        self.gridLayout_3.addLayout(self.horizontalLayout_9, 2, 1, 1, 1)
        self.addPoiXML_label = QtWidgets.QLabel(self.addPoiXml_frame)
        self.addPoiXML_label.setMinimumSize(QtCore.QSize(0, 0))
        self.addPoiXML_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.addPoiXML_label.setFont(font)
        self.addPoiXML_label.setAlignment(QtCore.Qt.AlignCenter)
        self.addPoiXML_label.setObjectName("addPoiXML_label")
        self.gridLayout_3.addWidget(self.addPoiXML_label, 0, 1, 1, 1)
        self.verticalLayout_23.addLayout(self.gridLayout_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_23.addItem(spacerItem5)
        self.verticalLayout_18.addWidget(self.addPoiXml_frame)
        self.addPoiManual_frame = QtWidgets.QFrame(self.dpoim_box)
        self.addPoiManual_frame.setAutoFillBackground(True)
        self.addPoiManual_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.addPoiManual_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.addPoiManual_frame.setObjectName("addPoiManual_frame")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.addPoiManual_frame)
        self.verticalLayout_24.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_24.setSpacing(6)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem6)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.addPoi_label = QtWidgets.QLabel(self.addPoiManual_frame)
        self.addPoi_label.setMinimumSize(QtCore.QSize(140, 0))
        self.addPoi_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.addPoi_label.setObjectName("addPoi_label")
        self.gridLayout.addWidget(self.addPoi_label, 2, 0, 1, 1)
        self.addPoiName_lineEdit = QtWidgets.QLineEdit(self.addPoiManual_frame)
        self.addPoiName_lineEdit.setObjectName("addPoiName_lineEdit")
        self.gridLayout.addWidget(self.addPoiName_lineEdit, 2, 2, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.clearPoiAll_button = QtWidgets.QPushButton(self.addPoiManual_frame)
        self.clearPoiAll_button.setObjectName("clearPoiAll_button")
        self.horizontalLayout_11.addWidget(self.clearPoiAll_button)
        self.savePoi_button = QtWidgets.QPushButton(self.addPoiManual_frame)
        self.savePoi_button.setMinimumSize(QtCore.QSize(100, 0))
        self.savePoi_button.setObjectName("savePoi_button")
        self.horizontalLayout_11.addWidget(self.savePoi_button)
        self.gridLayout.addLayout(self.horizontalLayout_11, 3, 2, 1, 1)
        self.addPoiManual_label = QtWidgets.QLabel(self.addPoiManual_frame)
        self.addPoiManual_label.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.addPoiManual_label.setFont(font)
        self.addPoiManual_label.setAlignment(QtCore.Qt.AlignCenter)
        self.addPoiManual_label.setObjectName("addPoiManual_label")
        self.gridLayout.addWidget(self.addPoiManual_label, 1, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 2, 3, 1, 1)
        self.verticalLayout_24.addLayout(self.gridLayout)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem8)
        self.verticalLayout_18.addWidget(self.addPoiManual_frame)
        self.poiMmgmnt_layout.addWidget(self.dpoim_box)
        self.verticalLayout_21.addLayout(self.poiMmgmnt_layout)
        self.central_tabs.addTab(self.management_tab, "")
        self.verticalLayout_13.addWidget(self.central_tabs)
        BATT5.setCentralWidget(self.central_layout)
        self.menubar = QtWidgets.QMenuBar(BATT5)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 957, 21))
        self.menubar.setObjectName("menubar")
        self.file_menu = QtWidgets.QMenu(self.menubar)
        self.file_menu.setObjectName("file_menu")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        BATT5.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BATT5)
        self.statusbar.setObjectName("statusbar")
        BATT5.setStatusBar(self.statusbar)
        self.actionNew_Project = QtWidgets.QAction(BATT5)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionSave = QtWidgets.QAction(BATT5)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(BATT5)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave_Analysis = QtWidgets.QAction(BATT5)
        self.actionSave_Analysis.setObjectName("actionSave_Analysis")
        self.actionSave_as = QtWidgets.QAction(BATT5)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionDocumentation = QtWidgets.QAction(BATT5)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionSave_Analysis_2 = QtWidgets.QAction(BATT5)
        self.actionSave_Analysis_2.setObjectName("actionSave_Analysis_2")
        self.actionOpen_Project = QtWidgets.QAction(BATT5)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionExport_Project = QtWidgets.QAction(BATT5)
        self.actionExport_Project.setObjectName("actionExport_Project")
        self.file_menu.addAction(self.actionNew_Project)
        self.file_menu.addAction(self.actionOpen_Project)
        self.file_menu.addAction(self.actionExport_Project)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.actionSave_Analysis_2)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(BATT5)
        self.central_tabs.setCurrentIndex(0)
        self.changeViews_stack.setCurrentIndex(0)
        self.viewPoi_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BATT5)

    def retranslateUi(self, BATT5):
        _translate = QtCore.QCoreApplication.translate
        BATT5.setWindowTitle(_translate("BATT5", "BATT5"))
        self.project_box.setTitle(_translate("BATT5", "Projects"))
        self.projectSearch_lineEdit.setPlaceholderText(_translate("BATT5", "Search.."))
        self.projectNavigator_tree.headerItem().setText(0, _translate("BATT5", "Projects"))
        self.projectProperties_text.setHtml(_translate("BATT5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.pluginSelection_box.setTitle(_translate("BATT5", "Plugin Selection"))
        self.analyisisControls_box.setTitle(_translate("BATT5", "Analysis Controls"))
        self.runStaticAnalysis_button.setText(_translate("BATT5", "Run Static Analysis"))
        self.runDynamicAnalysis_button.setText(_translate("BATT5", "Run Dynamic Analysis"))
        self.pluginControls_box.setTitle(_translate("BATT5", "Plugin Controls"))
        self.generateScript_button.setText(_translate("BATT5", "Generate Output Field"))
        self.analysis_box.setTitle(_translate("BATT5", "Analysis View"))
        self.vewFunc_tree.headerItem().setText(0, _translate("BATT5", "Functions"))
        self.viewString_tree.headerItem().setText(0, _translate("BATT5", "Strings"))
        self.viewVar_tree.headerItem().setText(0, _translate("BATT5", "Variables"))
        self.viewDll_tree.headerItem().setText(0, _translate("BATT5", "DLL\'s"))
        self.radareConsole_box.setTitle(_translate("BATT5", "r2 Command Prompt"))
        self.radareConsoleIn_lineEdit.setPlaceholderText(_translate("BATT5", "BATT5$"))
        self.comment_box.setTitle(_translate("BATT5", "Comment View"))
        self.commentSave_button.setText(_translate("BATT5", "Save"))
        self.commentClear_button.setText(_translate("BATT5", "Clear"))
        self.poi_box.setTitle(_translate("BATT5", "Points of Interest"))
        self.poiType_label.setText(_translate("BATT5", "Type"))
        self.poiType_dropdown.setItemText(0, _translate("BATT5", "Function"))
        self.poiType_dropdown.setItemText(1, _translate("BATT5", "String"))
        self.poiType_dropdown.setItemText(2, _translate("BATT5", "Variable"))
        self.poiType_dropdown.setItemText(3, _translate("BATT5", "DLL"))
        self.check_allpoi.setText(_translate("BATT5", "Check/Uncheck ALL"))
        self.poiSearch_lineEdit.setPlaceholderText(_translate("BATT5", "Search.."))
        self.viewCurrent_box.setTitle(_translate("BATT5", "Switch View"))
        self.switchToHistory_button.setText(_translate("BATT5", "Switch to History View"))
        self.project_box_h.setTitle(_translate("BATT5", "Properties"))
        self.projectProperties_text_h.setHtml(_translate("BATT5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:7.8pt;\"><br /></p></body></html>"))
        self.daRuns_box.setTitle(_translate("BATT5", "Dynamic Analysis Runs"))
        self.recentCmd_box.setTitle(_translate("BATT5", "Recent Command History"))
        self.daRunDetails_box.setTitle(_translate("BATT5", "Dynamic Analysis Run Details"))
        self.comment_box_2.setTitle(_translate("BATT5", "Comment View"))
        self.commentSave_button_2.setText(_translate("BATT5", "Save"))
        self.commentClear_button_2.setText(_translate("BATT5", "Clear"))
        self.poi_box_2.setTitle(_translate("BATT5", "Points of Interest"))
        self.poiType_dropdown_2.setItemText(0, _translate("BATT5", "Function"))
        self.poiType_dropdown_2.setItemText(1, _translate("BATT5", "String"))
        self.poiType_dropdown_2.setItemText(2, _translate("BATT5", "Variable"))
        self.poiType_dropdown_2.setItemText(3, _translate("BATT5", "DLL"))
        self.poiType_dropdown_2.setItemText(4, _translate("BATT5", "Packet Protocol"))
        self.poiType_dropdown_2.setItemText(5, _translate("BATT5", "Struct"))
        self.poiType_label_2.setText(_translate("BATT5", "Type"))
        self.poiSearch_lineEdit_2.setText(_translate("BATT5", "Search.."))
        self.switchToCurrent_box.setTitle(_translate("BATT5", "Switch View"))
        self.switchToCurrent_button.setText(_translate("BATT5", "Switch to Curent View"))
        self.central_tabs.setTabText(self.central_tabs.indexOf(self.analysis_tab), _translate("BATT5", "Analysis"))
        self.pluginManagement_box.setTitle(_translate("BATT5", "Plugin Management"))
        self.pluginManagementSearch_lineEdit.setPlaceholderText(_translate("BATT5", "Search.."))
        self.dpm_box.setTitle(_translate("BATT5", "Detailed Plugin Management"))
        self.dpmPluginStructure_label.setText(_translate("BATT5", "Plugin Structure:"))
        self.dpmPluginStructure_button.setText(_translate("BATT5", "Browse"))
        self.clearXMLPlugin_button.setText(_translate("BATT5", "Clear"))
        self.saveXMLPlugin_button.setText(_translate("BATT5", "Save"))
        self.label_2.setText(_translate("BATT5", "Add Plugin Through XML Input"))
        self.dpmOutFuncName_label.setText(_translate("BATT5", "Output Function Name:"))
        self.dpmOutName_lable.setText(_translate("BATT5", "Output Name:"))
        self.clearManualPlugin_button.setText(_translate("BATT5", "Clear"))
        self.saveManualPlugin_button.setText(_translate("BATT5", "Save"))
        self.dpmOutFuncSource_label.setText(_translate("BATT5", "Output Function Source:"))
        self.dpmOutFuncSource_button.setText(_translate("BATT5", "Browse"))
        self.pluginEditingStatus_label.setText(_translate("BATT5", "Add Plugin Through Manual Input"))
        self.dpmPluginDesc_label.setText(_translate("BATT5", "*Description:"))
        self.label_7.setText(_translate("BATT5", "Points of Interest Will be Added Below"))
        self.dpmPluginName_label.setText(_translate("BATT5", "*Name:"))
        self.poiManagement_box.setTitle(_translate("BATT5", "Points of Interest Management"))
        self.label_6.setText(_translate("BATT5", "Type"))
        self.addPoiType_dropdown.setItemText(0, _translate("BATT5", "Function"))
        self.addPoiType_dropdown.setItemText(1, _translate("BATT5", "String"))
        self.addPoiType_dropdown.setItemText(2, _translate("BATT5", "Variable"))
        self.addPoiType_dropdown.setItemText(3, _translate("BATT5", "DLL"))
        self.poiManagementSeach_lineEdit.setPlaceholderText(_translate("BATT5", "Search.."))
        self.dpoim_box.setTitle(_translate("BATT5", "Detailed Points of Interest Management"))
        self.dpoimPredefined_button.setText(_translate("BATT5", "Browse"))
        self.dpoimPredefined_label.setText(_translate("BATT5", "Predefined Data Set:"))
        self.clearPredefPoi_button.setText(_translate("BATT5", "Clear"))
        self.savePredefPoi_button.setText(_translate("BATT5", "Save"))
        self.addPoiXML_label.setText(_translate("BATT5", "Add POI to Plugin Through XML Input"))
        self.addPoi_label.setText(_translate("BATT5", "*Point of Interest  Name:"))
        self.clearPoiAll_button.setText(_translate("BATT5", "Clear"))
        self.savePoi_button.setText(_translate("BATT5", "Save POI"))
        self.addPoiManual_label.setText(_translate("BATT5", "Add POI to Plugin Through Manual Input"))
        self.central_tabs.setTabText(self.central_tabs.indexOf(self.management_tab), _translate("BATT5", "Management"))
        self.file_menu.setTitle(_translate("BATT5", "File"))
        self.menuHelp.setTitle(_translate("BATT5", "Help"))
        self.actionNew_Project.setText(_translate("BATT5", "New Project"))
        self.actionSave.setText(_translate("BATT5", "Save"))
        self.actionOpen.setText(_translate("BATT5", "Open..."))
        self.actionSave_Analysis.setText(_translate("BATT5", "Save Analysis"))
        self.actionSave_as.setText(_translate("BATT5", "Save as..."))
        self.actionDocumentation.setText(_translate("BATT5", "Documentation"))
        self.actionSave_Analysis_2.setText(_translate("BATT5", "Save Analysis"))
        self.actionOpen_Project.setText(_translate("BATT5", "Open Project"))
        self.actionExport_Project.setText(_translate("BATT5", "Export Project"))

